# `make verify` is the one thing that has to pass before a change lands.
# CI runs exactly this and nothing else — see .github/workflows/ci.yml.
.DEFAULT_GOAL := help
BIN := bin

.PHONY: help verify build test lint fmt generate check-generate check-brand-assets check-markdown configdoc compose-env web-build web-typecheck web-test web-lint dev

help: ## List available targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

verify: ## Full gate; everything CI runs
	@printf '\n\033[36m==> 1/9 lint\033[0m\n'
	@$(MAKE) --no-print-directory lint
	@printf '\n\033[36m==> 2/9 build\033[0m\n'
	@$(MAKE) --no-print-directory build
	@printf '\n\033[36m==> 3/9 configuration docs\033[0m\n'
	@$(MAKE) --no-print-directory configdoc
	@printf '\n\033[36m==> 4/9 generated-code drift\033[0m\n'
	@$(MAKE) --no-print-directory check-generate
	@printf '\n\033[36m==> 5/9 Compose environment contract\033[0m\n'
	@$(MAKE) --no-print-directory compose-env
	@printf '\n\033[36m==> 6/9 tests\033[0m\n'
	@$(MAKE) --no-print-directory test
	@printf '\n\033[36m==> 7/9 brand assets\033[0m\n'
	@$(MAKE) --no-print-directory check-brand-assets
	@printf '\n\033[36m==> 8/9 markdown rendering\033[0m\n'
	@$(MAKE) --no-print-directory check-markdown
	@printf '\n\033[36m==> 9/9 frontend\033[0m\n'
	@$(MAKE) --no-print-directory web-lint web-typecheck web-test web-build
	@printf '\n\033[32mv verify passed\033[0m\n'

# Block-level markdown defects (a paragraph swallowed into a setext heading, an
# ordered list absorbed into the paragraph above it) are invisible in the source
# and only appear once rendered, so the criterion is the parsed token stream.
#
# Wired here as well as from the repository root because this tree is published
# on its own: a Community checkout that cannot run the check is a check that does
# not exist for the people reading these docs. It enumerates through
# `git ls-files`, so in this tree it sees exactly this tree's markdown.
check-markdown: ## Verify markdown block structure renders as written
	cd web && node scripts/check-markdown-render.mjs --self-test
	cd web && node scripts/check-markdown-render.mjs

check-generate: ## Regenerate and fail if any generated byte or path changes
	bash scripts/check-generate.sh --self-test
	bash scripts/check-generate.sh "Generated" go.mod \
		"$(MAKE) --no-print-directory generate" $(GENERATED)

build: ## Build the binary
	go build -o $(BIN)/fairlb ./cmd/fairlb

test: ## Run tests (needs Docker: tests start a real PostgreSQL)
	go test ./... -count=1

lint: ## Static checks
	go vet ./...
	gofmt -l . | tee /dev/stderr | (! read)

fmt: ## Format
	gofmt -w .

# Everything that is produced rather than written. The drift check in `verify`
# covers exactly this list, and refuses to run if any entry has gone missing —
# a check pointed at a path that no longer exists passes for the wrong reason.
GENERATED := foundation/errcode internal/gateway/db \
	internal/community/db \
	internal/gateway/consoleapi/api.gen.go internal/gateway/staffapi/api.gen.go \
	internal/community/staffapi/api.gen.go \
	web/packages/api-client/src/gen web/packages/api-client/src/errors.gen.ts

generate: ## Code generation (SQL -> Go, error registry -> constants, OpenAPI -> server + client)
	go tool sqlc generate
	go run ./tools/errgen
	go tool oapi-codegen -config api/gateway-console.codegen.yaml api/gateway-console.yaml
	go tool oapi-codegen -config api/gateway-staff.codegen.yaml api/gateway-staff.yaml
	go tool oapi-codegen -config api/staff.codegen.yaml api/staff.yaml
	go run ./tools/configdoc
	# `pnpm generate` at the web root, not the filtered form: the root script
	# runs the formatter afterwards. orval emits unformatted output, so calling
	# it directly leaves a diff against the committed files that is entirely
	# quotes and line breaks — and the drift check cannot tell that from a real
	# one. Measured: 6 files, ~11k lines, on a tree nobody had touched.
	cd web && pnpm generate

configdoc: ## Verify Community configuration reference matches metadata
	go run ./tools/configdoc -check

compose-env: ## Verify .env.example through Docker Compose interpolation
	python3 scripts/check-compose-env.py

check-brand-assets: ## Verify source identity, icon dimensions and manifest brand tokens
	node web/scripts/check-brand-assets.mjs --self-test
	node web/scripts/check-brand-assets.mjs --scope public

web-typecheck: ## Typecheck the frontend
	cd web && pnpm typecheck

web-test: ## Run frontend unit and composition tests
	# The bundle guard's own three cases. It only ever fires on a developer's
	# machine -- each CI job installs its own workspace last -- so without this
	# nothing would notice it going quiet.
	cd web && node scripts/check-app-bundle.mjs --self-test
	cd web && pnpm test

web-lint: ## Lint and format-check the frontend
	cd web && pnpm lint && pnpm fmt:check

web-build: ## Build the admin UI
	cd web && pnpm build
	cd web && BRAND_PROFILE_PATH="$(CURDIR)/web/packages/brand/fixtures/acme-route/profile.json" \
		pnpm --fail-if-no-match --filter @fairlb/staff build

dev: ## Run locally (set DATABASE_URL and SECRET_KEY first)
	go run ./cmd/fairlb serve
