// Package gwconsoleapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package gwconsoleapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for OrgProviderKeyStatus.
const (
	Active   OrgProviderKeyStatus = "active"
	Disabled OrgProviderKeyStatus = "disabled"
	Invalid  OrgProviderKeyStatus = "invalid"
)

// Valid indicates whether the value is a known member of the OrgProviderKeyStatus enum.
func (e OrgProviderKeyStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Disabled:
		return true
	case Invalid:
		return true
	default:
		return false
	}
}

// Defines values for ListRequestLogsParamsStatus.
const (
	ListRequestLogsParamsStatusCanceled      ListRequestLogsParamsStatus = "canceled"
	ListRequestLogsParamsStatusClientError   ListRequestLogsParamsStatus = "client_error"
	ListRequestLogsParamsStatusOk            ListRequestLogsParamsStatus = "ok"
	ListRequestLogsParamsStatusUpstreamError ListRequestLogsParamsStatus = "upstream_error"
)

// Valid indicates whether the value is a known member of the ListRequestLogsParamsStatus enum.
func (e ListRequestLogsParamsStatus) Valid() bool {
	switch e {
	case ListRequestLogsParamsStatusCanceled:
		return true
	case ListRequestLogsParamsStatusClientError:
		return true
	case ListRequestLogsParamsStatusOk:
		return true
	case ListRequestLogsParamsStatusUpstreamError:
		return true
	default:
		return false
	}
}

// Defines values for ExportLogsCSVParamsStatus.
const (
	ExportLogsCSVParamsStatusCanceled      ExportLogsCSVParamsStatus = "canceled"
	ExportLogsCSVParamsStatusClientError   ExportLogsCSVParamsStatus = "client_error"
	ExportLogsCSVParamsStatusOk            ExportLogsCSVParamsStatus = "ok"
	ExportLogsCSVParamsStatusUpstreamError ExportLogsCSVParamsStatus = "upstream_error"
)

// Valid indicates whether the value is a known member of the ExportLogsCSVParamsStatus enum.
func (e ExportLogsCSVParamsStatus) Valid() bool {
	switch e {
	case ExportLogsCSVParamsStatusCanceled:
		return true
	case ExportLogsCSVParamsStatusClientError:
		return true
	case ExportLogsCSVParamsStatusOk:
		return true
	case ExportLogsCSVParamsStatusUpstreamError:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageParamsGranularity.
const (
	GetUsageParamsGranularityDay  GetUsageParamsGranularity = "day"
	GetUsageParamsGranularityHour GetUsageParamsGranularity = "hour"
)

// Valid indicates whether the value is a known member of the GetUsageParamsGranularity enum.
func (e GetUsageParamsGranularity) Valid() bool {
	switch e {
	case GetUsageParamsGranularityDay:
		return true
	case GetUsageParamsGranularityHour:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageParamsGroupBy.
const (
	ApiKey GetUsageParamsGroupBy = "api_key"
	Model  GetUsageParamsGroupBy = "model"
)

// Valid indicates whether the value is a known member of the GetUsageParamsGroupBy enum.
func (e GetUsageParamsGroupBy) Valid() bool {
	switch e {
	case ApiKey:
		return true
	case Model:
		return true
	default:
		return false
	}
}

// Defines values for ExportUsageCSVParamsGranularity.
const (
	ExportUsageCSVParamsGranularityDay  ExportUsageCSVParamsGranularity = "day"
	ExportUsageCSVParamsGranularityHour ExportUsageCSVParamsGranularity = "hour"
)

// Valid indicates whether the value is a known member of the ExportUsageCSVParamsGranularity enum.
func (e ExportUsageCSVParamsGranularity) Valid() bool {
	switch e {
	case ExportUsageCSVParamsGranularityDay:
		return true
	case ExportUsageCSVParamsGranularityHour:
		return true
	default:
		return false
	}
}

// AvailableModel defines model for AvailableModel.
type AvailableModel struct {
	// Capabilities Display metadata such as vision or tool support.
	//
	// What can actually be called is always what the model's routes have
	// been verified to serve: a capability advertised here with no
	// verified route behind it only gets the caller a 404.
	Capabilities  *map[string]interface{} `json:"capabilities,omitempty"`
	ContextWindow *int                    `json:"context_window,omitempty"`
	DisplayName   *string                 `json:"display_name,omitempty"`

	// Endpoints Which endpoints this model can be called on — chat, messages,
	// embeddings and so on — every endpoint a probe has verified on one
	// of its enabled routes.
	//
	// This is not a capability list. It answers "which URL do I send
	// to", not "can this model read an image"; for that, see
	// `capabilities`.
	Endpoints []string `json:"endpoints"`

	// IsFree Omitted for a caller without the financial read capability
	IsFree          *bool `json:"is_free,omitempty"`
	MaxOutputTokens *int  `json:"max_output_tokens,omitempty"`

	// PriceCacheReadNanoPerMtok Omitted for a caller without the financial read capability
	PriceCacheReadNanoPerMtok *int64 `json:"price_cache_read_nano_per_mtok,omitempty"`

	// PriceCacheWriteNanoPerMtok Omitted for a caller without the financial read capability
	PriceCacheWriteNanoPerMtok *int64 `json:"price_cache_write_nano_per_mtok,omitempty"`

	// PriceInNanoPerMtok Omitted for a caller without the financial read capability
	PriceInNanoPerMtok *int64 `json:"price_in_nano_per_mtok,omitempty"`

	// PriceOutNanoPerMtok Omitted for a caller without the financial read capability
	PriceOutNanoPerMtok *int64 `json:"price_out_nano_per_mtok,omitempty"`

	// Protocols The protocols the verified endpoints belong to. A model owns no
	// protocol of its own: it is reachable on whichever protocols its
	// routes' providers speak, and the same slug may be callable on both
	// `/v1/chat/completions` and `/v1/messages`.
	Protocols []string `json:"protocols"`
	Slug      string   `json:"slug"`
}

// OrgProviderKey defines model for OrgProviderKey.
type OrgProviderKey struct {
	// AllowFallback Whether a request rejected with this credential may fall back to the deployment's own, which is billed at the full rate
	AllowFallback  bool       `json:"allow_fallback"`
	BaseUrl        *string    `json:"base_url,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	Id             string     `json:"id"`
	LastVerifiedAt *time.Time `json:"last_verified_at,omitempty"`
	Name           string     `json:"name"`

	// SecretHint A masked form of the credential. The stored value cannot be read back, so this is how you recognize which credential a row holds.
	SecretHint string `json:"secret_hint"`

	// Status `invalid` means the upstream rejected this credential; it has to be replaced
	Status OrgProviderKeyStatus `json:"status"`
	Vendor string               `json:"vendor"`

	// VendorLabel The platform's display name, resolved when this deployment's build knows the vendor.
	VendorLabel *string `json:"vendor_label,omitempty"`
}

// OrgProviderKeyStatus `invalid` means the upstream rejected this credential; it has to be replaced
type OrgProviderKeyStatus string

// OrgProviderKeyTestResult defines model for OrgProviderKeyTestResult.
type OrgProviderKeyTestResult struct {
	CheckedAt time.Time `json:"checked_at"`
	LatencyMs *int      `json:"latency_ms,omitempty"`

	// Message On failure, the upstream's own message (truncated) — the only thing that distinguishes a bad credential from a wrong model name from an exhausted quota
	Message    *string `json:"message,omitempty"`
	Ok         bool    `json:"ok"`
	StatusCode *int    `json:"status_code,omitempty"`
}

// OrgProviderVendor defines model for OrgProviderVendor.
type OrgProviderVendor struct {
	// BaseUrlHint The endpoint this deployment would use for that vendor when the credential leaves base_url empty.
	BaseUrlHint *string `json:"base_url_hint,omitempty"`

	// KeyHint What shape the credential takes, so the field can say what to paste.
	KeyHint *string `json:"key_hint,omitempty"`

	// Label The platform's own name, for display. Not translated.
	Label string `json:"label"`

	// ModelIdExample One model id as this vendor spells it, for the connectivity test's input.
	ModelIdExample *string `json:"model_id_example,omitempty"`
	Vendor         string  `json:"vendor"`
}

// Problem RFC 9457 problem+json, plus a stable machine-readable `code`
type Problem struct {
	// Code The stable error code
	Code      string  `json:"code"`
	Detail    *string `json:"detail,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      *string `json:"type,omitempty"`
}

// RequestLog defines model for RequestLog.
type RequestLog struct {
	// ApiKeyId An API key's `key_…` public id; omitted without `keys.manage`.
	ApiKeyId *string `json:"api_key_id,omitempty"`

	// ChargedNano 0 for a caller without the financial read capability
	ChargedNano int64     `json:"charged_nano"`
	CreatedAt   time.Time `json:"created_at"`
	DurationMs  *int      `json:"duration_ms,omitempty"`
	EndUserId   *string   `json:"end_user_id,omitempty"`
	ErrorCode   *string   `json:"error_code,omitempty"`
	HttpStatus  int       `json:"http_status"`
	ModelSlug   string    `json:"model_slug"`
	RequestId   string    `json:"request_id"`
	Status      string    `json:"status"`
	Stream      *bool     `json:"stream,omitempty"`
	Surface     string    `json:"surface"`
	TokensIn    *int64    `json:"tokens_in,omitempty"`
	TokensOut   *int64    `json:"tokens_out,omitempty"`
}

// RequestLogDetail defines model for RequestLogDetail.
type RequestLogDetail struct {
	// ApiKeyId An API key's `key_…` public id; omitted without `keys.manage`.
	ApiKeyId *string `json:"api_key_id,omitempty"`

	// ChargedCurrency Omitted for a caller without the financial read capability
	ChargedCurrency *string `json:"charged_currency,omitempty"`

	// ChargedNano 0 for a caller without the financial read capability
	ChargedNano  int64     `json:"charged_nano"`
	CreatedAt    time.Time `json:"created_at"`
	DurationMs   *int      `json:"duration_ms,omitempty"`
	EndUserId    *string   `json:"end_user_id,omitempty"`
	ErrorCode    *string   `json:"error_code,omitempty"`
	HttpStatus   int       `json:"http_status"`
	ModelSlug    string    `json:"model_slug"`
	ProviderSlug *string   `json:"provider_slug,omitempty"`
	RequestId    string    `json:"request_id"`

	// RouteAttempts How many routes this request actually tried; more than one means it failed over
	RouteAttempts    *int   `json:"route_attempts,omitempty"`
	Status           string `json:"status"`
	Stream           *bool  `json:"stream,omitempty"`
	Surface          string `json:"surface"`
	TokensCacheWrite *int64 `json:"tokens_cache_write,omitempty"`
	TokensCachedRead *int64 `json:"tokens_cached_read,omitempty"`
	TokensIn         *int64 `json:"tokens_in,omitempty"`
	TokensOut        *int64 `json:"tokens_out,omitempty"`
	TokensReasoning  *int64 `json:"tokens_reasoning,omitempty"`
	TtftMs           *int   `json:"ttft_ms,omitempty"`

	// UsageEstimated The upstream reported no usage, so this charge is based on an estimate
	UsageEstimated *bool `json:"usage_estimated,omitempty"`
}

// UsageGroup defines model for UsageGroup.
type UsageGroup struct {
	// ChargedNano 0 for a caller without the financial read capability
	ChargedNano int64 `json:"charged_nano"`

	// Key The value of the grouping dimension — a model slug, or an API key's `key_…` public id
	Key string `json:"key"`

	// Label A display name; the key's name when grouping by key, otherwise the same as `key`
	Label     *string `json:"label,omitempty"`
	Requests  int64   `json:"requests"`
	TokensIn  int64   `json:"tokens_in"`
	TokensOut int64   `json:"tokens_out"`
}

// UsageLatency Latency percentiles, interpolated from cumulative histograms. They are
// not an average of per-bucket percentiles: percentiles cannot be
// averaged.
type UsageLatency struct {
	// HasSamples False means this range contains no latency samples at all, which is not the same as a latency of 0
	HasSamples bool `json:"has_samples"`
	MeanMs     *int `json:"mean_ms,omitempty"`
	P50Ms      *int `json:"p50_ms,omitempty"`
	P95Ms      *int `json:"p95_ms,omitempty"`

	// P95Unbounded True when p95 falls beyond the histogram's largest bucket bound, in which case p95_ms reads as "at least this much"
	P95Unbounded *bool `json:"p95_unbounded,omitempty"`
}

// UsagePoint defines model for UsagePoint.
type UsagePoint struct {
	BucketStart time.Time `json:"bucket_start"`

	// ChargedNano 0 for a caller without the financial read capability
	ChargedNano int64  `json:"charged_nano"`
	Errors      *int64 `json:"errors,omitempty"`
	Requests    int64  `json:"requests"`
	TokensIn    int64  `json:"tokens_in"`
	TokensOut   int64  `json:"tokens_out"`
}

// UsageReport defines model for UsageReport.
type UsageReport struct {
	// Groups Totals per grouping dimension; empty when `group_by` is not given.
	// Ordered by amount for a caller with the financial read capability,
	// and by `requests DESC, key ASC` for one without it.
	Groups *[]UsageGroup `json:"groups,omitempty"`

	// Series Totals per time bucket, oldest first
	Series []UsagePoint `json:"series"`
	Totals UsageTotals  `json:"totals"`
}

// UsageTotals defines model for UsageTotals.
type UsageTotals struct {
	// ChargedNano 0 for a caller without the financial read capability
	ChargedNano int64 `json:"charged_nano"`

	// Currency The currency amounts are in; empty for a caller without the financial read capability
	Currency string `json:"currency"`
	Errors   *int64 `json:"errors,omitempty"`

	// Latency Latency percentiles, interpolated from cumulative histograms. They are
	// not an average of per-bucket percentiles: percentiles cannot be
	// averaged.
	Latency   *UsageLatency `json:"latency,omitempty"`
	Requests  int64         `json:"requests"`
	TokensIn  int64         `json:"tokens_in"`
	TokensOut int64         `json:"tokens_out"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// OrgID defines model for OrgID.
type OrgID = string

// ListRequestLogsParams defines parameters for ListRequestLogs.
type ListRequestLogsParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// ApiKeyId An API key's `key_…` public id. Requires `keys.manage`; a caller who
	// can read the organization but lacks that capability gets a 403.
	ApiKeyId  *string                      `form:"api_key_id,omitempty" json:"api_key_id,omitempty"`
	Model     *string                      `form:"model,omitempty" json:"model,omitempty"`
	Status    *ListRequestLogsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	EndUserId *string                      `form:"end_user_id,omitempty" json:"end_user_id,omitempty"`

	// Cursor The `next_cursor` from the previous page, passed back verbatim. It is
	// opaque: internally it is a composite of timestamp and id, because a
	// timestamp alone would skip the other rows sharing that instant.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRequestLogsParamsStatus defines parameters for ListRequestLogs.
type ListRequestLogsParamsStatus string

// ExportLogsCSVParams defines parameters for ExportLogsCSV.
type ExportLogsCSVParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// ApiKeyId An API key's `key_…` public id
	ApiKeyId  *string                    `form:"api_key_id,omitempty" json:"api_key_id,omitempty"`
	Model     *string                    `form:"model,omitempty" json:"model,omitempty"`
	Status    *ExportLogsCSVParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	EndUserId *string                    `form:"end_user_id,omitempty" json:"end_user_id,omitempty"`
}

// ExportLogsCSVParamsStatus defines parameters for ExportLogsCSV.
type ExportLogsCSVParamsStatus string

// ListAvailableModelsParams defines parameters for ListAvailableModels.
type ListAvailableModelsParams struct {
	// IfNoneMatch The ETag from a previous response; unchanged, the answer is 304
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// ListOrgProviderKeysParams defines parameters for ListOrgProviderKeys.
type ListOrgProviderKeysParams struct {
	// Cursor Where to resume from — the previous response's `next_cursor`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Rows per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrgProviderKeyJSONBody defines parameters for CreateOrgProviderKey.
type CreateOrgProviderKeyJSONBody struct {
	// AllowFallback Whether a request rejected with this credential may fall back to the deployment's own. False by default, deliberately - falling back silently means the request is billed at the full rate rather than the service fee, and a surprising bill is worse than a failed request. Turn it on only when availability matters more.
	AllowFallback *bool `json:"allow_fallback,omitempty"`

	// BaseUrl A custom upstream endpoint; empty means this deployment's default for that vendor
	BaseUrl *string `json:"base_url,omitempty"`

	// Name A label, unique within the organization, for telling several credentials apart
	Name string `json:"name"`

	// Secret The upstream credential itself. It is encrypted before it is stored and no endpoint can read it back.
	Secret string `json:"secret"`

	// Vendor Which platform this credential is with, from the vendors list on the GET above.
	// A vendor this deployment does not route to is refused: the credential could never
	// apply to anything.
	Vendor string `json:"vendor"`
}

// TestOrgProviderKeyJSONBody defines parameters for TestOrgProviderKey.
type TestOrgProviderKeyJSONBody struct {
	// UpstreamModel The model name as the upstream knows it
	UpstreamModel string `json:"upstream_model"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	From        time.Time                  `form:"from" json:"from"`
	To          time.Time                  `form:"to" json:"to"`
	Granularity *GetUsageParamsGranularity `form:"granularity,omitempty" json:"granularity,omitempty"`

	// GroupBy The grouping dimension. Omitted, the response carries only the time
	// series. Grouping by `api_key` requires `keys.manage`; a caller who
	// can read the organization but lacks that capability gets a 403 rather
	// than a silently ungrouped answer.
	GroupBy *GetUsageParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`

	// ApiKeyId Restrict to one API key, given as its `key_…` public id. Requires
	// `keys.manage`; a caller who can read the organization but lacks that
	// capability gets a 403.
	ApiKeyId *string `form:"api_key_id,omitempty" json:"api_key_id,omitempty"`

	// Tz An IANA time zone name such as `Asia/Shanghai`, which decides where a
	// day boundary falls when `granularity=day`. Defaults to UTC.
	//
	// It matters because buckets are stored on UTC hour boundaries while a
	// chart usually labels its axis in the reader's local zone. If the two
	// disagree, a daily bar spans two local days and its label can be off by
	// a full day.
	//
	// Ignored when `granularity=hour`.
	Tz *string `form:"tz,omitempty" json:"tz,omitempty"`
}

// GetUsageParamsGranularity defines parameters for GetUsage.
type GetUsageParamsGranularity string

// GetUsageParamsGroupBy defines parameters for GetUsage.
type GetUsageParamsGroupBy string

// ExportUsageCSVParams defines parameters for ExportUsageCSV.
type ExportUsageCSVParams struct {
	From        time.Time                        `form:"from" json:"from"`
	To          time.Time                        `form:"to" json:"to"`
	Granularity *ExportUsageCSVParamsGranularity `form:"granularity,omitempty" json:"granularity,omitempty"`

	// ApiKeyId As on `/usage`: restrict the export to one API key, given as its
	// `key_…` public id. The export honours the filter, so filtering to one
	// key exports only that key. Requires `keys.manage` in addition to the
	// financial read capability.
	ApiKeyId *string `form:"api_key_id,omitempty" json:"api_key_id,omitempty"`

	// Tz As on `/usage`. The export and the chart must agree, or a reader cross-checking them will see two different day boundaries.
	Tz *string `form:"tz,omitempty" json:"tz,omitempty"`
}

// ExportUsageCSVParamsGranularity defines parameters for ExportUsageCSV.
type ExportUsageCSVParamsGranularity string

// CreateOrgProviderKeyJSONRequestBody defines body for CreateOrgProviderKey for application/json ContentType.
type CreateOrgProviderKeyJSONRequestBody CreateOrgProviderKeyJSONBody

// TestOrgProviderKeyJSONRequestBody defines body for TestOrgProviderKey for application/json ContentType.
type TestOrgProviderKeyJSONRequestBody TestOrgProviderKeyJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListRequestLogs Request log, filterable and cursor-paginated
	// (GET /orgs/{org_id}/logs)
	ListRequestLogs(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListRequestLogsParams)
	// ExportLogsCSV Export the request log as CSV, with the same filters
	// (GET /orgs/{org_id}/logs.csv)
	ExportLogsCSV(w http.ResponseWriter, r *http.Request, orgId OrgID, params ExportLogsCSVParams)
	// GetRequestLog One request, including its error and the routes it tried
	// (GET /orgs/{org_id}/logs/{request_id})
	GetRequestLog(w http.ResponseWriter, r *http.Request, orgId OrgID, requestId string)
	// ListAvailableModels The models this organization can call
	// (GET /orgs/{org_id}/models)
	ListAvailableModels(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListAvailableModelsParams)
	// ListOrgProviderKeys List the upstream credentials this organization brought itself
	// (GET /orgs/{org_id}/provider-keys)
	ListOrgProviderKeys(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListOrgProviderKeysParams)
	// CreateOrgProviderKey Add an upstream credential (it appears only in this request and is encrypted at rest)
	// (POST /orgs/{org_id}/provider-keys)
	CreateOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID)
	// DeleteOrgProviderKey Delete an upstream credential
	// (DELETE /orgs/{org_id}/provider-keys/{key_id})
	DeleteOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID, keyId string)
	// TestOrgProviderKey Test a credential by making one minimal upstream request
	// (POST /orgs/{org_id}/provider-keys/{key_id}/test)
	TestOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID, keyId string)
	// GetUsage Usage over time, optionally grouped
	// (GET /orgs/{org_id}/usage)
	GetUsage(w http.ResponseWriter, r *http.Request, orgId OrgID, params GetUsageParams)
	// ExportUsageCSV Export usage as CSV, with the same filters as /usage
	// (GET /orgs/{org_id}/usage.csv)
	ExportUsageCSV(w http.ResponseWriter, r *http.Request, orgId OrgID, params ExportUsageCSVParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListRequestLogs Request log, filterable and cursor-paginated
// (GET /orgs/{org_id}/logs)
func (_ Unimplemented) ListRequestLogs(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListRequestLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ExportLogsCSV Export the request log as CSV, with the same filters
// (GET /orgs/{org_id}/logs.csv)
func (_ Unimplemented) ExportLogsCSV(w http.ResponseWriter, r *http.Request, orgId OrgID, params ExportLogsCSVParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRequestLog One request, including its error and the routes it tried
// (GET /orgs/{org_id}/logs/{request_id})
func (_ Unimplemented) GetRequestLog(w http.ResponseWriter, r *http.Request, orgId OrgID, requestId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListAvailableModels The models this organization can call
// (GET /orgs/{org_id}/models)
func (_ Unimplemented) ListAvailableModels(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListAvailableModelsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListOrgProviderKeys List the upstream credentials this organization brought itself
// (GET /orgs/{org_id}/provider-keys)
func (_ Unimplemented) ListOrgProviderKeys(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListOrgProviderKeysParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrgProviderKey Add an upstream credential (it appears only in this request and is encrypted at rest)
// (POST /orgs/{org_id}/provider-keys)
func (_ Unimplemented) CreateOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteOrgProviderKey Delete an upstream credential
// (DELETE /orgs/{org_id}/provider-keys/{key_id})
func (_ Unimplemented) DeleteOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// TestOrgProviderKey Test a credential by making one minimal upstream request
// (POST /orgs/{org_id}/provider-keys/{key_id}/test)
func (_ Unimplemented) TestOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUsage Usage over time, optionally grouped
// (GET /orgs/{org_id}/usage)
func (_ Unimplemented) GetUsage(w http.ResponseWriter, r *http.Request, orgId OrgID, params GetUsageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ExportUsageCSV Export usage as CSV, with the same filters as /usage
// (GET /orgs/{org_id}/usage.csv)
func (_ Unimplemented) ExportUsageCSV(w http.ResponseWriter, r *http.Request, orgId OrgID, params ExportUsageCSVParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListRequestLogs operation middleware
func (siw *ServerInterfaceWrapper) ListRequestLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRequestLogsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "api_key_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "api_key_id", r.URL.Query(), &params.ApiKeyId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "api_key_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "api_key_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", r.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "model"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end_user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_user_id", r.URL.Query(), &params.EndUserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end_user_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_user_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRequestLogs(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportLogsCSV operation middleware
func (siw *ServerInterfaceWrapper) ExportLogsCSV(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportLogsCSVParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "api_key_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "api_key_id", r.URL.Query(), &params.ApiKeyId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "api_key_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "api_key_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", r.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "model"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "end_user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_user_id", r.URL.Query(), &params.EndUserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end_user_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_user_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportLogsCSV(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRequestLog operation middleware
func (siw *ServerInterfaceWrapper) GetRequestLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "request_id" -------------
	var requestId string

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", chi.URLParam(r, "request_id"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "request_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRequestLog(w, r, orgId, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAvailableModels operation middleware
func (siw *ServerInterfaceWrapper) ListAvailableModels(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAvailableModelsParams

	headers := r.Header

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAvailableModels(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrgProviderKeys operation middleware
func (siw *ServerInterfaceWrapper) ListOrgProviderKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrgProviderKeysParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrgProviderKeys(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrgProviderKey operation middleware
func (siw *ServerInterfaceWrapper) CreateOrgProviderKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrgProviderKey(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrgProviderKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrgProviderKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrgProviderKey(w, r, orgId, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestOrgProviderKey operation middleware
func (siw *ServerInterfaceWrapper) TestOrgProviderKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestOrgProviderKey(w, r, orgId, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "granularity", r.URL.Query(), &params.Granularity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "granularity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_by", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "group_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_by", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "api_key_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "api_key_id", r.URL.Query(), &params.ApiKeyId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "api_key_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "api_key_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tz" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tz", r.URL.Query(), &params.Tz, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tz"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tz", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsage(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportUsageCSV operation middleware
func (siw *ServerInterfaceWrapper) ExportUsageCSV(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgID

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportUsageCSVParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "granularity", r.URL.Query(), &params.Granularity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "granularity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "api_key_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "api_key_id", r.URL.Query(), &params.ApiKeyId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "api_key_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "api_key_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tz" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tz", r.URL.Query(), &params.Tz, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tz"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tz", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportUsageCSV(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/usage", wrapper.GetUsage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/usage.csv", wrapper.ExportUsageCSV)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/logs", wrapper.ListRequestLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/logs.csv", wrapper.ExportLogsCSV)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/logs/{request_id}", wrapper.GetRequestLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/models", wrapper.ListAvailableModels)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orgs/{org_id}/provider-keys", wrapper.ListOrgProviderKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/{org_id}/provider-keys", wrapper.CreateOrgProviderKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/orgs/{org_id}/provider-keys/{key_id}", wrapper.DeleteOrgProviderKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orgs/{org_id}/provider-keys/{key_id}/test", wrapper.TestOrgProviderKey)
	})

	return r
}

type ProblemResponseHeaders struct {
	XRequestId *string
}
type ProblemApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ProblemResponseHeaders
}

type ListRequestLogsRequestObject struct {
	OrgId  OrgID `json:"org_id"`
	Params ListRequestLogsParams
}

type ListRequestLogsResponseObject interface {
	VisitListRequestLogsResponse(w http.ResponseWriter) error
}

type ListRequestLogs200JSONResponse struct {
	Items []RequestLog `json:"items"`

	// NextCursor Null when there are no more pages
	NextCursor *string `json:"next_cursor,omitempty"`
}

func (response ListRequestLogs200JSONResponse) VisitListRequestLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRequestLogsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response ListRequestLogsdefaultApplicationProblemPlusJSONResponse) VisitListRequestLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportLogsCSVRequestObject struct {
	OrgId  OrgID `json:"org_id"`
	Params ExportLogsCSVParams
}

type ExportLogsCSVResponseObject interface {
	VisitExportLogsCSVResponse(w http.ResponseWriter) error
}

type ExportLogsCSV200TextcsvResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExportLogsCSV200TextcsvResponse) VisitExportLogsCSVResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/csv")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportLogsCSVdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response ExportLogsCSVdefaultApplicationProblemPlusJSONResponse) VisitExportLogsCSVResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLogRequestObject struct {
	OrgId     OrgID  `json:"org_id"`
	RequestId string `json:"request_id"`
}

type GetRequestLogResponseObject interface {
	VisitGetRequestLogResponse(w http.ResponseWriter) error
}

type GetRequestLog200JSONResponse RequestLogDetail

func (response GetRequestLog200JSONResponse) VisitGetRequestLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLogdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetRequestLogdefaultApplicationProblemPlusJSONResponse) VisitGetRequestLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListAvailableModelsRequestObject struct {
	OrgId  OrgID `json:"org_id"`
	Params ListAvailableModelsParams
}

type ListAvailableModelsResponseObject interface {
	VisitListAvailableModelsResponse(w http.ResponseWriter) error
}

type ListAvailableModels200ResponseHeaders struct {
	ETag *string
}

type ListAvailableModels200JSONResponse struct {
	Body struct {
		Items []AvailableModel `json:"items"`
	}
	Headers ListAvailableModels200ResponseHeaders
}

func (response ListAvailableModels200JSONResponse) VisitListAvailableModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAvailableModels304Response struct {
}

func (response ListAvailableModels304Response) VisitListAvailableModelsResponse(w http.ResponseWriter) error {
	w.WriteHeader(304)
	return nil
}

type ListAvailableModelsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response ListAvailableModelsdefaultApplicationProblemPlusJSONResponse) VisitListAvailableModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgProviderKeysRequestObject struct {
	OrgId  OrgID `json:"org_id"`
	Params ListOrgProviderKeysParams
}

type ListOrgProviderKeysResponseObject interface {
	VisitListOrgProviderKeysResponse(w http.ResponseWriter) error
}

type ListOrgProviderKeys200JSONResponse struct {
	Items []OrgProviderKey `json:"items"`

	// NextCursor Present when another page follows; pass it back as `cursor`
	NextCursor *string `json:"next_cursor,omitempty"`

	// Vendors The platforms a credential can usefully be supplied for here: the vendors this
	// deployment has an enabled provider at. A key for anything else could never take
	// effect, because no candidate would ever be served by it, and it would sit in the
	// list looking configured.
	//
	// It travels with the list rather than at an address of its own so that the page
	// showing the credentials and the form adding one read the same answer.
	Vendors []OrgProviderVendor `json:"vendors"`
}

func (response ListOrgProviderKeys200JSONResponse) VisitListOrgProviderKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOrgProviderKeysdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response ListOrgProviderKeysdefaultApplicationProblemPlusJSONResponse) VisitListOrgProviderKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgProviderKeyRequestObject struct {
	OrgId OrgID `json:"org_id"`
	Body  *CreateOrgProviderKeyJSONRequestBody
}

type CreateOrgProviderKeyResponseObject interface {
	VisitCreateOrgProviderKeyResponse(w http.ResponseWriter) error
}

type CreateOrgProviderKey201JSONResponse OrgProviderKey

func (response CreateOrgProviderKey201JSONResponse) VisitCreateOrgProviderKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrgProviderKeydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response CreateOrgProviderKeydefaultApplicationProblemPlusJSONResponse) VisitCreateOrgProviderKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrgProviderKeyRequestObject struct {
	OrgId OrgID  `json:"org_id"`
	KeyId string `json:"key_id"`
}

type DeleteOrgProviderKeyResponseObject interface {
	VisitDeleteOrgProviderKeyResponse(w http.ResponseWriter) error
}

type DeleteOrgProviderKey204Response struct {
}

func (response DeleteOrgProviderKey204Response) VisitDeleteOrgProviderKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOrgProviderKeydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response DeleteOrgProviderKeydefaultApplicationProblemPlusJSONResponse) VisitDeleteOrgProviderKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type TestOrgProviderKeyRequestObject struct {
	OrgId OrgID  `json:"org_id"`
	KeyId string `json:"key_id"`
	Body  *TestOrgProviderKeyJSONRequestBody
}

type TestOrgProviderKeyResponseObject interface {
	VisitTestOrgProviderKeyResponse(w http.ResponseWriter) error
}

type TestOrgProviderKey200JSONResponse OrgProviderKeyTestResult

func (response TestOrgProviderKey200JSONResponse) VisitTestOrgProviderKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TestOrgProviderKeydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response TestOrgProviderKeydefaultApplicationProblemPlusJSONResponse) VisitTestOrgProviderKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsageRequestObject struct {
	OrgId  OrgID `json:"org_id"`
	Params GetUsageParams
}

type GetUsageResponseObject interface {
	VisitGetUsageResponse(w http.ResponseWriter) error
}

type GetUsage200JSONResponse UsageReport

func (response GetUsage200JSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsagedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response GetUsagedefaultApplicationProblemPlusJSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUsageCSVRequestObject struct {
	OrgId  OrgID `json:"org_id"`
	Params ExportUsageCSVParams
}

type ExportUsageCSVResponseObject interface {
	VisitExportUsageCSVResponse(w http.ResponseWriter) error
}

type ExportUsageCSV200TextcsvResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ExportUsageCSV200TextcsvResponse) VisitExportUsageCSVResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/csv")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportUsageCSVdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	Headers    ProblemResponseHeaders
	StatusCode int
}

func (response ExportUsageCSVdefaultApplicationProblemPlusJSONResponse) VisitExportUsageCSVResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListRequestLogs Request log, filterable and cursor-paginated
	// (GET /orgs/{org_id}/logs)
	ListRequestLogs(ctx context.Context, request ListRequestLogsRequestObject) (ListRequestLogsResponseObject, error)
	// ExportLogsCSV Export the request log as CSV, with the same filters
	// (GET /orgs/{org_id}/logs.csv)
	ExportLogsCSV(ctx context.Context, request ExportLogsCSVRequestObject) (ExportLogsCSVResponseObject, error)
	// GetRequestLog One request, including its error and the routes it tried
	// (GET /orgs/{org_id}/logs/{request_id})
	GetRequestLog(ctx context.Context, request GetRequestLogRequestObject) (GetRequestLogResponseObject, error)
	// ListAvailableModels The models this organization can call
	// (GET /orgs/{org_id}/models)
	ListAvailableModels(ctx context.Context, request ListAvailableModelsRequestObject) (ListAvailableModelsResponseObject, error)
	// ListOrgProviderKeys List the upstream credentials this organization brought itself
	// (GET /orgs/{org_id}/provider-keys)
	ListOrgProviderKeys(ctx context.Context, request ListOrgProviderKeysRequestObject) (ListOrgProviderKeysResponseObject, error)
	// CreateOrgProviderKey Add an upstream credential (it appears only in this request and is encrypted at rest)
	// (POST /orgs/{org_id}/provider-keys)
	CreateOrgProviderKey(ctx context.Context, request CreateOrgProviderKeyRequestObject) (CreateOrgProviderKeyResponseObject, error)
	// DeleteOrgProviderKey Delete an upstream credential
	// (DELETE /orgs/{org_id}/provider-keys/{key_id})
	DeleteOrgProviderKey(ctx context.Context, request DeleteOrgProviderKeyRequestObject) (DeleteOrgProviderKeyResponseObject, error)
	// TestOrgProviderKey Test a credential by making one minimal upstream request
	// (POST /orgs/{org_id}/provider-keys/{key_id}/test)
	TestOrgProviderKey(ctx context.Context, request TestOrgProviderKeyRequestObject) (TestOrgProviderKeyResponseObject, error)
	// GetUsage Usage over time, optionally grouped
	// (GET /orgs/{org_id}/usage)
	GetUsage(ctx context.Context, request GetUsageRequestObject) (GetUsageResponseObject, error)
	// ExportUsageCSV Export usage as CSV, with the same filters as /usage
	// (GET /orgs/{org_id}/usage.csv)
	ExportUsageCSV(ctx context.Context, request ExportUsageCSVRequestObject) (ExportUsageCSVResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListRequestLogs operation middleware
func (sh *strictHandler) ListRequestLogs(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListRequestLogsParams) {
	var request ListRequestLogsRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRequestLogs(ctx, request.(ListRequestLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRequestLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRequestLogsResponseObject); ok {
		if err := validResponse.VisitListRequestLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportLogsCSV operation middleware
func (sh *strictHandler) ExportLogsCSV(w http.ResponseWriter, r *http.Request, orgId OrgID, params ExportLogsCSVParams) {
	var request ExportLogsCSVRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportLogsCSV(ctx, request.(ExportLogsCSVRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportLogsCSV")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportLogsCSVResponseObject); ok {
		if err := validResponse.VisitExportLogsCSVResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRequestLog operation middleware
func (sh *strictHandler) GetRequestLog(w http.ResponseWriter, r *http.Request, orgId OrgID, requestId string) {
	var request GetRequestLogRequestObject

	request.OrgId = orgId
	request.RequestId = requestId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRequestLog(ctx, request.(GetRequestLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRequestLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRequestLogResponseObject); ok {
		if err := validResponse.VisitGetRequestLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAvailableModels operation middleware
func (sh *strictHandler) ListAvailableModels(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListAvailableModelsParams) {
	var request ListAvailableModelsRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAvailableModels(ctx, request.(ListAvailableModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAvailableModels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAvailableModelsResponseObject); ok {
		if err := validResponse.VisitListAvailableModelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrgProviderKeys operation middleware
func (sh *strictHandler) ListOrgProviderKeys(w http.ResponseWriter, r *http.Request, orgId OrgID, params ListOrgProviderKeysParams) {
	var request ListOrgProviderKeysRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrgProviderKeys(ctx, request.(ListOrgProviderKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrgProviderKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrgProviderKeysResponseObject); ok {
		if err := validResponse.VisitListOrgProviderKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrgProviderKey operation middleware
func (sh *strictHandler) CreateOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID) {
	var request CreateOrgProviderKeyRequestObject

	request.OrgId = orgId

	var body CreateOrgProviderKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrgProviderKey(ctx, request.(CreateOrgProviderKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrgProviderKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrgProviderKeyResponseObject); ok {
		if err := validResponse.VisitCreateOrgProviderKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrgProviderKey operation middleware
func (sh *strictHandler) DeleteOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID, keyId string) {
	var request DeleteOrgProviderKeyRequestObject

	request.OrgId = orgId
	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrgProviderKey(ctx, request.(DeleteOrgProviderKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrgProviderKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrgProviderKeyResponseObject); ok {
		if err := validResponse.VisitDeleteOrgProviderKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestOrgProviderKey operation middleware
func (sh *strictHandler) TestOrgProviderKey(w http.ResponseWriter, r *http.Request, orgId OrgID, keyId string) {
	var request TestOrgProviderKeyRequestObject

	request.OrgId = orgId
	request.KeyId = keyId

	var body TestOrgProviderKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestOrgProviderKey(ctx, request.(TestOrgProviderKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestOrgProviderKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestOrgProviderKeyResponseObject); ok {
		if err := validResponse.VisitTestOrgProviderKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsage operation middleware
func (sh *strictHandler) GetUsage(w http.ResponseWriter, r *http.Request, orgId OrgID, params GetUsageParams) {
	var request GetUsageRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsage(ctx, request.(GetUsageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUsageResponseObject); ok {
		if err := validResponse.VisitGetUsageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportUsageCSV operation middleware
func (sh *strictHandler) ExportUsageCSV(w http.ResponseWriter, r *http.Request, orgId OrgID, params ExportUsageCSVParams) {
	var request ExportUsageCSVRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportUsageCSV(ctx, request.(ExportUsageCSVRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportUsageCSV")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportUsageCSVResponseObject); ok {
		if err := validResponse.VisitExportUsageCSVResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
