package config

import (
	"flag"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"
)

// This file produces testdata/env-surface.txt: the complete set of environment
// variables Load actually asks for. Writing that set down is what makes a
// deployment checkable against the code — a variable renamed here while the
// deployment still injects the old name is otherwise completely silent.
//
// It records rather than parses: MapSource records only the names the loader
// actually asks for, which stays true for any future way of reading. The golden
// file is generated by this test rather than maintained by hand, so it cannot
// drift on its own.
//
// The list is this package's variables only. A build that layers its own
// settings on top records its own list the same way, and its recording covers
// both segments because its loader calls this one — so nothing has to merge two
// lists, and no merge can be forgotten.

var updateGolden = flag.Bool("update-env-surface", false, "rewrite the testdata/env-surface.txt golden file")

// fullEnv is complete enough for LoadRuntime to run all the way through. An
// early validation return would otherwise truncate every later Lookup while
// leaving a deceptively valid-looking golden.
func fullEnv() map[string]string {
	return map[string]string{
		"HTTP_ADDR":                  ":8080",
		"INTERNAL_ADDR":              ":9091",
		"DATABASE_URL":               "postgres://u:p@h:5432/d",
		"REDIS_URL":                  "redis://h:6379",
		"DRIVER_CACHE":               DriverRedis,
		"DRIVER_RATELIMIT":           DriverRedis,
		"DRIVER_BREAKER":             DriverRedis,
		"DRIVER_LOCK":                DriverRedis,
		"TRUST_PROXY":                "true",
		"TRUST_PROXY_HOPS":           "2",
		"RATE_LIMIT_PER_IP_RPM":      "300",
		"AUTH_RATE_LIMIT_PER_IP_RPM": "10",
		"RATE_LIMIT_DISABLED":        "false",
		"DRAIN_GRACE_SECONDS":        "3",
		"SHUTDOWN_TIMEOUT_SECONDS":   "320",
		"SECRET_KEY":                 devSecretKeyHex,
		"DB_POOL_MAX_CONNS":          "10",
	}
}

func TestEnvSurfaceGolden(t *testing.T) {
	seen := map[string]bool{}
	if _, err := LoadRuntime(MapSource{Values: fullEnv(), Seen: seen}, SelfHostedDefaults()); err != nil {
		t.Fatalf("the sample configuration did not get through Load, so the golden file would be short: %v", err)
	}

	names := make([]string, 0, len(seen))
	for k := range seen {
		names = append(names, k)
	}
	sort.Strings(names)
	metadata, err := ExpandedDescriptors(SharedDescriptors)
	if err != nil {
		t.Fatal(err)
	}
	metadataNames := make([]string, len(metadata))
	for i, descriptor := range metadata {
		metadataNames[i] = descriptor.Name
	}
	if !slices.Equal(names, metadataNames) {
		t.Fatalf("actual reads and metadata differ\nreads: %s\nmetadata: %s", strings.Join(names, ", "), strings.Join(metadataNames, ", "))
	}

	// Positive controls. Each of these represents one way of reading a
	// variable, and a missing one means the recording did not work: one is read
	// through a helper rather than directly, one is read only inside an
	// "if it is set" branch, and one is the very first read.
	//
	// The fourth shape the hand-written regular expressions missed — a name
	// containing digits — has no example left in this package, so its positive
	// control lives in the loader that layers on top of this one. Saying that
	// here rather than dropping the note quietly: a control this file cannot
	// run is a control somebody else has to.
	for _, must := range []string{"DRAIN_GRACE_SECONDS", "DB_POOL_MAX_CONNS", "DATABASE_URL_FILE"} {
		if !seen[must] {
			t.Fatalf("the recording getenv never saw %s: the instrument is broken and the golden file cannot be trusted", must)
		}
	}
	if len(names) < 16 {
		t.Fatalf("only %d variables were recorded, below the floor of 16: Load almost certainly returned early", len(names))
	}

	golden := filepath.Join("testdata", "env-surface.txt")
	body := header + strings.Join(names, "\n") + "\n"
	if *updateGolden {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("rewrote %s (%d variables)", golden, len(names))
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("could not read the golden file (generate it with: go test ./foundation/config -run EnvSurface -update-env-surface): %v", err)
	}
	if string(want) != body {
		t.Errorf("the set of variables config.Load reads differs from the golden file. "+
			"If that is intended, run:\n"+
			"  go test ./foundation/config -run EnvSurface -update-env-surface\n"+
			"and update the deployment configuration to match.\n"+
			"Currently %d:\n%s", len(names), strings.Join(names, "\n"))
	}
}

const header = `# Generated by foundation/config/surface_test.go. Do not edit by hand.
# Regenerate: go test ./foundation/config -run EnvSurface -update-env-surface
#
# Every environment variable this build reads, recorded by actually running the
# loader. When you change how the service is configured, this is the list that
# tells you what you missed.
`
