// Command configdoc generates the Community configuration reference from the
// same descriptors whose names are checked against the runtime loader.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fairlb/fairlb/foundation/config"
	community "github.com/fairlb/fairlb/internal/community/config"
)

func main() {
	check := flag.Bool("check", false, "fail when docs/configuration.md is stale")
	flag.Parse()
	descriptors, err := config.ExpandedDescriptors(config.SharedDescriptors, community.Descriptors)
	if err != nil {
		fatal(err)
	}
	body := render(descriptors)
	path := filepath.Join("docs", "configuration.md")
	if *check {
		current, err := os.ReadFile(path)
		if err != nil {
			fatal(err)
		}
		if !bytes.Equal(current, body) {
			fatal(fmt.Errorf("%s is stale; run go run ./tools/configdoc", path))
		}
		return
	}
	if err := os.WriteFile(path, body, 0o644); err != nil {
		fatal(err)
	}
}

func render(descriptors []config.Descriptor) []byte {
	var out strings.Builder
	out.WriteString("<!-- Generated by tools/configdoc from typed configuration metadata. Do not edit. -->\n\n" +
		"# Configuration\n\n" +
		"FairLB Community uses environment variables. `DATABASE_URL` is the only required\n" +
		"value in the shipped Compose deployment; the remaining defaults suit one instance.\n" +
		"Every secret accepts a mutually exclusive `<NAME>_FILE` alternative. Blank values\n" +
		"use the built-in default, matching the shipped Compose file.\n\n" +
		"Run `fairlb config check` to validate without connecting to external services and\n" +
		"to print redacted effective values, their source, and optional-feature state.\n\n" +
		"| Variable | Type | Default | Required when | Description |\n" +
		"|---|---|---|---|---|\n")
	for _, d := range descriptors {
		def := d.Default
		if d.CommunityDefault != "" {
			def = d.CommunityDefault
		}
		if def == "" {
			def = "—"
		}
		required := d.Required
		if required == "" {
			required = "—"
		}
		typeName := d.Type
		if d.Secret && d.Type != "file" {
			typeName = "secret " + typeName
		}
		fmt.Fprintf(&out, "| `%s` | %s | `%s` | %s | %s |\n",
			d.Name, typeName, escape(def), escape(required), escape(d.Description))
	}
	out.WriteString("\nOpenTelemetry exporter variables are consumed by the OTel adapter directly and\n" +
		"retain the standard names defined by the OpenTelemetry SDK.\n")
	return []byte(out.String())
}

func escape(value string) string { return strings.ReplaceAll(value, "|", "\\|") }

func fatal(err error) {
	_, _ = fmt.Fprintln(os.Stderr, "configdoc:", err)
	os.Exit(1)
}
