// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: affinity.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredResourceAffinities = `-- name: DeleteExpiredResourceAffinities :execrows
DELETE FROM resource_affinities WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredResourceAffinities(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredResourceAffinities)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResourceAffinity = `-- name: DeleteResourceAffinity :exec
DELETE FROM resource_affinities
 WHERE org_id = $1 AND protocol = $2 AND resource_type = $3 AND upstream_id = $4
`

type DeleteResourceAffinityParams struct {
	OrgID        pgtype.UUID
	Protocol     string
	ResourceType string
	UpstreamID   string
}

func (q *Queries) DeleteResourceAffinity(ctx context.Context, arg DeleteResourceAffinityParams) error {
	_, err := q.db.Exec(ctx, deleteResourceAffinity,
		arg.OrgID,
		arg.Protocol,
		arg.ResourceType,
		arg.UpstreamID,
	)
	return err
}

const getActiveOrgProviderKeyByID = `-- name: GetActiveOrgProviderKeyByID :one
SELECT id, org_id, vendor, base_url, secret_enc, allow_fallback
  FROM org_provider_keys
 WHERE id = $1 AND org_id = $2 AND status = 'active'
`

type GetActiveOrgProviderKeyByIDParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

type GetActiveOrgProviderKeyByIDRow struct {
	ID            pgtype.UUID
	OrgID         pgtype.UUID
	Vendor        string
	BaseUrl       pgtype.Text
	SecretEnc     []byte
	AllowFallback bool
}

func (q *Queries) GetActiveOrgProviderKeyByID(ctx context.Context, arg GetActiveOrgProviderKeyByIDParams) (GetActiveOrgProviderKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrgProviderKeyByID, arg.ID, arg.OrgID)
	var i GetActiveOrgProviderKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Vendor,
		&i.BaseUrl,
		&i.SecretEnc,
		&i.AllowFallback,
	)
	return i, err
}

const getProviderKeyByID = `-- name: GetProviderKeyByID :one
SELECT id, provider_id, name, secret_enc
  FROM provider_keys
 WHERE id = $1 AND status = 'active'
`

type GetProviderKeyByIDRow struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
	Name       string
	SecretEnc  []byte
}

func (q *Queries) GetProviderKeyByID(ctx context.Context, id pgtype.UUID) (GetProviderKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderKeyByID, id)
	var i GetProviderKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.SecretEnc,
	)
	return i, err
}

const getResourceAffinity = `-- name: GetResourceAffinity :one
SELECT a.org_id, a.protocol, a.resource_type, a.upstream_id, a.model_id, a.route_id, a.provider_id, a.provider_key_id, a.org_provider_key_id, a.expires_at, a.created_at, a.updated_at, m.slug AS model_slug
  FROM resource_affinities a
  JOIN models m ON m.id = a.model_id
 WHERE a.org_id = $1
   AND a.protocol = $2
   AND a.resource_type = $3
   AND a.upstream_id = $4
   AND a.expires_at > now()
`

type GetResourceAffinityParams struct {
	OrgID        pgtype.UUID
	Protocol     string
	ResourceType string
	UpstreamID   string
}

type GetResourceAffinityRow struct {
	OrgID            pgtype.UUID
	Protocol         string
	ResourceType     string
	UpstreamID       string
	ModelID          pgtype.UUID
	RouteID          pgtype.UUID
	ProviderID       pgtype.UUID
	ProviderKeyID    pgtype.UUID
	OrgProviderKeyID pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ModelSlug        string
}

func (q *Queries) GetResourceAffinity(ctx context.Context, arg GetResourceAffinityParams) (GetResourceAffinityRow, error) {
	row := q.db.QueryRow(ctx, getResourceAffinity,
		arg.OrgID,
		arg.Protocol,
		arg.ResourceType,
		arg.UpstreamID,
	)
	var i GetResourceAffinityRow
	err := row.Scan(
		&i.OrgID,
		&i.Protocol,
		&i.ResourceType,
		&i.UpstreamID,
		&i.ModelID,
		&i.RouteID,
		&i.ProviderID,
		&i.ProviderKeyID,
		&i.OrgProviderKeyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelSlug,
	)
	return i, err
}

const upsertResourceAffinity = `-- name: UpsertResourceAffinity :exec
INSERT INTO resource_affinities (
    org_id, protocol, resource_type, upstream_id, model_id, route_id,
    provider_id, provider_key_id, org_provider_key_id, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $9,
          $10, $8)
ON CONFLICT (org_id, protocol, resource_type, upstream_id) DO UPDATE SET
    model_id = excluded.model_id,
    route_id = excluded.route_id,
    provider_id = excluded.provider_id,
    provider_key_id = excluded.provider_key_id,
    org_provider_key_id = excluded.org_provider_key_id,
    expires_at = excluded.expires_at,
    updated_at = now()
`

type UpsertResourceAffinityParams struct {
	OrgID            pgtype.UUID
	Protocol         string
	ResourceType     string
	UpstreamID       string
	ModelID          pgtype.UUID
	RouteID          pgtype.UUID
	ProviderID       pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	ProviderKeyID    pgtype.UUID
	OrgProviderKeyID pgtype.UUID
}

func (q *Queries) UpsertResourceAffinity(ctx context.Context, arg UpsertResourceAffinityParams) error {
	_, err := q.db.Exec(ctx, upsertResourceAffinity,
		arg.OrgID,
		arg.Protocol,
		arg.ResourceType,
		arg.UpstreamID,
		arg.ModelID,
		arg.RouteID,
		arg.ProviderID,
		arg.ExpiresAt,
		arg.ProviderKeyID,
		arg.OrgProviderKeyID,
	)
	return err
}
