// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: byok.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrgProviderKey = `-- name: CreateOrgProviderKey :one
INSERT INTO org_provider_keys (org_id, vendor, name, base_url, secret_enc, secret_hint, allow_fallback)
VALUES ($1, $2, $3, $5, '\x00'::bytea, $4, $6)
RETURNING id, org_id, vendor, name, base_url, status,
          secret_hint, allow_fallback, last_verified_at, created_at
`

type CreateOrgProviderKeyParams struct {
	OrgID         pgtype.UUID
	Vendor        string
	Name          string
	SecretHint    string
	BaseUrl       pgtype.Text
	AllowFallback bool
}

type CreateOrgProviderKeyRow struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	Vendor         string
	Name           string
	BaseUrl        pgtype.Text
	Status         string
	SecretHint     string
	AllowFallback  bool
	LastVerifiedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

// secret_enc is inserted as a placeholder and back-filled once the row id is
// known, because the id is used as the AEAD associated data. The two steps are
// deliberate: binding the AAD to the row id makes the ciphertext unusable if it
// is copied into another row.
func (q *Queries) CreateOrgProviderKey(ctx context.Context, arg CreateOrgProviderKeyParams) (CreateOrgProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, createOrgProviderKey,
		arg.OrgID,
		arg.Vendor,
		arg.Name,
		arg.SecretHint,
		arg.BaseUrl,
		arg.AllowFallback,
	)
	var i CreateOrgProviderKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Vendor,
		&i.Name,
		&i.BaseUrl,
		&i.Status,
		&i.SecretHint,
		&i.AllowFallback,
		&i.LastVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const defaultUpstreamForVendor = `-- name: DefaultUpstreamForVendor :one
SELECT base_url, transport, protocols FROM providers
WHERE vendor = $1::text AND enabled
ORDER BY slug
LIMIT 1
`

type DefaultUpstreamForVendorRow struct {
	BaseUrl   string
	Transport []byte
	Protocols []string
}

// Resolve the default endpoint for a vendor when a BYOK row leaves base_url
// empty (empty means "use the deployment's default endpoint for this vendor").
// Picks the enabled provider with the lowest slug so the result is
// deterministic; if there is none the row comes back empty and the caller asks
// the organization to fill in base_url explicitly -- guessing an endpoint is worse
// than an error.
// Membership is by vendor rather than by protocol, because the endpoint has to be
// one this credential is actually valid at: every provider speaking a protocol
// was the old criterion, and it would hand a organization's key the address of a
// different company that happens to speak the same protocol.
// base_url and transport come back together, from one row, because they are one
// answer: the address of an upstream is the endpoint plus the profile that says
// how to address it. Fetching them separately would let a connectivity test
// reach one provider's endpoint carrying another provider's path override --
// and the profile is now certainly the right one, since it belongs to the same
// platform the credential does.
func (q *Queries) DefaultUpstreamForVendor(ctx context.Context, vendor string) (DefaultUpstreamForVendorRow, error) {
	row := q.db.QueryRow(ctx, defaultUpstreamForVendor, vendor)
	var i DefaultUpstreamForVendorRow
	err := row.Scan(&i.BaseUrl, &i.Transport, &i.Protocols)
	return i, err
}

const deleteOrgProviderKey = `-- name: DeleteOrgProviderKey :execrows
DELETE FROM org_provider_keys WHERE id = $1 AND org_id = $2
`

type DeleteOrgProviderKeyParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) DeleteOrgProviderKey(ctx context.Context, arg DeleteOrgProviderKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgProviderKey, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgProviderKeySecret = `-- name: GetOrgProviderKeySecret :one
SELECT id, org_id, vendor, base_url, secret_enc, status
FROM org_provider_keys
WHERE id = $1 AND org_id = $2
`

type GetOrgProviderKeySecretParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

type GetOrgProviderKeySecretRow struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	Vendor    string
	BaseUrl   pgtype.Text
	SecretEnc []byte
	Status    string
}

// Fetch the ciphertext for decryption (connectivity test and dataplane
// routing). The org predicate means a caller holding someone else's key id
// still reads nothing.
func (q *Queries) GetOrgProviderKeySecret(ctx context.Context, arg GetOrgProviderKeySecretParams) (GetOrgProviderKeySecretRow, error) {
	row := q.db.QueryRow(ctx, getOrgProviderKeySecret, arg.ID, arg.OrgID)
	var i GetOrgProviderKeySecretRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Vendor,
		&i.BaseUrl,
		&i.SecretEnc,
		&i.Status,
	)
	return i, err
}

const listActiveBYOKForOrg = `-- name: ListActiveBYOKForOrg :many
SELECT id, vendor, base_url, secret_enc, allow_fallback
FROM org_provider_keys
WHERE org_id = $1 AND status = 'active'
ORDER BY vendor, created_at
`

type ListActiveBYOKForOrgRow struct {
	ID            pgtype.UUID
	Vendor        string
	BaseUrl       pgtype.Text
	SecretEnc     []byte
	AllowFallback bool
}

// Every usable BYOK credential an org holds (dataplane hot path).
//
// All of them in one query rather than one query per vendor: a model's
// candidates can span several platforms, and the credential that applies is
// decided per candidate. Asking per candidate would put a database round trip
// inside the rotation loop; asking once per request and choosing in memory keeps
// it at one.
//
// Deliberately not inside an org-scoped transaction: here the org comes from an
// authenticated API key rather than user-controlled input, so the explicit
// predicate is the whole requirement, and the hot path should not open an extra
// transaction per request.
// Only active rows: invalid (upstream rejected it) and disabled (the organization
// turned it off) both stay out of routing.
// With several credentials for one vendor the oldest wins -- stability is all
// that is needed, and there is no rotation here. Rotation is a property of a
// shared credential pool; a organization's own quota does not need us spreading load
// across their keys. The ordering is what makes "the oldest" well defined for
// the caller collapsing this list per vendor.
func (q *Queries) ListActiveBYOKForOrg(ctx context.Context, orgID pgtype.UUID) ([]ListActiveBYOKForOrgRow, error) {
	rows, err := q.db.Query(ctx, listActiveBYOKForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveBYOKForOrgRow
	for rows.Next() {
		var i ListActiveBYOKForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Vendor,
			&i.BaseUrl,
			&i.SecretEnc,
			&i.AllowFallback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBYOKVendors = `-- name: ListBYOKVendors :many
SELECT DISTINCT vendor FROM providers
WHERE enabled AND vendor <> 'custom'
ORDER BY vendor
`

// The vendors this deployment actually routes to, which is the set a organization may
// usefully supply a credential for.
//
// A key for a vendor with no enabled provider can never apply to anything: there
// is no candidate for it to serve, so it would sit in the organization's list looking
// configured and never take effect. Refusing it at the point of entry is the
// only place that difference is visible.
//
// The custom vendor is excluded: it means "an upstream this build has no entry
// for", which is not an identity a organization can hold an account with.
func (q *Queries) ListBYOKVendors(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listBYOKVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var vendor string
		if err := rows.Scan(&vendor); err != nil {
			return nil, err
		}
		items = append(items, vendor)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgProviderKeys = `-- name: ListOrgProviderKeys :many

SELECT id, org_id, vendor, name, base_url, status,
       secret_hint, allow_fallback, last_verified_at, created_at
FROM org_provider_keys
WHERE org_id = $1
  AND (NOT $2::boolean
       OR (vendor, name) > ($3::text, $4::text))
ORDER BY vendor, name
LIMIT $5
`

type ListOrgProviderKeysParams struct {
	OrgID        pgtype.UUID
	HasCursor    bool
	CursorVendor string
	CursorName   string
	Lim          int32
}

type ListOrgProviderKeysRow struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	Vendor         string
	Name           string
	BaseUrl        pgtype.Text
	Status         string
	SecretHint     string
	AllowFallback  bool
	LastVerifiedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

// Organization-supplied upstream credentials (BYOK).
//
// Every query here carries an explicit org predicate. These are called from the
// console, where the org comes from a URL parameter -- user-controlled input --
// so they must run inside an org-scoped transaction: row-level security is the
// third line of defence, the explicit predicate is the second, and both are
// required. See docs/design/upstream-credentials.md.
// Deliberately does not return secret_enc: once ciphertext leaves the crypto
// boundary it can be carried off by logs, serialisation or error messages.
//
// Ordered by (vendor, name) rather than by time, and paginated on that same
// key. This is a configuration screen, not a feed: an organization holding
// azure-eu, azure-us and two OpenAI accounts reads it by platform, and ordering
// it newest-first to suit a created_at cursor would rearrange the page to serve
// the pagination rather than the reader.
//
// No id tiebreaker, and that is a property of the schema rather than an
// omission: `UNIQUE (org_id, name)` makes name alone unique within an
// organization, so (vendor, name) is already a total order.
func (q *Queries) ListOrgProviderKeys(ctx context.Context, arg ListOrgProviderKeysParams) ([]ListOrgProviderKeysRow, error) {
	rows, err := q.db.Query(ctx, listOrgProviderKeys,
		arg.OrgID,
		arg.HasCursor,
		arg.CursorVendor,
		arg.CursorName,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgProviderKeysRow
	for rows.Next() {
		var i ListOrgProviderKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Vendor,
			&i.Name,
			&i.BaseUrl,
			&i.Status,
			&i.SecretHint,
			&i.AllowFallback,
			&i.LastVerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgProviderKeySecret = `-- name: SetOrgProviderKeySecret :exec
UPDATE org_provider_keys SET secret_enc = $2 WHERE id = $1 AND org_id = $3
`

type SetOrgProviderKeySecretParams struct {
	ID        pgtype.UUID
	SecretEnc []byte
	OrgID     pgtype.UUID
}

func (q *Queries) SetOrgProviderKeySecret(ctx context.Context, arg SetOrgProviderKeySecretParams) error {
	_, err := q.db.Exec(ctx, setOrgProviderKeySecret, arg.ID, arg.SecretEnc, arg.OrgID)
	return err
}

const setOrgProviderKeyStatus = `-- name: SetOrgProviderKeyStatus :exec
UPDATE org_provider_keys
SET status = $3,
    last_verified_at = CASE WHEN $3 = 'active' THEN now() ELSE last_verified_at END
WHERE id = $1 AND org_id = $2
`

type SetOrgProviderKeyStatusParams struct {
	ID     pgtype.UUID
	OrgID  pgtype.UUID
	Status string
}

// Shared by the connectivity test and the dataplane: a successful verification
// sets status to active and stamps the time, a 401/403 from upstream sets it to
// invalid.
func (q *Queries) SetOrgProviderKeyStatus(ctx context.Context, arg SetOrgProviderKeyStatusParams) error {
	_, err := q.db.Exec(ctx, setOrgProviderKeyStatus, arg.ID, arg.OrgID, arg.Status)
	return err
}
