// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const catalogSwitchCounts = `-- name: CatalogSwitchCounts :one
SELECT (SELECT count(*) FROM providers)::bigint                     AS providers_total,
       (SELECT count(*) FROM providers WHERE NOT enabled)::bigint   AS providers_disabled,
       (SELECT count(*) FROM models)::bigint                        AS models_total,
       (SELECT count(*) FROM models WHERE NOT enabled)::bigint      AS models_disabled
`

type CatalogSwitchCountsRow struct {
	ProvidersTotal    int64
	ProvidersDisabled int64
	ModelsTotal       int64
	ModelsDisabled    int64
}

// Counts for the provider- and model-level kill switches shown on the health
// page.
// The frontend must not derive these by counting the catalog lists: those lists
// are capped (200 and 500 above), so counting them yields "how many are disabled
// on the first page" while the card claims "N total, M disabled". The day a cap
// actually bites, both numbers go silently wrong with no signal at all. A count
// and the thing it counts have to come from the same place.
func (q *Queries) CatalogSwitchCounts(ctx context.Context) (CatalogSwitchCountsRow, error) {
	row := q.db.QueryRow(ctx, catalogSwitchCounts)
	var i CatalogSwitchCountsRow
	err := row.Scan(
		&i.ProvidersTotal,
		&i.ProvidersDisabled,
		&i.ModelsTotal,
		&i.ModelsDisabled,
	)
	return i, err
}

const classifyUpstreamModels = `-- name: ClassifyUpstreamModels :many

WITH ids AS (SELECT DISTINCT unnest($3::text[])::text AS upstream_id)
SELECT i.upstream_id::text                AS upstream_id,
       m.id                               AS model_id,
       COALESCE(m.slug, '')::text         AS model_slug,
       -- The "is it priced" criterion reads model_pricing, word for word the
       -- same as the readiness check in the admin write path.
       --
       -- It used to read a free flag and four price columns on models. Those
       -- five columns had long been dead, and price now lives in exactly one
       -- place. The general lesson: a value has as many places to be read wrong
       -- as it has places to be stored. Collapsing it to one place removes the
       -- habitat for this class of defect, instead of relying on every reader
       -- remembering which copy is the real one.
       --
       -- The criterion itself: the row says free explicitly, or all four token
       -- buckets are present and not all zero. "All present" rather than "any
       -- non-zero" -- partial NULLs mean incomplete data, not a cheap price.
       -- (A CHECK constraint says the same thing on the write side; this is the
       -- read side of one sentence.)
       --
       -- No COALESCE wrapper: EXISTS is never NULL, and when the LATERAL misses
       -- (m.id IS NULL) ` + "`" + `mp.model_id = m.id` + "`" + ` is never true, so it is plainly
       -- false. The Go side checks for a missing model id first and reports
       -- "unknown", so the four-state precedence is unaffected.
       EXISTS (
           SELECT 1 FROM model_pricing mp
           WHERE mp.model_id = m.id
             AND (mp.billing_mode = 'free'
                  OR (mp.upstream_in_nano_per_mtok IS NOT NULL
                      AND mp.upstream_out_nano_per_mtok IS NOT NULL
                      AND mp.upstream_cache_read_nano_per_mtok IS NOT NULL
                      AND mp.upstream_cache_write_nano_per_mtok IS NOT NULL
                      AND (mp.upstream_in_nano_per_mtok <> 0
                           OR mp.upstream_out_nano_per_mtok <> 0
                           OR mp.upstream_cache_read_nano_per_mtok <> 0
                           OR mp.upstream_cache_write_nano_per_mtok <> 0)))
       )::boolean AS priced,
       EXISTS (
           SELECT 1 FROM model_routes r
           WHERE r.provider_id = $1
             AND r.provider_model_id = i.upstream_id
       )::boolean AS routed
FROM ids i
LEFT JOIN LATERAL (
    -- Only the two columns the decision needs. Narrowing is not about bytes:
    -- ` + "`" + `mm.*` + "`" + ` would drag every column on models into scope, and the next person
    -- writing a criterion against one of them would meet no resistance at all.
    -- That is exactly how the defect described above grew.
    SELECT mm.id, mm.slug FROM models mm
    -- No protocol predicate: a model owns none, and any provider can carry any
    -- model on the protocols it speaks.
    --
    -- The equality arm only ever fires for an upstream that reports two-part
    -- names of its own -- an aggregator saying "openai/gpt-5.4" -- because a
    -- slug is two segments and a plain upstream name is one. The suffix arm is
    -- what matches the ordinary case.
    WHERE mm.slug = i.upstream_id OR mm.slug LIKE '%/' || i.upstream_id
    -- Exact first, then the model whose creator segment is the one this
    -- provider's vendor publishes as a first party.
    --
    -- Without that middle term two catalog entries ending in the same name are
    -- separated by alphabetical order, which is not a reason -- it is the
    -- absence of one. The argument is the vendor's *creator*, not its own slug:
    -- the two differ often enough (xAI publishes "x-ai", Alibaba publishes
    -- "qwen") that using the slug would rank by a name no slug contains. It is
    -- empty for a vendor that creates nothing -- a platform or an aggregator --
    -- and an empty creator matches no slug, so the term drops out rather than
    -- ranking anything by accident.
    ORDER BY (mm.slug = i.upstream_id) DESC,
             (split_part(mm.slug, '/', 1) = $2::text) DESC,
             mm.slug
    LIMIT 1
) m ON true
ORDER BY i.upstream_id
`

type ClassifyUpstreamModelsParams struct {
	ProviderID  pgtype.UUID
	Creator     string
	UpstreamIds []string
}

type ClassifyUpstreamModelsRow struct {
	UpstreamID string
	ModelID    pgtype.UUID
	ModelSlug  string
	Priced     bool
	Routed     bool
}

// ===== Upstream model discovery =====
// Classify the model ids an upstream reports, so the admin page can show the
// four-state diff view.
//
// Matching is a heuristic suggestion, never an authoritative verdict. Upstream
// reports its own model name (`gpt-4o`); identity here is a slug
// (`openai/gpt-4o`), and there is no reliable mechanical correspondence between
// the two. So the criterion is fixed at "the slug either equals the upstream
// name or ends in /<upstream name>", and a hit is only a candidate
// -- a route is created after a human confirms it.
//
// LATERAL with LIMIT 1 rather than a plain LEFT JOIN: one upstream name can
// match several local slugs (`openai/gpt-4o` and `vendorx/gpt-4o`), and a plain
// join would turn one upstream model into several rows, which reads in the UI
// as upstream reporting duplicates. The ordering makes an exact match win.
// Both explicit type annotations are required: sqlc cannot infer the type of
// the unnest inside the CTE, nor the nullability of the LEFT JOINed columns.
// The former would generate interface{}, and the latter would generate the
// nullable slug as a non-nullable string, which panics on scan.
func (q *Queries) ClassifyUpstreamModels(ctx context.Context, arg ClassifyUpstreamModelsParams) ([]ClassifyUpstreamModelsRow, error) {
	rows, err := q.db.Query(ctx, classifyUpstreamModels, arg.ProviderID, arg.Creator, arg.UpstreamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassifyUpstreamModelsRow
	for rows.Next() {
		var i ClassifyUpstreamModelsRow
		if err := rows.Scan(
			&i.UpstreamID,
			&i.ModelID,
			&i.ModelSlug,
			&i.Priced,
			&i.Routed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearRouteProbeOverride = `-- name: ClearRouteProbeOverride :exec
UPDATE model_route_probes
SET status = 'unverified', source = 'probe', checked_at = NULL, latency_ms = NULL,
    status_code = NULL, error = '', probe_enqueued_at = NULL, updated_at = now()
WHERE route_id = $1 AND endpoint = $2
`

type ClearRouteProbeOverrideParams struct {
	RouteID  pgtype.UUID
	Endpoint string
}

// Clearing the override hands the row back to the worker, unverified, so the
// next probe decides.
func (q *Queries) ClearRouteProbeOverride(ctx context.Context, arg ClearRouteProbeOverrideParams) error {
	_, err := q.db.Exec(ctx, clearRouteProbeOverride, arg.RouteID, arg.Endpoint)
	return err
}

const clearRouteProbesEnqueued = `-- name: ClearRouteProbesEnqueued :exec
UPDATE model_route_probes SET probe_enqueued_at = NULL, updated_at = now()
 WHERE route_id = $1 AND probe_enqueued_at IS NOT NULL
`

// The worker's own cleanup, run however its pass ends. Verdicts clear their own
// row as they land, which is what makes each badge stop one at a time; this
// catches what is left -- an operator's row the upsert refused to touch, an
// endpoint skipped because the provider has no credential yet, a route deleted
// under the job.
func (q *Queries) ClearRouteProbesEnqueued(ctx context.Context, routeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRouteProbesEnqueued, routeID)
	return err
}

const countActiveProviderKeys = `-- name: CountActiveProviderKeys :one
SELECT count(*)::bigint FROM provider_keys WHERE provider_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveProviderKeys(ctx context.Context, providerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProviderKeys, providerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countVerifiedProviderKeys = `-- name: CountVerifiedProviderKeys :one
SELECT count(*)::bigint
FROM provider_keys k
WHERE k.provider_id = $1
  AND k.last_verified_at IS NOT NULL
  AND k.last_error = ''
`

// How many of this upstream's credentials have ever verified, over the whole set
// rather than over a page.
//
// The readiness checklist asks "has any credential been verified", and it used to
// answer by scanning the list it had already fetched. Once that list paginates,
// a verified key sitting on a later page reads as "none verified" — a checklist
// step shown incomplete while the thing it checks is done. A count from the
// database cannot be wrong that way.
func (q *Queries) CountVerifiedProviderKeys(ctx context.Context, providerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedProviderKeys, providerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO models (
    slug, display_name, enabled, visibility,
    context_window, max_output_tokens, output_modalities
) VALUES ($1, $2, $3, $4, $5, $6,
          -- Unset means text, the column's own default. Passing the argument
          -- through raw would send NULL for every caller that says nothing and
          -- fail the NOT NULL -- which is most of them, since only an image or
          -- video model has anything to say here.
          --
          -- nullif before the coalesce, because a caller can send ` + "`" + `[]` + "`" + ` and the
          -- driver encodes a non-nil empty slice as ` + "`" + `{}` + "`" + ` rather than as NULL:
          -- without it that array reaches the column and fails the cardinality
          -- CHECK, so "I said nothing about modalities" answers with a
          -- constraint violation instead of with the default.
          COALESCE(
              nullif($7::text[], '{}'::text[]),
              ARRAY['text']::text[]
          ))
RETURNING id, slug, display_name, enabled, visibility, output_modalities
`

type CreateModelParams struct {
	Slug             string
	DisplayName      string
	Enabled          bool
	Visibility       string
	ContextWindow    int32
	MaxOutputTokens  int32
	OutputModalities []string
}

type CreateModelRow struct {
	ID               pgtype.UUID
	Slug             string
	DisplayName      string
	Enabled          bool
	Visibility       string
	OutputModalities []string
}

// Pricing does not live in this table: the model_pricing row is the price.
// When a model is created with a price, the price goes through
// `PUT /gateway/models/{id}/pricing` as a second call.
func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (CreateModelRow, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.Slug,
		arg.DisplayName,
		arg.Enabled,
		arg.Visibility,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.OutputModalities,
	)
	var i CreateModelRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Enabled,
		&i.Visibility,
		&i.OutputModalities,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (slug, vendor, protocols, base_url, name, headers, transport,
                       cost_multiplier_bps, rate_limit_rpm, rate_limit_tpm, max_concurrency)
VALUES ($1, $2,
        (SELECT array_agg(DISTINCT f ORDER BY f) FROM unnest($3::text[]) AS f),
        $4, $5,
        COALESCE($6, '{}'::jsonb),
        COALESCE($7, '{}'::jsonb),
        COALESCE($8, 10000),
        $9, $10,
        COALESCE($11, 64))
RETURNING id, slug, vendor, protocols, name, base_url, enabled, auto_disabled, headers, transport,
          cost_multiplier_bps, rate_limit_rpm, rate_limit_tpm, max_concurrency
`

type CreateProviderParams struct {
	Slug              string
	Vendor            string
	Protocols         []string
	BaseUrl           string
	Name              string
	Headers           interface{}
	Transport         interface{}
	CostMultiplierBps interface{}
	RateLimitRpm      pgtype.Int4
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    interface{}
}

type CreateProviderRow struct {
	ID                pgtype.UUID
	Slug              string
	Vendor            string
	Protocols         []string
	Name              string
	BaseUrl           string
	Enabled           bool
	AutoDisabled      bool
	Headers           []byte
	Transport         []byte
	CostMultiplierBps int32
	RateLimitRpm      pgtype.Int4
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    int32
}

// protocols is normalised on write (sorted and deduplicated) so the stored form
// is canonical and comparison and display do not shift with the order the
// operator happened to tick the boxes in. A CHECK constraint cannot do this
// (subqueries are not allowed in CHECK), so both write paths array_agg it
// themselves.
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (CreateProviderRow, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Slug,
		arg.Vendor,
		arg.Protocols,
		arg.BaseUrl,
		arg.Name,
		arg.Headers,
		arg.Transport,
		arg.CostMultiplierBps,
		arg.RateLimitRpm,
		arg.RateLimitTpm,
		arg.MaxConcurrency,
	)
	var i CreateProviderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vendor,
		&i.Protocols,
		&i.Name,
		&i.BaseUrl,
		&i.Enabled,
		&i.AutoDisabled,
		&i.Headers,
		&i.Transport,
		&i.CostMultiplierBps,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.MaxConcurrency,
	)
	return i, err
}

const createProviderKey = `-- name: CreateProviderKey :one
INSERT INTO provider_keys (provider_id, name, secret_enc, secret_hint)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, name, status, secret_hint, last_verified_at, last_error
`

type CreateProviderKeyParams struct {
	ProviderID pgtype.UUID
	Name       string
	SecretEnc  []byte
	SecretHint string
}

type CreateProviderKeyRow struct {
	ID             pgtype.UUID
	ProviderID     pgtype.UUID
	Name           string
	Status         string
	SecretHint     string
	LastVerifiedAt pgtype.Timestamptz
	LastError      string
}

func (q *Queries) CreateProviderKey(ctx context.Context, arg CreateProviderKeyParams) (CreateProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, createProviderKey,
		arg.ProviderID,
		arg.Name,
		arg.SecretEnc,
		arg.SecretHint,
	)
	var i CreateProviderKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Status,
		&i.SecretHint,
		&i.LastVerifiedAt,
		&i.LastError,
	)
	return i, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO model_routes (
    model_id, provider_id, provider_model_id, priority, weight, enabled, headers,
    context_window, max_output_tokens, quirks, video_envelope, max_images
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, model_id, provider_id, provider_model_id, priority, weight, enabled, headers,
          context_window, max_output_tokens, quirks, video_envelope, max_images
`

type CreateRouteParams struct {
	ModelID         pgtype.UUID
	ProviderID      pgtype.UUID
	ProviderModelID string
	Priority        int32
	Weight          int32
	Enabled         bool
	Headers         []byte
	ContextWindow   pgtype.Int4
	MaxOutputTokens pgtype.Int4
	Quirks          []byte
	VideoEnvelope   []byte
	MaxImages       pgtype.Int4
}

type CreateRouteRow struct {
	ID              pgtype.UUID
	ModelID         pgtype.UUID
	ProviderID      pgtype.UUID
	ProviderModelID string
	Priority        int32
	Weight          int32
	Enabled         bool
	Headers         []byte
	ContextWindow   pgtype.Int4
	MaxOutputTokens pgtype.Int4
	Quirks          []byte
	VideoEnvelope   []byte
	MaxImages       pgtype.Int4
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (CreateRouteRow, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.ModelID,
		arg.ProviderID,
		arg.ProviderModelID,
		arg.Priority,
		arg.Weight,
		arg.Enabled,
		arg.Headers,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Quirks,
		arg.VideoEnvelope,
		arg.MaxImages,
	)
	var i CreateRouteRow
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.ProviderID,
		&i.ProviderModelID,
		&i.Priority,
		&i.Weight,
		&i.Enabled,
		&i.Headers,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Quirks,
		&i.VideoEnvelope,
		&i.MaxImages,
	)
	return i, err
}

const deleteCooldown = `-- name: DeleteCooldown :exec
DELETE FROM cooldowns WHERE scope = $1 AND ref_id = $2
`

type DeleteCooldownParams struct {
	Scope string
	RefID pgtype.UUID
}

func (q *Queries) DeleteCooldown(ctx context.Context, arg DeleteCooldownParams) error {
	_, err := q.db.Exec(ctx, deleteCooldown, arg.Scope, arg.RefID)
	return err
}

const deleteProviderDiscovery = `-- name: DeleteProviderDiscovery :exec
DELETE FROM provider_discoveries WHERE provider_id = $1
`

// Forget the snapshot when the provider stops being the same upstream.
//
// A base URL or vendor change points the record at a different service, and the
// stored catalogue then describes something nobody is talking to any more --
// which is worse than having no snapshot, because it still reads as an answer.
// The same judgement the probe rows make when an upstream model name changes.
func (q *Queries) DeleteProviderDiscovery(ctx context.Context, providerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderDiscovery, providerID)
	return err
}

const deleteProviderKey = `-- name: DeleteProviderKey :execrows
DELETE FROM provider_keys WHERE id = $1 AND provider_id = $2
`

type DeleteProviderKeyParams struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
}

// Carries a provider_id predicate to prevent cross-provider deletion: a
// tampered path parameter fails silently rather than deleting another
// provider's key.
func (q *Queries) DeleteProviderKey(ctx context.Context, arg DeleteProviderKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderKey, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM model_routes WHERE id = $1 AND model_id = $2
`

type DeleteRouteParams struct {
	ID      pgtype.UUID
	ModelID pgtype.UUID
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, arg.ID, arg.ModelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRouteProbesOutsideProtocols = `-- name: DeleteRouteProbesOutsideProtocols :exec
DELETE FROM model_route_probes pr
USING model_routes r
WHERE r.id = pr.route_id AND r.provider_id = $1
  AND NOT (pr.protocol = ANY ($2::text[]))
`

type DeleteRouteProbesOutsideProtocolsParams struct {
	ProviderID pgtype.UUID
	Protocols  []string
}

// When a provider stops speaking a protocol, the rows for that protocol's
// endpoints go with it on every route of the provider.
func (q *Queries) DeleteRouteProbesOutsideProtocols(ctx context.Context, arg DeleteRouteProbesOutsideProtocolsParams) error {
	_, err := q.db.Exec(ctx, deleteRouteProbesOutsideProtocols, arg.ProviderID, arg.Protocols)
	return err
}

const getModelBySlug = `-- name: GetModelBySlug :one
SELECT id, slug, display_name, context_window, max_output_tokens, capabilities, output_modalities, visibility, enabled, metadata, created_at, updated_at FROM models WHERE slug = $1 AND enabled
`

func (q *Queries) GetModelBySlug(ctx context.Context, slug string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelBySlug, slug)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.OutputModalities,
		&i.Visibility,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelForAdmin = `-- name: GetModelForAdmin :one
SELECT m.id, m.slug, m.display_name, m.enabled, m.visibility,
       m.context_window, m.max_output_tokens,
       m.output_modalities,
       m.metadata,
       COALESCE((SELECT array_agg(DISTINCT v.endpoint ORDER BY v.endpoint)
                 FROM model_published_endpoints v WHERE v.model_id = m.id), '{}')::text[] AS endpoints,
       COALESCE((SELECT array_agg(DISTINCT proto ORDER BY proto)
                 FROM model_routes r JOIN providers p ON p.id = r.provider_id, unnest(p.protocols) proto
                 WHERE r.model_id = m.id AND r.enabled AND p.enabled), '{}')::text[] AS protocols,
       (SELECT count(*) FROM model_routes r2 WHERE r2.model_id = m.id)::bigint AS route_count
FROM models m WHERE m.id = $1
`

type GetModelForAdminRow struct {
	ID               pgtype.UUID
	Slug             string
	DisplayName      string
	Enabled          bool
	Visibility       string
	ContextWindow    int32
	MaxOutputTokens  int32
	OutputModalities []string
	Metadata         []byte
	Endpoints        []string
	Protocols        []string
	RouteCount       int64
}

// Single-row read for the detail page; the column list is a literal copy of
// ListModelsForAdmin.
// Distinct from GetModelBySlug, which serves the dataplane, keys on slug and
// requires enabled. The admin page must be able to open a disabled model --
// otherwise disabling one makes it permanently unreachable.
func (q *Queries) GetModelForAdmin(ctx context.Context, id pgtype.UUID) (GetModelForAdminRow, error) {
	row := q.db.QueryRow(ctx, getModelForAdmin, id)
	var i GetModelForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Enabled,
		&i.Visibility,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.OutputModalities,
		&i.Metadata,
		&i.Endpoints,
		&i.Protocols,
		&i.RouteCount,
	)
	return i, err
}

const getProviderDetailForAdmin = `-- name: GetProviderDetailForAdmin :one
SELECT p.id, p.slug, p.vendor, p.protocols, p.name, p.base_url, p.enabled, p.auto_disabled, p.headers,
       p.transport, p.cost_multiplier_bps,
       p.rate_limit_rpm, p.rate_limit_tpm, p.max_concurrency,
       (SELECT count(*) FROM provider_keys k WHERE k.provider_id = p.id AND k.status = 'active')::bigint AS key_count,
       (SELECT count(*) FROM model_routes r WHERE r.provider_id = p.id AND r.enabled)::bigint AS route_count
FROM providers p WHERE p.id = $1
`

type GetProviderDetailForAdminRow struct {
	ID                pgtype.UUID
	Slug              string
	Vendor            string
	Protocols         []string
	Name              string
	BaseUrl           string
	Enabled           bool
	AutoDisabled      bool
	Headers           []byte
	Transport         []byte
	CostMultiplierBps int32
	RateLimitRpm      pgtype.Int4
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    int32
	KeyCount          int64
	RouteCount        int64
}

// Single-row read for the detail page. The column list is a literal copy of
// ListProvidersForAdmin: one missing column means one thing the detail page
// fails to render, and no gate can see a divergence between the two.
// Distinct from GetProviderForAdmin, which serves the connectivity test and
// model discovery and only needs identity plus base_url.
func (q *Queries) GetProviderDetailForAdmin(ctx context.Context, id pgtype.UUID) (GetProviderDetailForAdminRow, error) {
	row := q.db.QueryRow(ctx, getProviderDetailForAdmin, id)
	var i GetProviderDetailForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vendor,
		&i.Protocols,
		&i.Name,
		&i.BaseUrl,
		&i.Enabled,
		&i.AutoDisabled,
		&i.Headers,
		&i.Transport,
		&i.CostMultiplierBps,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.MaxConcurrency,
		&i.KeyCount,
		&i.RouteCount,
	)
	return i, err
}

const getProviderDiscovery = `-- name: GetProviderDiscovery :one
SELECT provider_id, checked_at, ok, complete, status_code, message, models
FROM provider_discoveries WHERE provider_id = $1
`

func (q *Queries) GetProviderDiscovery(ctx context.Context, providerID pgtype.UUID) (ProviderDiscovery, error) {
	row := q.db.QueryRow(ctx, getProviderDiscovery, providerID)
	var i ProviderDiscovery
	err := row.Scan(
		&i.ProviderID,
		&i.CheckedAt,
		&i.Ok,
		&i.Complete,
		&i.StatusCode,
		&i.Message,
		&i.Models,
	)
	return i, err
}

const getProviderForAdmin = `-- name: GetProviderForAdmin :one
SELECT id, slug, vendor, protocols, name, base_url, enabled, auto_disabled, headers, transport
FROM providers WHERE id = $1
`

type GetProviderForAdminRow struct {
	ID           pgtype.UUID
	Slug         string
	Vendor       string
	Protocols    []string
	Name         string
	BaseUrl      string
	Enabled      bool
	AutoDisabled bool
	Headers      []byte
	Transport    []byte
}

// Serves the connectivity test and model discovery, so it carries transport as
// well as headers: both of those build a real outbound request, and one built
// without the transport profile would report "cannot reach the upstream" for a
// provider the data plane reaches without trouble -- the diagnosis tool
// disagreeing with the thing it diagnoses.
func (q *Queries) GetProviderForAdmin(ctx context.Context, id pgtype.UUID) (GetProviderForAdminRow, error) {
	row := q.db.QueryRow(ctx, getProviderForAdmin, id)
	var i GetProviderForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vendor,
		&i.Protocols,
		&i.Name,
		&i.BaseUrl,
		&i.Enabled,
		&i.AutoDisabled,
		&i.Headers,
		&i.Transport,
	)
	return i, err
}

const getProviderKeyForProvider = `-- name: GetProviderKeyForProvider :one
SELECT id, provider_id, name, secret_enc, status
FROM provider_keys
WHERE id = $1 AND provider_id = $2
`

type GetProviderKeyForProviderParams struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
}

type GetProviderKeyForProviderRow struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
	Name       string
	SecretEnc  []byte
	Status     string
}

// Used when the connectivity test probes a specific key_id. Ownership must be
// verified here: without it, passing another provider's key_id would send that
// key to this provider's base_url.
func (q *Queries) GetProviderKeyForProvider(ctx context.Context, arg GetProviderKeyForProviderParams) (GetProviderKeyForProviderRow, error) {
	row := q.db.QueryRow(ctx, getProviderKeyForProvider, arg.ID, arg.ProviderID)
	var i GetProviderKeyForProviderRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.SecretEnc,
		&i.Status,
	)
	return i, err
}

const getProviderKeysForProvider = `-- name: GetProviderKeysForProvider :many
SELECT id, provider_id, name, secret_enc
FROM provider_keys
WHERE provider_id = $1 AND status = 'active'
ORDER BY id
`

type GetProviderKeysForProviderRow struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
	Name       string
	SecretEnc  []byte
}

// The source of truth for per-key cooldown is cooldowns(scope='provider_key');
// this table deliberately has no cooldown status column of its own.
func (q *Queries) GetProviderKeysForProvider(ctx context.Context, providerID pgtype.UUID) ([]GetProviderKeysForProviderRow, error) {
	rows, err := q.db.Query(ctx, getProviderKeysForProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProviderKeysForProviderRow
	for rows.Next() {
		var i GetProviderKeysForProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.SecretEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRouteProbe = `-- name: GetRouteProbe :one
SELECT pr.route_id, pr.endpoint, pr.probe_mode, pr.status, pr.source, pr.checked_at, pr.latency_ms, pr.status_code, pr.error, pr.probe_enqueued_at
FROM model_route_probes pr
WHERE pr.route_id = $1 AND pr.endpoint = $2
`

type GetRouteProbeParams struct {
	RouteID  pgtype.UUID
	Endpoint string
}

type GetRouteProbeRow struct {
	RouteID         pgtype.UUID
	Endpoint        string
	ProbeMode       string
	Status          string
	Source          string
	CheckedAt       pgtype.Timestamptz
	LatencyMs       pgtype.Int4
	StatusCode      pgtype.Int4
	Error           string
	ProbeEnqueuedAt pgtype.Timestamptz
}

func (q *Queries) GetRouteProbe(ctx context.Context, arg GetRouteProbeParams) (GetRouteProbeRow, error) {
	row := q.db.QueryRow(ctx, getRouteProbe, arg.RouteID, arg.Endpoint)
	var i GetRouteProbeRow
	err := row.Scan(
		&i.RouteID,
		&i.Endpoint,
		&i.ProbeMode,
		&i.Status,
		&i.Source,
		&i.CheckedAt,
		&i.LatencyMs,
		&i.StatusCode,
		&i.Error,
		&i.ProbeEnqueuedAt,
	)
	return i, err
}

const listActiveCooldowns = `-- name: ListActiveCooldowns :many

SELECT scope, ref_id, until, reason FROM cooldowns WHERE until > now()
`

type ListActiveCooldownsRow struct {
	Scope  string
	RefID  pgtype.UUID
	Until  pgtype.Timestamptz
	Reason string
}

// ===== Cooldown state (persisted so it survives a restart; the decision itself
// is made in memory). See docs/design/failover-and-cooldowns.md. =====
func (q *Queries) ListActiveCooldowns(ctx context.Context) ([]ListActiveCooldownsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCooldowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCooldownsRow
	for rows.Next() {
		var i ListActiveCooldownsRow
		if err := rows.Scan(
			&i.Scope,
			&i.RefID,
			&i.Until,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsForAdmin = `-- name: ListModelsForAdmin :many
SELECT m.id, m.slug, m.display_name, m.enabled, m.visibility,
       -- The edit dialog has to prefill current values. These two columns were
       -- once write-only, which meant "settable at creation, unchangeable
       -- afterwards" -- changing a display name took a hand-written API call.
       m.context_window, m.max_output_tokens,
       -- What the model produces (ADR-0226). Declared, so the catalog filter
       -- and the edit dialog both read it from here rather than guessing from
       -- the endpoint set -- an endpoint says how a model is called, not what
       -- comes back.
       m.output_modalities,
       -- metadata comes along with the list for the same reason: the mapping
       -- editor prefills from it, and without it every open would need a second
       -- single-model query.
       m.metadata,
       -- Published endpoints, from the same view the public catalog reads.
       COALESCE((SELECT array_agg(DISTINCT v.endpoint ORDER BY v.endpoint)
                 FROM model_published_endpoints v WHERE v.model_id = m.id), '{}')::text[] AS endpoints,
       -- The protocols the model is *configured* on: every protocol spoken by
       -- a provider that has an enabled route for it. This is the configuration
       -- view, for the catalog filter; the public catalog publishes the narrower
       -- verified set.
       COALESCE((SELECT array_agg(DISTINCT proto ORDER BY proto)
                 FROM model_routes r JOIN providers p ON p.id = r.provider_id, unnest(p.protocols) proto
                 WHERE r.model_id = m.id AND r.enabled AND p.enabled), '{}')::text[] AS protocols,
       (SELECT count(*) FROM model_routes r2 WHERE r2.model_id = m.id)::bigint AS route_count
FROM models m
WHERE ($1::text = ''
       OR m.slug ILIKE '%' || $1::text || '%'
       OR m.display_name ILIKE '%' || $1::text || '%')
ORDER BY m.slug
LIMIT 500
`

type ListModelsForAdminRow struct {
	ID               pgtype.UUID
	Slug             string
	DisplayName      string
	Enabled          bool
	Visibility       string
	ContextWindow    int32
	MaxOutputTokens  int32
	OutputModalities []string
	Metadata         []byte
	Endpoints        []string
	Protocols        []string
	RouteCount       int64
}

// Still capped rather than paginated, and the order is deliberate (ADR-0187):
// four consumers of this list are whole-set editors that need every configured
// model to stay visible and ticked. Search comes first so those editors have
// somewhere to move to; the cursor comes after they have moved.
// This one stays a cap rather than a probe: it also feeds the plain catalog
// page, which must keep rendering past the bound. The two route lists below are
// editor-only and probe one row over so the editor can refuse instead.
func (q *Queries) ListModelsForAdmin(ctx context.Context, search string) ([]ListModelsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listModelsForAdmin, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsForAdminRow
	for rows.Next() {
		var i ListModelsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Enabled,
			&i.Visibility,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.OutputModalities,
			&i.Metadata,
			&i.Endpoints,
			&i.Protocols,
			&i.RouteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderKeysForAdmin = `-- name: ListProviderKeysForAdmin :many

SELECT k.id, k.provider_id, k.name, k.status, k.secret_hint,
       k.last_verified_at, k.last_error, k.created_at,
       (SELECT c.until FROM cooldowns c
        WHERE c.scope = 'provider_key' AND c.ref_id = k.id AND c.until > now()) AS cooldown_until
FROM provider_keys k
WHERE k.provider_id = $1
  -- Keyset on (created_at, id): two keys added in one rotation script share a
  -- created_at, and a cursor on that alone loses one at the page boundary.
  AND ($2::timestamptz IS NULL
       OR (k.created_at, k.id) > ($2::timestamptz, $3::uuid))
ORDER BY k.created_at, k.id
LIMIT $4
`

type ListProviderKeysForAdminParams struct {
	ProviderID      pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	Lim             int32
}

type ListProviderKeysForAdminRow struct {
	ID             pgtype.UUID
	ProviderID     pgtype.UUID
	Name           string
	Status         string
	SecretHint     string
	LastVerifiedAt pgtype.Timestamptz
	LastError      string
	CreatedAt      pgtype.Timestamptz
	CooldownUntil  pgtype.Timestamptz
}

// ===== Admin write surface =====
// Every write to the catalog goes through here. The hot read path never touches
// these queries (it reads the cache), so clarity wins over cleverness.
// secret_enc is deliberately not returned: ciphertext only ever goes in, never
// out, and what the API layer never receives it cannot leak.
//
// cooldown_until comes from the same place the router uses: a tripped key
// writes cooldowns(scope='provider_key'), which is also what the breaker behind
// key selection consults (and what is read back on restart). Without a cooldown
// column the admin page would show a key as active while the router has already
// taken it out of rotation.
func (q *Queries) ListProviderKeysForAdmin(ctx context.Context, arg ListProviderKeysForAdminParams) ([]ListProviderKeysForAdminRow, error) {
	rows, err := q.db.Query(ctx, listProviderKeysForAdmin,
		arg.ProviderID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderKeysForAdminRow
	for rows.Next() {
		var i ListProviderKeysForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Status,
			&i.SecretHint,
			&i.LastVerifiedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.CooldownUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersForAdmin = `-- name: ListProvidersForAdmin :many

SELECT p.id, p.slug, p.vendor, p.protocols, p.name, p.base_url, p.enabled, p.auto_disabled, p.headers,
       p.transport, p.cost_multiplier_bps,
       p.rate_limit_rpm, p.rate_limit_tpm, p.max_concurrency,
       (SELECT count(*) FROM provider_keys k WHERE k.provider_id = p.id AND k.status = 'active')::bigint AS key_count,
       -- Only enabled routes are counted: a disabled route carries no traffic,
       -- and counting it as "some model is using this provider" would light up
       -- the provider's readiness checklist green while nothing actually routes
       -- through it. Same criterion the model enable gate uses.
       (SELECT count(*) FROM model_routes r WHERE r.provider_id = p.id AND r.enabled)::bigint AS route_count
FROM providers p
WHERE ($1::text = ''
       OR p.slug ILIKE '%' || $1::text || '%'
       OR p.name ILIKE '%' || $1::text || '%'
       OR p.base_url ILIKE '%' || $1::text || '%')
  -- No tiebreaker: providers.slug is UNIQUE, so slug alone is already a total
  -- order. The cursor packs exactly what the ORDER BY sorts by.
  AND (NOT $2::boolean OR p.slug > $3::text)
ORDER BY p.slug
LIMIT $4
`

type ListProvidersForAdminParams struct {
	Search     string
	HasCursor  bool
	CursorSlug string
	Lim        int32
}

type ListProvidersForAdminRow struct {
	ID                pgtype.UUID
	Slug              string
	Vendor            string
	Protocols         []string
	Name              string
	BaseUrl           string
	Enabled           bool
	AutoDisabled      bool
	Headers           []byte
	Transport         []byte
	CostMultiplierBps int32
	RateLimitRpm      pgtype.Int4
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    int32
	KeyCount          int64
	RouteCount        int64
}

// ===== Admin console =====
// Matching base_url too, because the list page's own search box always has:
// "which provider points at api.openai.com" is a question operators actually
// ask, and moving the filter server side must not quietly drop a field it
// used to cover.
func (q *Queries) ListProvidersForAdmin(ctx context.Context, arg ListProvidersForAdminParams) ([]ListProvidersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listProvidersForAdmin,
		arg.Search,
		arg.HasCursor,
		arg.CursorSlug,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProvidersForAdminRow
	for rows.Next() {
		var i ListProvidersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Vendor,
			&i.Protocols,
			&i.Name,
			&i.BaseUrl,
			&i.Enabled,
			&i.AutoDisabled,
			&i.Headers,
			&i.Transport,
			&i.CostMultiplierBps,
			&i.RateLimitRpm,
			&i.RateLimitTpm,
			&i.MaxConcurrency,
			&i.KeyCount,
			&i.RouteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersForProbe = `-- name: ListProvidersForProbe :many
SELECT id, slug, base_url, enabled, auto_disabled, transport FROM providers ORDER BY slug
`

type ListProvidersForProbeRow struct {
	ID           pgtype.UUID
	Slug         string
	BaseUrl      string
	Enabled      bool
	AutoDisabled bool
	Transport    []byte
}

// Liveness probe candidates: every provider, including disabled ones -- the
// probe is also what decides whether a provider can be brought back.
// protocols is not selected: the probe calls GET /v1/models, which is the same
// regardless of protocol.
// transport comes along because the probe builds a real URL: an upstream whose
// catalog lives at another path, or which requires a query parameter, answers
// 404 to the standard one. Probing without it would auto-disable a healthy
// provider on a schedule.
func (q *Queries) ListProvidersForProbe(ctx context.Context) ([]ListProvidersForProbeRow, error) {
	rows, err := q.db.Query(ctx, listProvidersForProbe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProvidersForProbeRow
	for rows.Next() {
		var i ListProvidersForProbeRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.BaseUrl,
			&i.Enabled,
			&i.AutoDisabled,
			&i.Transport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicModels = `-- name: ListPublicModels :many
WITH selected_plan AS (
    SELECT a.pricing_plan_id
      FROM org_pricing_plan_assignments a
      JOIN pricing_plans p ON p.id = a.pricing_plan_id AND p.status = 'active'
     WHERE $2::uuid IS NOT NULL
       AND a.org_id = $2::uuid AND NOT a.inherit_default
    UNION ALL
    SELECT p.id
      FROM pricing_plans p
     WHERE p.is_default AND p.status = 'active'
       AND NOT EXISTS (
           SELECT 1 FROM org_pricing_plan_assignments a
            WHERE $2::uuid IS NOT NULL
              AND a.org_id = $2::uuid AND NOT a.inherit_default
       )
    LIMIT 1
)
SELECT m.id, m.slug, m.display_name, m.context_window, m.max_output_tokens, m.capabilities, m.output_modalities, m.visibility, m.enabled, m.metadata, m.created_at, m.updated_at,
       -- What the catalog publishes is stated once, in the
       -- model_published_endpoints view: what a probe has seen working, plus
       -- what the platform has no credential to look at. Unverified endpoints
       -- elsewhere are callable but not listed: a listing the caller cannot
       -- act on is the failure this query exists to prevent, whereas an
       -- omission costs nothing. The protocols are those of the published
       -- endpoints, not the providers' declared sets: a provider may declare
       -- a protocol its preset base URL does not serve, and the catalog must
       -- not repeat the claim.
       COALESCE((SELECT array_agg(DISTINCT v.endpoint ORDER BY v.endpoint)
                 FROM model_published_endpoints v WHERE v.model_id = m.id), '{}')::text[] AS endpoints,
       COALESCE((SELECT array_agg(DISTINCT v.protocol ORDER BY v.protocol)
                 FROM model_published_endpoints v WHERE v.model_id = m.id), '{}')::text[] AS protocols,
       -- Price lives in exactly one place: the model_pricing row is the current
       -- price, and models carries no price columns at all.
       mp.model_id AS priced_model_id,
       -- Currency comes from model_pricing (a CHECK pins it to USD).
       COALESCE(mp.currency, 'USD')::text AS price_currency,
       mp.billing_mode AS current_billing_mode,
       mp.upstream_in_nano_per_mtok AS current_upstream_in_nano_per_mtok,
       mp.upstream_out_nano_per_mtok AS current_upstream_out_nano_per_mtok,
       mp.upstream_cache_read_nano_per_mtok AS current_upstream_cache_read_nano_per_mtok,
       mp.upstream_cache_write_nano_per_mtok AS current_upstream_cache_write_nano_per_mtok,
       mp.multiplier_bps AS current_model_multiplier_bps,
       mp.updated_at AS current_model_price_effective_at,
       -- Which family charges this model. Without it a per-second model is
       -- indistinguishable here from an unpriced one: its four token columns
       -- are explicit zeros, which every reader of this row would otherwise
       -- have to guess the meaning of.
       COALESCE(mp.pricing_family, 'tokens')::text AS current_pricing_family,
       -- The per-unit rate card, carried with the row rather than fetched per
       -- model: this query already answers "what does it cost" for every other
       -- family, and a second round trip per row is how a catalogue page turns
       -- into N+1 queries.
       COALESCE((
           SELECT jsonb_agg(jsonb_build_object(
                      'unit', u.unit, 'resolution', u.resolution,
                      'audio', u.audio, 'variant', u.variant,
                      'service_tier', u.service_tier,
                      'nano_per_unit', u.nano_per_unit)
                  ORDER BY u.unit, u.resolution, u.audio, u.variant, u.service_tier)
             FROM model_price_unit_rates u WHERE u.model_id = mp.model_id
       ), '[]'::jsonb)::jsonb AS current_unit_rates,
       -- Where the upstream rate came from and whether a person confirmed it.
       -- verified_at NULL means "a reference dataset suggested this, nobody
       -- checked it" -- see docs/design/reference-prices.md. A catalog that
       -- publishes a rate without saying which of the two it is invites the
       -- reader to assume the stronger one.
       mp.source_name AS current_price_source_name,
       mp.source_url AS current_price_source_url,
       mp.verified_at AS current_price_verified_at,
       pl.id AS current_pricing_plan_id,
       pl.default_multiplier_bps AS current_plan_default_multiplier_bps,
       po.multiplier_bps AS current_plan_override_multiplier_bps
FROM models m
LEFT JOIN model_pricing mp ON mp.model_id = m.id
LEFT JOIN selected_plan sp ON true
LEFT JOIN pricing_plans pl ON pl.id = sp.pricing_plan_id
LEFT JOIN pricing_plan_model_overrides po
    ON po.pricing_plan_id = sp.pricing_plan_id AND po.model_id = m.id
WHERE m.enabled AND m.visibility = 'public'
  AND EXISTS (
      SELECT 1 FROM model_routes r
      JOIN providers p ON p.id = r.provider_id
      WHERE r.model_id = m.id AND r.enabled AND p.enabled
  )
  AND (
      $1::uuid IS NULL
      OR EXISTS (
          SELECT 1 FROM model_tiers t
          WHERE t.id = $1::uuid AND t.allow_all_models
      )
      OR EXISTS (
          SELECT 1 FROM model_tier_models b
          WHERE b.tier_id = $1::uuid AND b.model_id = m.id
      )
  )
ORDER BY m.slug
`

type ListPublicModelsParams struct {
	TierID pgtype.UUID
	OrgID  pgtype.UUID
}

type ListPublicModelsRow struct {
	ID                                   pgtype.UUID
	Slug                                 string
	DisplayName                          string
	ContextWindow                        int32
	MaxOutputTokens                      int32
	Capabilities                         []byte
	OutputModalities                     []string
	Visibility                           string
	Enabled                              bool
	Metadata                             []byte
	CreatedAt                            pgtype.Timestamptz
	UpdatedAt                            pgtype.Timestamptz
	Endpoints                            []string
	Protocols                            []string
	PricedModelID                        pgtype.UUID
	PriceCurrency                        string
	CurrentBillingMode                   pgtype.Text
	CurrentUpstreamInNanoPerMtok         pgtype.Int8
	CurrentUpstreamOutNanoPerMtok        pgtype.Int8
	CurrentUpstreamCacheReadNanoPerMtok  pgtype.Int8
	CurrentUpstreamCacheWriteNanoPerMtok pgtype.Int8
	CurrentModelMultiplierBps            pgtype.Int4
	CurrentModelPriceEffectiveAt         pgtype.Timestamptz
	CurrentPricingFamily                 string
	CurrentUnitRates                     []byte
	CurrentPriceSourceName               pgtype.Text
	CurrentPriceSourceUrl                pgtype.Text
	CurrentPriceVerifiedAt               pgtype.Timestamptz
	CurrentPricingPlanID                 pgtype.UUID
	CurrentPlanDefaultMultiplierBps      pgtype.Int4
	CurrentPlanOverrideMultiplierBps     pgtype.Int4
}

// The public catalog behind GET /v1/models: only public, enabled models that
// have at least one usable route -- a model listed with nobody to serve it just
// hands the caller a 404.
// A NULL tier_id means no admission filtering; the anonymous catalog is the
// list price seen from the default tier, not any particular caller's usable
// set. When a tier is given, the criterion must match what the dataplane
// resolves, because "visible in the catalog, 404 on call" is exactly the kind of
// inconsistency that turns into a support ticket.
// The tier predicate is the same one the dataplane applies: a tier either
// admits everything or admits exactly what it lists.
// The pricing plan is resolved in the same statement as the prices, so a price
// change activating between two separate queries cannot produce a blend of old
// and new that never existed.
// With an org_id that org's own assignment wins, falling back to the default
// plan. With no org_id the default plan is still resolved, because the
// anonymous catalog is *defined* as the default plan's price: it is what a
// reader who signs up right now will actually be charged. Leaving the plan
// unresolved here would publish a list price nobody is on the moment the
// operator discounts the default plan -- and in the mark-up direction it would
// publish a price lower than the one charged.
func (q *Queries) ListPublicModels(ctx context.Context, arg ListPublicModelsParams) ([]ListPublicModelsRow, error) {
	rows, err := q.db.Query(ctx, listPublicModels, arg.TierID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicModelsRow
	for rows.Next() {
		var i ListPublicModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.OutputModalities,
			&i.Visibility,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Endpoints,
			&i.Protocols,
			&i.PricedModelID,
			&i.PriceCurrency,
			&i.CurrentBillingMode,
			&i.CurrentUpstreamInNanoPerMtok,
			&i.CurrentUpstreamOutNanoPerMtok,
			&i.CurrentUpstreamCacheReadNanoPerMtok,
			&i.CurrentUpstreamCacheWriteNanoPerMtok,
			&i.CurrentModelMultiplierBps,
			&i.CurrentModelPriceEffectiveAt,
			&i.CurrentPricingFamily,
			&i.CurrentUnitRates,
			&i.CurrentPriceSourceName,
			&i.CurrentPriceSourceUrl,
			&i.CurrentPriceVerifiedAt,
			&i.CurrentPricingPlanID,
			&i.CurrentPlanDefaultMultiplierBps,
			&i.CurrentPlanOverrideMultiplierBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteIDsForProvider = `-- name: ListRouteIDsForProvider :many
SELECT id FROM model_routes WHERE provider_id = $1 ORDER BY id
`

// Every route of a provider, for seeding probe rows when the provider gains a
// protocol or its first credential.
func (q *Queries) ListRouteIDsForProvider(ctx context.Context, providerID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRouteIDsForProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteProbes = `-- name: ListRouteProbes :many
SELECT pr.route_id, pr.endpoint, pr.probe_mode, pr.status, pr.source, pr.checked_at, pr.latency_ms, pr.status_code, pr.error, pr.probe_enqueued_at
FROM model_route_probes pr
JOIN model_routes r ON r.id = pr.route_id
JOIN providers p ON p.id = r.provider_id
WHERE r.model_id = $1 AND pr.protocol = ANY (p.protocols)
ORDER BY pr.route_id, pr.endpoint
`

type ListRouteProbesRow struct {
	RouteID         pgtype.UUID
	Endpoint        string
	ProbeMode       string
	Status          string
	Source          string
	CheckedAt       pgtype.Timestamptz
	LatencyMs       pgtype.Int4
	StatusCode      pgtype.Int4
	Error           string
	ProbeEnqueuedAt pgtype.Timestamptz
}

// Only endpoints of a protocol the provider still speaks: rows are deleted when
// a provider's protocol set narrows, but the read side filters as well so that
// the two never disagree.
func (q *Queries) ListRouteProbes(ctx context.Context, modelID pgtype.UUID) ([]ListRouteProbesRow, error) {
	rows, err := q.db.Query(ctx, listRouteProbes, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteProbesRow
	for rows.Next() {
		var i ListRouteProbesRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Endpoint,
			&i.ProbeMode,
			&i.Status,
			&i.Source,
			&i.CheckedAt,
			&i.LatencyMs,
			&i.StatusCode,
			&i.Error,
			&i.ProbeEnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteProbesDueForReprobe = `-- name: ListRouteProbesDueForReprobe :many
SELECT pr.route_id, pr.endpoint
FROM model_route_probes pr
JOIN model_routes r ON r.id = pr.route_id
JOIN providers p ON p.id = r.provider_id
WHERE pr.source <> 'operator'
  AND pr.probe_mode = 'auto'
  AND r.enabled AND p.enabled
  AND pr.protocol = ANY (p.protocols)
  AND EXISTS (SELECT 1 FROM provider_keys k WHERE k.provider_id = p.id AND k.status = 'active')
  AND (
      (pr.status = 'unverified' AND pr.updated_at < now() - $1::interval)
      OR (pr.status IN ('failed', 'unsupported') AND pr.checked_at < now() - $2::interval)
  )
ORDER BY COALESCE(pr.checked_at, pr.updated_at), pr.route_id, pr.endpoint
LIMIT $3
`

type ListRouteProbesDueForReprobeParams struct {
	UnverifiedAfter pgtype.Interval
	VerdictAfter    pgtype.Interval
	MaxRows         int32
}

type ListRouteProbesDueForReprobeRow struct {
	RouteID  pgtype.UUID
	Endpoint string
}

// The sweeper's work list: verdicts that have aged, on routes and providers
// that are still enabled, excluding operator overrides -- and only rows a
// probe can actually advance. Rows it cannot must not be here at all, because
// the batch is bounded and a row that is due forever would occupy it forever:
// manual endpoints are never probed on the sweeper's own initiative, and a
// provider with no active credential gives the worker nothing to probe with.
// Unverified rows are included after a short grace period, because a route
// whose creation-time job was lost sits at unverified with nothing else coming
// for it. Oldest first, so that whatever does not fit this hour is reached the
// next.
func (q *Queries) ListRouteProbesDueForReprobe(ctx context.Context, arg ListRouteProbesDueForReprobeParams) ([]ListRouteProbesDueForReprobeRow, error) {
	rows, err := q.db.Query(ctx, listRouteProbesDueForReprobe, arg.UnverifiedAfter, arg.VerdictAfter, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteProbesDueForReprobeRow
	for rows.Next() {
		var i ListRouteProbesDueForReprobeRow
		if err := rows.Scan(&i.RouteID, &i.Endpoint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteProbesForProvider = `-- name: ListRouteProbesForProvider :many
SELECT pr.route_id, pr.endpoint, pr.probe_mode, pr.status, pr.source, pr.checked_at, pr.latency_ms, pr.status_code, pr.error, pr.probe_enqueued_at
FROM model_route_probes pr
JOIN model_routes r ON r.id = pr.route_id
JOIN providers p ON p.id = r.provider_id
WHERE r.provider_id = $1 AND pr.protocol = ANY (p.protocols)
ORDER BY pr.route_id, pr.endpoint
`

type ListRouteProbesForProviderRow struct {
	RouteID         pgtype.UUID
	Endpoint        string
	ProbeMode       string
	Status          string
	Source          string
	CheckedAt       pgtype.Timestamptz
	LatencyMs       pgtype.Int4
	StatusCode      pgtype.Int4
	Error           string
	ProbeEnqueuedAt pgtype.Timestamptz
}

// Probe results read from the provider side; same as ListRouteProbes with the
// axis swapped.
func (q *Queries) ListRouteProbesForProvider(ctx context.Context, providerID pgtype.UUID) ([]ListRouteProbesForProviderRow, error) {
	rows, err := q.db.Query(ctx, listRouteProbesForProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteProbesForProviderRow
	for rows.Next() {
		var i ListRouteProbesForProviderRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Endpoint,
			&i.ProbeMode,
			&i.Status,
			&i.Source,
			&i.CheckedAt,
			&i.LatencyMs,
			&i.StatusCode,
			&i.Error,
			&i.ProbeEnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForAdmin = `-- name: ListRoutesForAdmin :many
SELECT r.id, r.model_id, m.slug AS model_slug,
       r.provider_id, p.slug AS provider_slug, p.protocols AS provider_protocols,
       r.provider_model_id, r.priority, r.weight, r.enabled, r.headers,
       r.context_window, r.max_output_tokens, r.quirks, r.video_envelope, r.max_images
FROM model_routes r
JOIN providers p ON p.id = r.provider_id
JOIN models m ON m.id = r.model_id
WHERE r.model_id = $1
ORDER BY r.priority, p.slug
LIMIT 501
`

type ListRoutesForAdminRow struct {
	ID                pgtype.UUID
	ModelID           pgtype.UUID
	ModelSlug         string
	ProviderID        pgtype.UUID
	ProviderSlug      string
	ProviderProtocols []string
	ProviderModelID   string
	Priority          int32
	Weight            int32
	Enabled           bool
	Headers           []byte
	ContextWindow     pgtype.Int4
	MaxOutputTokens   pgtype.Int4
	Quirks            []byte
	VideoEnvelope     []byte
	MaxImages         pgtype.Int4
}

// 有界而不是分页，且这是**整集编辑面的前提**：模型侧的接线弹窗按这份清单算出
// 「要建哪些、要删哪些」，清单缺一行，那一行就会被算作「未勾选」而删掉。
// 一个模型的路由数受限于已配置的供应商数（那是运维手工建的），所以上界在这里
// 是安全的；真有部署撞上它，该做的是把那个弹窗改成分批，不是给这里加游标。
// 多取一行：第 501 行出现时 Go 侧拒绝打开编辑面，而不是把截断的清单交出去。
func (q *Queries) ListRoutesForAdmin(ctx context.Context, modelID pgtype.UUID) ([]ListRoutesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listRoutesForAdmin, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesForAdminRow
	for rows.Next() {
		var i ListRoutesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.ModelSlug,
			&i.ProviderID,
			&i.ProviderSlug,
			&i.ProviderProtocols,
			&i.ProviderModelID,
			&i.Priority,
			&i.Weight,
			&i.Enabled,
			&i.Headers,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Quirks,
			&i.VideoEnvelope,
			&i.MaxImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForModel = `-- name: ListRoutesForModel :many

SELECT r.id, r.model_id, r.provider_id, r.provider_model_id,
       r.priority, r.weight, r.headers,
       r.context_window, r.max_output_tokens, r.quirks, r.video_envelope, r.max_images,
       p.slug AS provider_slug, p.vendor AS provider_vendor,
       $2::text AS protocol, p.base_url,
       p.headers AS provider_headers, p.transport AS provider_transport,
       p.rate_limit_rpm AS provider_rate_limit_rpm,
       p.rate_limit_tpm AS provider_rate_limit_tpm,
       p.max_concurrency AS provider_max_concurrency
FROM model_routes r
JOIN providers p ON p.id = r.provider_id
WHERE r.model_id = $1
  AND r.enabled AND p.enabled
  AND $2::text = ANY (p.protocols)
  AND NOT EXISTS (
      SELECT 1 FROM model_route_probes pr
      WHERE pr.route_id = r.id AND pr.endpoint = $3::text
        -- COALESCE: a NULL vendor list (a caller passing none) must read as
        -- "no exemption", not as an unknowable that lets the row through.
        AND pr.status = 'unsupported' AND NOT COALESCE(p.vendor = ANY ($4::text[]), false)
  )
  AND (
      NOT $5::boolean
      OR EXISTS (
          SELECT 1 FROM model_route_probes pr
          WHERE pr.route_id = r.id AND pr.endpoint = $3::text AND pr.status = 'ok'
      )
  )
ORDER BY r.priority, r.id
`

type ListRoutesForModelParams struct {
	ModelID         pgtype.UUID
	Protocol        string
	Endpoint        string
	ByokVendors     []string
	RequiresVerdict bool
}

type ListRoutesForModelRow struct {
	ID                     pgtype.UUID
	ModelID                pgtype.UUID
	ProviderID             pgtype.UUID
	ProviderModelID        string
	Priority               int32
	Weight                 int32
	Headers                []byte
	ContextWindow          pgtype.Int4
	MaxOutputTokens        pgtype.Int4
	Quirks                 []byte
	VideoEnvelope          []byte
	MaxImages              pgtype.Int4
	ProviderSlug           string
	ProviderVendor         string
	Protocol               string
	BaseUrl                string
	ProviderHeaders        []byte
	ProviderTransport      []byte
	ProviderRateLimitRpm   pgtype.Int4
	ProviderRateLimitTpm   pgtype.Int4
	ProviderMaxConcurrency int32
}

// Catalog reads for the gateway: resolving a model on the request path.
// In steady state a cache in front of these absorbs the traffic and the database
// is only touched on a miss.
// The usable candidates for a model across providers, filtered by the protocol the
// request surface belongs to and by what has been observed about the endpoint.
//
// A route is a candidate for an automatically probed endpoint unless a probe
// has found the endpoint unsupported on it. No row, `unverified` and `failed`
// all let the request through: the upstream is the authority on what it
// serves, and a live request is the cheapest way to ask. A 404 from the
// upstream is classified as a route problem by the data plane and enqueues a
// probe, whose verdict -- not the request -- is what removes the candidate.
// An endpoint the gateway refuses to probe on its own (images) is the other
// way round: a candidate only once a verdict says `ok`, because nothing would
// ever converge otherwise and every request would be the probe. The caller
// says which kind the endpoint is (requires_verdict), from the same surface
// table the seeder writes probe_mode from, so the rule does not depend on a
// row having been seeded.
//
// byok_vendors are the vendors this organization brings its own credential
// for. An `unsupported` verdict was reached with the platform's shared
// credential, and "404" from an upstream also means "your project has no
// access"; the organization's own key may well have it, so for those vendors
// the verdict does not exclude. An empty result here renders 404
// model_not_found.
//
// Protocol membership is decided by whether a provider *speaks the protocol*
// (`= ANY (p.protocols)`), not by which protocol a provider "belongs to". An
// aggregating relay that exposes chat, messages and responses at once is one
// provider row, not two copies each carrying their own credentials and breaker
// state.
//
// The protocol column returned is the *request* protocol, not a column on the
// provider: the candidates have already been filtered by that protocol, so for
// this candidate it is the protocol we are about to speak upstream. With
// multi-protocol providers the provider row has no single value to offer anyway,
// and everything downstream (outbound auth headers, the same-protocol gate for
// organization credentials) wants the request protocol. See
// docs/design/same-protocol-passthrough.md.
func (q *Queries) ListRoutesForModel(ctx context.Context, arg ListRoutesForModelParams) ([]ListRoutesForModelRow, error) {
	rows, err := q.db.Query(ctx, listRoutesForModel,
		arg.ModelID,
		arg.Protocol,
		arg.Endpoint,
		arg.ByokVendors,
		arg.RequiresVerdict,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesForModelRow
	for rows.Next() {
		var i ListRoutesForModelRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.ProviderID,
			&i.ProviderModelID,
			&i.Priority,
			&i.Weight,
			&i.Headers,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Quirks,
			&i.VideoEnvelope,
			&i.MaxImages,
			&i.ProviderSlug,
			&i.ProviderVendor,
			&i.Protocol,
			&i.BaseUrl,
			&i.ProviderHeaders,
			&i.ProviderTransport,
			&i.ProviderRateLimitRpm,
			&i.ProviderRateLimitTpm,
			&i.ProviderMaxConcurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForProviderAdmin = `-- name: ListRoutesForProviderAdmin :many
SELECT r.id, r.model_id, m.slug AS model_slug,
       r.provider_id, p.slug AS provider_slug, p.protocols AS provider_protocols,
       r.provider_model_id, r.priority, r.weight, r.enabled, r.headers,
       r.context_window, r.max_output_tokens, r.quirks, r.video_envelope, r.max_images
FROM model_routes r
JOIN providers p ON p.id = r.provider_id
JOIN models m ON m.id = r.model_id
WHERE r.provider_id = $1
ORDER BY m.slug
LIMIT 501
`

type ListRoutesForProviderAdminRow struct {
	ID                pgtype.UUID
	ModelID           pgtype.UUID
	ModelSlug         string
	ProviderID        pgtype.UUID
	ProviderSlug      string
	ProviderProtocols []string
	ProviderModelID   string
	Priority          int32
	Weight            int32
	Enabled           bool
	Headers           []byte
	ContextWindow     pgtype.Int4
	MaxOutputTokens   pgtype.Int4
	Quirks            []byte
	VideoEnvelope     []byte
	MaxImages         pgtype.Int4
}

// The same rows read from the provider side, for the Models panel on a provider's
// detail page. Identical columns to ListRoutesForAdmin, only the WHERE axis and
// the sort key differ: that panel is read model by model, so it sorts by model
// slug rather than by priority -- priorities on different models of the same
// provider are not comparable, and sorting by them is effectively random.
// 同 ListRoutesForAdmin：供应商侧的接线弹窗也是整集编辑，缺行即删行。
func (q *Queries) ListRoutesForProviderAdmin(ctx context.Context, providerID pgtype.UUID) ([]ListRoutesForProviderAdminRow, error) {
	rows, err := q.db.Query(ctx, listRoutesForProviderAdmin, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesForProviderAdminRow
	for rows.Next() {
		var i ListRoutesForProviderAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.ModelSlug,
			&i.ProviderID,
			&i.ProviderSlug,
			&i.ProviderProtocols,
			&i.ProviderModelID,
			&i.Priority,
			&i.Weight,
			&i.Enabled,
			&i.Headers,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Quirks,
			&i.VideoEnvelope,
			&i.MaxImages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProviderKeyVerified = `-- name: MarkProviderKeyVerified :exec
UPDATE provider_keys SET last_verified_at = now(), last_error = $2 WHERE id = $1
`

type MarkProviderKeyVerifiedParams struct {
	ID        pgtype.UUID
	LastError string
}

// Records the outcome of a connectivity test. A failure does not disable the
// key: the probe worker is the only authority for automatic disabling, and one
// failed manual test may just mean the upstream model name was typed wrong.
func (q *Queries) MarkProviderKeyVerified(ctx context.Context, arg MarkProviderKeyVerifiedParams) error {
	_, err := q.db.Exec(ctx, markProviderKeyVerified, arg.ID, arg.LastError)
	return err
}

const markRouteProbesEnqueued = `-- name: MarkRouteProbesEnqueued :exec
UPDATE model_route_probes
   SET probe_enqueued_at = now(), updated_at = now()
 WHERE route_id = $1
   AND CASE WHEN cardinality($2::text[]) = 0
            THEN probe_mode = 'auto'
            ELSE endpoint = ANY ($2::text[])
       END
`

type MarkRouteProbesEnqueuedParams struct {
	RouteID   pgtype.UUID
	Endpoints []string
}

// Mark the rows a probe job is about to answer as in flight.
//
// The endpoint selection is the worker's own rule, written once here rather
// than recomputed by each caller: the endpoints named, or every automatically
// probed one when none is. `probe_mode` is a stored column precisely so SQL can
// express that without spelling any endpoint's name.
//
// Marking at enqueue rather than when the worker picks the job up, because the
// question the marker answers -- "is one already running, or may I ask for
// one?" -- is asked by an interface a moment after somebody clicked, and on the
// endpoints that are never probed automatically the answer decides whether they
// pay for a second generation.
func (q *Queries) MarkRouteProbesEnqueued(ctx context.Context, arg MarkRouteProbesEnqueuedParams) error {
	_, err := q.db.Exec(ctx, markRouteProbesEnqueued, arg.RouteID, arg.Endpoints)
	return err
}

const providerHealthLastHour = `-- name: ProviderHealthLastHour :many
SELECT p.id, p.slug,
       COALESCE(SUM(ru.requests), 0)::bigint AS requests,
       COALESCE(SUM(ru.errors), 0)::bigint AS errors
FROM providers p
LEFT JOIN gateway_usage_rollups ru
       ON ru.provider_id = p.id AND ru.bucket_start >= now() - interval '1 hour'
GROUP BY p.id, p.slug
ORDER BY p.slug
`

type ProviderHealthLastHourRow struct {
	ID       pgtype.UUID
	Slug     string
	Requests int64
	Errors   int64
}

func (q *Queries) ProviderHealthLastHour(ctx context.Context) ([]ProviderHealthLastHourRow, error) {
	rows, err := q.db.Query(ctx, providerHealthLastHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderHealthLastHourRow
	for rows.Next() {
		var i ProviderHealthLastHourRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Requests,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerLatencyLastHour = `-- name: ProviderLatencyLastHour :many
SELECT p.id,
       COALESCE(SUM(ru.lat_count), 0)::bigint       AS samples,
       COALESCE(SUM(ru.lat_le_100), 0)::bigint      AS le_100,
       COALESCE(SUM(ru.lat_le_250), 0)::bigint      AS le_250,
       COALESCE(SUM(ru.lat_le_500), 0)::bigint      AS le_500,
       COALESCE(SUM(ru.lat_le_1000), 0)::bigint     AS le_1000,
       COALESCE(SUM(ru.lat_le_2500), 0)::bigint     AS le_2500,
       COALESCE(SUM(ru.lat_le_5000), 0)::bigint     AS le_5000,
       COALESCE(SUM(ru.lat_le_10000), 0)::bigint    AS le_10000,
       COALESCE(SUM(ru.lat_le_30000), 0)::bigint    AS le_30000,
       COALESCE(SUM(ru.lat_le_60000), 0)::bigint    AS le_60000,
       COALESCE(SUM(ru.lat_le_120000), 0)::bigint   AS le_120000,
       COALESCE(SUM(ru.duration_ms_sum), 0)::bigint AS duration_ms_sum
FROM providers p
LEFT JOIN gateway_usage_rollups ru
       ON ru.provider_id = p.id AND ru.bucket_start >= now() - interval '1 hour'
GROUP BY p.id
ORDER BY p.id
`

type ProviderLatencyLastHourRow struct {
	ID            pgtype.UUID
	Samples       int64
	Le100         int64
	Le250         int64
	Le500         int64
	Le1000        int64
	Le2500        int64
	Le5000        int64
	Le10000       int64
	Le30000       int64
	Le60000       int64
	Le120000      int64
	DurationMsSum int64
}

// Per-provider latency histogram over the last hour, for the health dashboard.
//
// The join is on provider_id directly, not routed through model_routes and
// models. The older form went providers -> routes -> models -> rollups keyed by
// model_slug, which meant:
//
//	a model served by two providers  -> each provider showed that model's
//	                                    entire request and error volume
//	two routes on the same provider  -> the same data counted twice
//
// In other words the "error rate for this provider" was neither this provider's
// nor any real number at all.
//
// Same source and same window as ProviderHealthLastHour (both read the last
// hour of the rollups), so "error rate" and "latency" describe the same set of
// requests. Taken from different windows the two would contradict each other
// during an incident review with no way to tell which to believe.
//
// The quantile is not computed in SQL: the rollups store a cumulative histogram
// rather than raw samples, so percentile_cont has nothing to work with. The
// columns are summed here and interpolated in Go.
func (q *Queries) ProviderLatencyLastHour(ctx context.Context) ([]ProviderLatencyLastHourRow, error) {
	rows, err := q.db.Query(ctx, providerLatencyLastHour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderLatencyLastHourRow
	for rows.Next() {
		var i ProviderLatencyLastHourRow
		if err := rows.Scan(
			&i.ID,
			&i.Samples,
			&i.Le100,
			&i.Le250,
			&i.Le500,
			&i.Le1000,
			&i.Le2500,
			&i.Le5000,
			&i.Le10000,
			&i.Le30000,
			&i.Le60000,
			&i.Le120000,
			&i.DurationMsSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetRouteProbes = `-- name: ResetRouteProbes :exec
UPDATE model_route_probes
SET status = 'unverified', source = 'probe', checked_at = NULL, latency_ms = NULL,
    status_code = NULL, error = '', updated_at = now()
WHERE route_id = $1
`

// Changing the upstream model name invalidates every previous verdict, the
// operator's included. Keeping one would be worse than having none: a stale
// green reads as a current one, and an override was about the old name.
func (q *Queries) ResetRouteProbes(ctx context.Context, routeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetRouteProbes, routeID)
	return err
}

const resolveModelsByUpstreamID = `-- name: ResolveModelsByUpstreamID :many
SELECT DISTINCT m.slug
FROM model_routes r
JOIN providers p ON p.id = r.provider_id
JOIN models m ON m.id = r.model_id
WHERE p.vendor = $1
  AND r.provider_model_id = $2
  AND r.enabled AND p.enabled AND m.enabled
  AND $3::text = ANY (p.protocols)
ORDER BY m.slug
`

type ResolveModelsByUpstreamIDParams struct {
	Vendor          string
	ProviderModelID string
	Protocol        string
}

// The reverse of the usual direction, and it exists for exactly one caller: a
// vendor compatibility surface, where the caller sends that vendor's own model
// name because that is what their existing code sends. Admission resolves by
// catalog slug, so the two have to be joined somewhere, and the join is here
// rather than in a map somebody maintains.
//
// Deployment-wide rather than scoped to the caller's organization, deliberately.
// What is being answered is "does this deployment wire that upstream name at
// all", which is a fact about the catalogue; whether this caller may use the
// model is admission's question and is asked next, so a model they cannot reach
// still refuses. Answering it here as well would make the two disagree.
//
// Several rows is not an error to resolve here: two catalog models wired to the
// same upstream name on the same vendor have different rate cards, and picking
// one would charge against a card nobody chose. The caller reports it.
func (q *Queries) ResolveModelsByUpstreamID(ctx context.Context, arg ResolveModelsByUpstreamIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, resolveModelsByUpstreamID, arg.Vendor, arg.ProviderModelID, arg.Protocol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const routeForProbe = `-- name: RouteForProbe :one
SELECT r.id, r.provider_model_id,
       p.id AS provider_id, p.protocols, p.vendor, p.base_url, p.headers AS provider_headers,
       p.transport AS provider_transport,
       r.headers AS route_headers
FROM model_routes r JOIN providers p ON p.id = r.provider_id
WHERE r.id = $1
`

type RouteForProbeRow struct {
	ID                pgtype.UUID
	ProviderModelID   string
	ProviderID        pgtype.UUID
	Protocols         []string
	Vendor            string
	BaseUrl           string
	ProviderHeaders   []byte
	ProviderTransport []byte
	RouteHeaders      []byte
}

// The context a probe job needs: the route, the provider, and the provider's
// first usable credential.
// Which protocol a probe request speaks is decided by the endpoint being probed,
// not by a column on the provider: a multi-protocol provider has no single
// protocol to read, while probing messages must send that protocol's auth header
// and probing chat must send a bearer token. protocols decides which endpoints
// the route is probed on at all.
// p.transport is selected because the probe has to build the same request the
// data plane builds. Without it the worker probed with the default profile
// while the operator's button probed with the provider's real one -- two greens
// for the same route that could contradict each other, which is exactly what
// sharing one probe implementation is supposed to prevent.
// p.vendor is selected for the same reason p.transport is: on the video plane
// the request shape comes from the vendor's mapper, so a probe that did not
// know the vendor could not build the request the data plane would send.
func (q *Queries) RouteForProbe(ctx context.Context, id pgtype.UUID) (RouteForProbeRow, error) {
	row := q.db.QueryRow(ctx, routeForProbe, id)
	var i RouteForProbeRow
	err := row.Scan(
		&i.ID,
		&i.ProviderModelID,
		&i.ProviderID,
		&i.Protocols,
		&i.Vendor,
		&i.BaseUrl,
		&i.ProviderHeaders,
		&i.ProviderTransport,
		&i.RouteHeaders,
	)
	return i, err
}

const routeParties = `-- name: RouteParties :one
SELECT m.id AS model_id, p.protocols AS provider_protocols
FROM models m, providers p
WHERE m.id = $1 AND p.id = $2
`

type RoutePartiesParams struct {
	ModelID    pgtype.UUID
	ProviderID pgtype.UUID
}

type RoutePartiesRow struct {
	ModelID           pgtype.UUID
	ProviderProtocols []string
}

// Existence check before creating a route, and the protocol set the route's
// probe rows are seeded from. A cross join with two equality conditions: if
// either side does not exist the result is zero rows, which is how the caller
// tells "not found" apart from anything else. There is no protocol to compare
// on the model side: a model is reachable on whatever its providers speak.
func (q *Queries) RouteParties(ctx context.Context, arg RoutePartiesParams) (RoutePartiesRow, error) {
	row := q.db.QueryRow(ctx, routeParties, arg.ModelID, arg.ProviderID)
	var i RoutePartiesRow
	err := row.Scan(&i.ModelID, &i.ProviderProtocols)
	return i, err
}

const routeUnderModel = `-- name: RouteUnderModel :one
SELECT r.id, p.protocols AS provider_protocols
FROM model_routes r JOIN providers p ON p.id = r.provider_id
WHERE r.id = $1 AND r.model_id = $2
`

type RouteUnderModelParams struct {
	RouteID pgtype.UUID
	ModelID pgtype.UUID
}

type RouteUnderModelRow struct {
	ID                pgtype.UUID
	ProviderProtocols []string
}

// One route under one model, with the protocol set its endpoints are drawn
// from: the operator's per-endpoint writes check both before touching a row.
func (q *Queries) RouteUnderModel(ctx context.Context, arg RouteUnderModelParams) (RouteUnderModelRow, error) {
	row := q.db.QueryRow(ctx, routeUnderModel, arg.RouteID, arg.ModelID)
	var i RouteUnderModelRow
	err := row.Scan(&i.ID, &i.ProviderProtocols)
	return i, err
}

const saveRouteProbe = `-- name: SaveRouteProbe :one
INSERT INTO model_route_probes (
    route_id, endpoint, protocol, probe_mode, status, source, checked_at, latency_ms, status_code, error
) VALUES ($1, $2, $3, $4, $5, 'probe', now(), $6, $7, $8)
ON CONFLICT (route_id, endpoint) DO UPDATE SET
    status = CASE
        WHEN excluded.status = 'failed' AND model_route_probes.status = 'ok' THEN 'ok'
        WHEN excluded.status = 'unsupported' AND model_route_probes.status = 'ok'
             AND NOT (model_route_probes.status_code IN (404, 405)
                      AND model_route_probes.checked_at > now() - interval '1 hour') THEN 'ok'
        ELSE excluded.status
    END,
    checked_at = excluded.checked_at,
    latency_ms = excluded.latency_ms, status_code = excluded.status_code,
    -- The verdict has landed, so the row is no longer in flight. Cleared here
    -- rather than by the caller because every writer of a verdict has to do it:
    -- a marker left set is an endpoint the interface will never let anybody
    -- probe again.
    error = excluded.error, probe_enqueued_at = NULL, updated_at = now()
WHERE model_route_probes.source <> 'operator'
RETURNING status
`

type SaveRouteProbeParams struct {
	RouteID    pgtype.UUID
	Endpoint   string
	Protocol   string
	ProbeMode  string
	Status     string
	LatencyMs  pgtype.Int4
	StatusCode pgtype.Int4
	Error      string
}

// The probe worker's verdict. Three guards live in the upsert rather than in
// the caller, because every writer must obey them:
//   - an operator's override is never overwritten by the worker;
//   - `failed` never downgrades `ok` -- it is an inconclusive answer (5xx,
//     timeout, quota, credential, or a body the upstream would not take), and
//     letting it flip a verified endpoint would churn the public catalog on
//     every upstream incident;
//   - `unsupported` downgrades `ok` only on a confirming second sample: one
//     404 cannot tell "gone" from "being rolled", so the first keeps the
//     verdict and records the 404, and the next 404 within an hour flips it.
//     The worker schedules that second look itself (see the returned status).
//
// In every case the timestamp, status and message of the latest probe are
// recorded, so the admin page shows what happened even while the verdict
// stands.
func (q *Queries) SaveRouteProbe(ctx context.Context, arg SaveRouteProbeParams) (string, error) {
	row := q.db.QueryRow(ctx, saveRouteProbe,
		arg.RouteID,
		arg.Endpoint,
		arg.Protocol,
		arg.ProbeMode,
		arg.Status,
		arg.LatencyMs,
		arg.StatusCode,
		arg.Error,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const seedRouteProbe = `-- name: SeedRouteProbe :exec

INSERT INTO model_route_probes (route_id, endpoint, protocol, probe_mode) VALUES ($1, $2, $3, $4)
ON CONFLICT (route_id, endpoint) DO NOTHING
`

type SeedRouteProbeParams struct {
	RouteID   pgtype.UUID
	Endpoint  string
	Protocol  string
	ProbeMode string
}

// ===== Route probes =====
//
// One row per (route, endpoint): the only record of what a route serves. The
// data plane reads it to skip unsupported endpoints and the catalog reads it to
// publish verified ones; see the table comment in the migration for the two
// thresholds.
// Create the row in the unverified state when a route is created or a provider
// starts speaking a protocol, so the admin page can show "not checked yet"
// rather than nothing at all.
func (q *Queries) SeedRouteProbe(ctx context.Context, arg SeedRouteProbeParams) error {
	_, err := q.db.Exec(ctx, seedRouteProbe,
		arg.RouteID,
		arg.Endpoint,
		arg.Protocol,
		arg.ProbeMode,
	)
	return err
}

const setProviderAutoDisabled = `-- name: SetProviderAutoDisabled :exec
UPDATE providers SET enabled = false, auto_disabled = true, updated_at = now() WHERE id = $1
`

// Persist the probe's verdict: auto-disable or auto-recover, flagged so it can
// be told apart from a manual change.
func (q *Queries) SetProviderAutoDisabled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setProviderAutoDisabled, id)
	return err
}

const setProviderAutoEnabled = `-- name: SetProviderAutoEnabled :exec
UPDATE providers SET enabled = true, auto_disabled = false, updated_at = now()
WHERE id = $1 AND auto_disabled
`

func (q *Queries) SetProviderAutoEnabled(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setProviderAutoEnabled, id)
	return err
}

const setProviderKeySecret = `-- name: SetProviderKeySecret :exec
UPDATE provider_keys SET secret_enc = $2 WHERE id = $1
`

type SetProviderKeySecretParams struct {
	ID        pgtype.UUID
	SecretEnc []byte
}

// Back-fill the ciphertext: the AEAD associated data is bound to the row id, so
// the row has to exist before its secret can be encrypted.
func (q *Queries) SetProviderKeySecret(ctx context.Context, arg SetProviderKeySecretParams) error {
	_, err := q.db.Exec(ctx, setProviderKeySecret, arg.ID, arg.SecretEnc)
	return err
}

const setRouteProbeOverride = `-- name: SetRouteProbeOverride :exec
INSERT INTO model_route_probes (route_id, endpoint, protocol, probe_mode, status, source, checked_at, error)
VALUES ($1, $2, $3, $4, $5, 'operator', now(), '')
ON CONFLICT (route_id, endpoint) DO UPDATE SET
    status = excluded.status, source = 'operator', checked_at = now(),
    latency_ms = NULL, status_code = NULL, error = '',
    -- An operator answering by hand ends whatever was in flight: the row has a
    -- verdict now, and it is theirs.
    probe_enqueued_at = NULL, updated_at = now()
`

type SetRouteProbeOverrideParams struct {
	RouteID   pgtype.UUID
	Endpoint  string
	Protocol  string
	ProbeMode string
	Status    string
}

// The operator's override: a verdict typed in, marked as such so the worker
// leaves it alone. Rows are only ever for endpoints of a protocol the provider
// speaks, which the caller checks; the protocol column is written from the
// endpoint so that the row is filtered like any other.
func (q *Queries) SetRouteProbeOverride(ctx context.Context, arg SetRouteProbeOverrideParams) error {
	_, err := q.db.Exec(ctx, setRouteProbeOverride,
		arg.RouteID,
		arg.Endpoint,
		arg.Protocol,
		arg.ProbeMode,
		arg.Status,
	)
	return err
}

const sweepStaleProbeEnqueued = `-- name: SweepStaleProbeEnqueued :execrows
UPDATE model_route_probes SET probe_enqueued_at = NULL, updated_at = now()
 WHERE probe_enqueued_at IS NOT NULL AND probe_enqueued_at < $1::timestamptz
`

// The backstop. A worker that died between marking and answering would leave a
// row in flight forever, and forever is the one duration an operator cannot
// wait out: the interface would never let them ask again.
func (q *Queries) SweepStaleProbeEnqueued(ctx context.Context, olderThan pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStaleProbeEnqueued, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModel = `-- name: UpdateModel :one
UPDATE models SET
    display_name = coalesce($1, display_name),
    enabled      = coalesce($2, enabled),
    visibility   = coalesce($3, visibility),
    context_window    = coalesce($4, context_window),
    max_output_tokens = coalesce($5, max_output_tokens),
    -- nullif for the same reason as at creation: ` + "`" + `[]` + "`" + ` is "leave it alone", not
    -- an empty modality set the column would refuse.
    output_modalities = coalesce(
        nullif($6::text[], '{}'::text[]), output_modalities),
    updated_at = now()
WHERE id = $7
RETURNING id, slug, display_name, enabled, visibility, output_modalities
`

type UpdateModelParams struct {
	DisplayName      pgtype.Text
	Enabled          pgtype.Bool
	Visibility       pgtype.Text
	ContextWindow    pgtype.Int4
	MaxOutputTokens  pgtype.Int4
	OutputModalities []string
	ID               pgtype.UUID
}

type UpdateModelRow struct {
	ID               pgtype.UUID
	Slug             string
	DisplayName      string
	Enabled          bool
	Visibility       string
	OutputModalities []string
}

// Partial update: NULL means the field is unchanged (an unset pgtype value is
// NULL).
func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (UpdateModelRow, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.DisplayName,
		arg.Enabled,
		arg.Visibility,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.OutputModalities,
		arg.ID,
	)
	var i UpdateModelRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Enabled,
		&i.Visibility,
		&i.OutputModalities,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers SET
    name = COALESCE($1, name),
    vendor = COALESCE($2, vendor),
    protocols = COALESCE(
        (SELECT array_agg(DISTINCT f ORDER BY f) FROM unnest($3::text[]) AS f),
        protocols),
    base_url = COALESCE($4, base_url),
    enabled = COALESCE($5, enabled),
    headers = COALESCE($6, headers),
    transport = COALESCE($7, transport),
    cost_multiplier_bps = COALESCE($8, cost_multiplier_bps),
    -- The two ceilings take a clear flag each, for the reason spelled out on
    -- UpdateAPIKeyControls: a nullable parameter cannot tell "leave it alone"
    -- from "remove it", and removing a ceiling has to be sayable.
    rate_limit_rpm = CASE WHEN $9::boolean THEN NULL
                          WHEN $10::integer IS NOT NULL
                            THEN $10::integer
                          ELSE rate_limit_rpm END,
    rate_limit_tpm = CASE WHEN $11::boolean THEN NULL
                          WHEN $12::integer IS NOT NULL
                            THEN $12::integer
                          ELSE rate_limit_tpm END,
    max_concurrency = COALESCE($13, max_concurrency),
    auto_disabled = CASE WHEN $5 IS NOT NULL THEN false ELSE auto_disabled END,
    updated_at = now()
WHERE id = $14
RETURNING id, slug, vendor, protocols, name, base_url, enabled, auto_disabled, headers, transport,
          cost_multiplier_bps, rate_limit_rpm, rate_limit_tpm, max_concurrency
`

type UpdateProviderParams struct {
	Name              pgtype.Text
	Vendor            pgtype.Text
	Protocols         []string
	BaseUrl           pgtype.Text
	Enabled           pgtype.Bool
	Headers           []byte
	Transport         []byte
	CostMultiplierBps pgtype.Int4
	ClearRateLimitRpm bool
	RateLimitRpm      pgtype.Int4
	ClearRateLimitTpm bool
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    pgtype.Int4
	ID                pgtype.UUID
}

type UpdateProviderRow struct {
	ID                pgtype.UUID
	Slug              string
	Vendor            string
	Protocols         []string
	Name              string
	BaseUrl           string
	Enabled           bool
	AutoDisabled      bool
	Headers           []byte
	Transport         []byte
	CostMultiplierBps int32
	RateLimitRpm      pgtype.Int4
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    int32
}

// Partial update: NULL means the field is unchanged. Enabling by hand also
// clears auto_disabled -- an explicit operator action takes the provider over,
// and the probe stops flipping it automatically from then on.
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (UpdateProviderRow, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.Name,
		arg.Vendor,
		arg.Protocols,
		arg.BaseUrl,
		arg.Enabled,
		arg.Headers,
		arg.Transport,
		arg.CostMultiplierBps,
		arg.ClearRateLimitRpm,
		arg.RateLimitRpm,
		arg.ClearRateLimitTpm,
		arg.RateLimitTpm,
		arg.MaxConcurrency,
		arg.ID,
	)
	var i UpdateProviderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Vendor,
		&i.Protocols,
		&i.Name,
		&i.BaseUrl,
		&i.Enabled,
		&i.AutoDisabled,
		&i.Headers,
		&i.Transport,
		&i.CostMultiplierBps,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.MaxConcurrency,
	)
	return i, err
}

const updateProviderKey = `-- name: UpdateProviderKey :one
UPDATE provider_keys
SET name   = COALESCE($1::text, name),
    status = COALESCE($2::text, status)
WHERE id = $3 AND provider_id = $4
RETURNING id, provider_id, name, status, secret_hint, last_verified_at, last_error
`

type UpdateProviderKeyParams struct {
	Name       pgtype.Text
	Status     pgtype.Text
	ID         pgtype.UUID
	ProviderID pgtype.UUID
}

type UpdateProviderKeyRow struct {
	ID             pgtype.UUID
	ProviderID     pgtype.UUID
	Name           string
	Status         string
	SecretHint     string
	LastVerifiedAt pgtype.Timestamptz
	LastError      string
}

// Carries a provider_id predicate, like DeleteProviderKey: a tampered path
// parameter fails silently instead of modifying another provider's key.
// The safe rotation order is add new -> verify new -> disable old. Without an
// update statement the only available move was to delete the old key first,
// which is the most dangerous order there is.
func (q *Queries) UpdateProviderKey(ctx context.Context, arg UpdateProviderKeyParams) (UpdateProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, updateProviderKey,
		arg.Name,
		arg.Status,
		arg.ID,
		arg.ProviderID,
	)
	var i UpdateProviderKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Status,
		&i.SecretHint,
		&i.LastVerifiedAt,
		&i.LastError,
	)
	return i, err
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE model_routes SET
    provider_model_id = coalesce($1, provider_model_id),
    priority  = coalesce($2, priority),
    weight    = coalesce($3, weight),
    enabled   = coalesce($4, enabled),
    headers   = coalesce($5, headers),
    context_window    = coalesce($6, context_window),
    max_output_tokens = coalesce($7, max_output_tokens),
    quirks            = coalesce($8, quirks),
    video_envelope    = coalesce($9, video_envelope),
    max_images        = coalesce($10, max_images),
    updated_at = now()
WHERE id = $11 AND model_id = $12
RETURNING id, model_id, provider_id, provider_model_id, priority, weight, enabled, headers,
          context_window, max_output_tokens, quirks, video_envelope, max_images
`

type UpdateRouteParams struct {
	ProviderModelID pgtype.Text
	Priority        pgtype.Int4
	Weight          pgtype.Int4
	Enabled         pgtype.Bool
	Headers         []byte
	ContextWindow   pgtype.Int4
	MaxOutputTokens pgtype.Int4
	Quirks          []byte
	VideoEnvelope   []byte
	MaxImages       pgtype.Int4
	ID              pgtype.UUID
	ModelID         pgtype.UUID
}

type UpdateRouteRow struct {
	ID              pgtype.UUID
	ModelID         pgtype.UUID
	ProviderID      pgtype.UUID
	ProviderModelID string
	Priority        int32
	Weight          int32
	Enabled         bool
	Headers         []byte
	ContextWindow   pgtype.Int4
	MaxOutputTokens pgtype.Int4
	Quirks          []byte
	VideoEnvelope   []byte
	MaxImages       pgtype.Int4
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (UpdateRouteRow, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ProviderModelID,
		arg.Priority,
		arg.Weight,
		arg.Enabled,
		arg.Headers,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Quirks,
		arg.VideoEnvelope,
		arg.MaxImages,
		arg.ID,
		arg.ModelID,
	)
	var i UpdateRouteRow
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.ProviderID,
		&i.ProviderModelID,
		&i.Priority,
		&i.Weight,
		&i.Enabled,
		&i.Headers,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Quirks,
		&i.VideoEnvelope,
		&i.MaxImages,
	)
	return i, err
}

const upsertCooldown = `-- name: UpsertCooldown :exec
INSERT INTO cooldowns (scope, ref_id, until, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (scope, ref_id)
    DO UPDATE SET until = excluded.until, reason = excluded.reason, updated_at = now()
`

type UpsertCooldownParams struct {
	Scope  string
	RefID  pgtype.UUID
	Until  pgtype.Timestamptz
	Reason string
}

func (q *Queries) UpsertCooldown(ctx context.Context, arg UpsertCooldownParams) error {
	_, err := q.db.Exec(ctx, upsertCooldown,
		arg.Scope,
		arg.RefID,
		arg.Until,
		arg.Reason,
	)
	return err
}

const upsertProviderDiscovery = `-- name: UpsertProviderDiscovery :exec

INSERT INTO provider_discoveries (provider_id, checked_at, ok, complete, status_code, message, models)
VALUES ($1, $2, $3, $4, $5::integer, $6, $7)
ON CONFLICT (provider_id) DO UPDATE SET
    checked_at  = excluded.checked_at,
    ok          = excluded.ok,
    complete    = excluded.complete,
    status_code = excluded.status_code,
    message     = excluded.message,
    models      = excluded.models
`

type UpsertProviderDiscoveryParams struct {
	ProviderID pgtype.UUID
	CheckedAt  pgtype.Timestamptz
	Ok         bool
	Complete   bool
	StatusCode pgtype.Int4
	Message    string
	Models     []byte
}

// ===== The last catalogue a provider reported =====
//
// One row per provider, replaced wholesale on each successful fetch. Asking an
// upstream what it serves costs real money, and the answer used to live only in
// a screen's local state -- so reloading the page meant paying again to learn
// the same thing, and the model side of the wiring editor had no way to know
// the name a given provider uses.
//
// Nothing on the data plane reads any of this. It is what the upstream said
// last time, with the time it said it, which is a different claim from what the
// upstream serves now.
func (q *Queries) UpsertProviderDiscovery(ctx context.Context, arg UpsertProviderDiscoveryParams) error {
	_, err := q.db.Exec(ctx, upsertProviderDiscovery,
		arg.ProviderID,
		arg.CheckedAt,
		arg.Ok,
		arg.Complete,
		arg.StatusCode,
		arg.Message,
		arg.Models,
	)
	return err
}
