// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestLog = `-- name: GetRequestLog :one
SELECT l.id::text AS id, l.request_id, l.created_at, l.model_slug, l.surface, l.status,
       l.http_status, l.error_code, l.stream, l.tokens_in, l.tokens_out,
       l.billed_units, l.billed_unit, l.charged_nano,
       l.duration_ms, l.api_key_id, l.end_user_id, l.route_attempts, l.ttft_ms,
       l.tokens_cached_read, l.tokens_cache_write, l.tokens_reasoning,
       l.usage_estimated, l.charged_currency, l.byok,
       COALESCE(p.slug, '')::text AS provider_slug
FROM usage_logs l
LEFT JOIN providers p ON p.id = l.provider_id
WHERE l.org_id = $1 AND l.request_id = $2
ORDER BY l.created_at DESC
LIMIT 1
`

type GetRequestLogParams struct {
	OrgID     pgtype.UUID
	RequestID string
}

type GetRequestLogRow struct {
	ID               string
	RequestID        string
	CreatedAt        pgtype.Timestamptz
	ModelSlug        string
	Surface          string
	Status           string
	HttpStatus       int32
	ErrorCode        string
	Stream           bool
	TokensIn         int32
	TokensOut        int32
	BilledUnits      pgtype.Int4
	BilledUnit       string
	ChargedNano      int64
	DurationMs       int32
	ApiKeyID         pgtype.UUID
	EndUserID        string
	RouteAttempts    int32
	TtftMs           int32
	TokensCachedRead int32
	TokensCacheWrite int32
	TokensReasoning  int32
	UsageEstimated   bool
	ChargedCurrency  string
	Byok             bool
	ProviderSlug     string
}

// Fetch a single log by request_id. request_id is not unique in this table (a
// UNIQUE constraint on a partitioned table must include the partition key);
// uniqueness is enforced by credit_holds instead. This returns the newest row,
// which is also the one you want to look at when a request was replayed.
func (q *Queries) GetRequestLog(ctx context.Context, arg GetRequestLogParams) (GetRequestLogRow, error) {
	row := q.db.QueryRow(ctx, getRequestLog, arg.OrgID, arg.RequestID)
	var i GetRequestLogRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.CreatedAt,
		&i.ModelSlug,
		&i.Surface,
		&i.Status,
		&i.HttpStatus,
		&i.ErrorCode,
		&i.Stream,
		&i.TokensIn,
		&i.TokensOut,
		&i.BilledUnits,
		&i.BilledUnit,
		&i.ChargedNano,
		&i.DurationMs,
		&i.ApiKeyID,
		&i.EndUserID,
		&i.RouteAttempts,
		&i.TtftMs,
		&i.TokensCachedRead,
		&i.TokensCacheWrite,
		&i.TokensReasoning,
		&i.UsageEstimated,
		&i.ChargedCurrency,
		&i.Byok,
		&i.ProviderSlug,
	)
	return i, err
}

const listRequestLogs = `-- name: ListRequestLogs :many

SELECT id::text AS id, request_id, created_at, model_slug, surface, status,
       http_status, error_code, stream, tokens_in, tokens_out, billed_units, billed_unit, charged_nano,
       duration_ms, api_key_id, end_user_id
FROM usage_logs
WHERE org_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
  AND ($4::uuid IS NULL OR api_key_id = $4::uuid)
  AND ($5::text IS NULL OR model_slug = $5::text)
  AND ($6::text IS NULL OR status = $6::text)
  AND ($7::text IS NULL OR end_user_id = $7::text)
  AND (
    $8::timestamptz IS NULL
    OR (created_at <= $8::timestamptz
        AND (created_at < $8::timestamptz
             OR id < $9::uuid))
  )
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListRequestLogsParams struct {
	OrgID     pgtype.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
	ApiKeyID  pgtype.UUID
	Model     pgtype.Text
	Status    pgtype.Text
	EndUserID pgtype.Text
	CursorTs  pgtype.Timestamptz
	CursorID  pgtype.UUID
	Lim       int32
}

type ListRequestLogsRow struct {
	ID          string
	RequestID   string
	CreatedAt   pgtype.Timestamptz
	ModelSlug   string
	Surface     string
	Status      string
	HttpStatus  int32
	ErrorCode   string
	Stream      bool
	TokensIn    int32
	TokensOut   int32
	BilledUnits pgtype.Int4
	BilledUnit  string
	ChargedNano int64
	DurationMs  int32
	ApiKeyID    pgtype.UUID
	EndUserID   string
}

// Per-request log listing for the console.
//
// Reads usage_logs, not the rollups: the log view wants individual request rows,
// and the rollups have already aggregated them away. Anything aggregate goes
// through the rollups instead; this file only filters and paginates.
// Keyset pagination, newest first.
//
// The cursor is the composite (created_at, id), not a bare timestamp: a bare
// timestamp drops every other row sharing the last row's instant, and under
// concurrent gateway writes several rows per millisecond is the normal case,
// not a theoretical one.
// The predicate is written as `created_at <=` boundary first (that form can use
// the index condition on usage_logs_org_idx), then a second term to discard the
// rows on the boundary that were already returned. Writing it as the row
// comparison (created_at, id) < (a, b) would instead lose the index -- there is
// no index in that column order.
func (q *Queries) ListRequestLogs(ctx context.Context, arg ListRequestLogsParams) ([]ListRequestLogsRow, error) {
	rows, err := q.db.Query(ctx, listRequestLogs,
		arg.OrgID,
		arg.FromTs,
		arg.ToTs,
		arg.ApiKeyID,
		arg.Model,
		arg.Status,
		arg.EndUserID,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestLogsRow
	for rows.Next() {
		var i ListRequestLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.CreatedAt,
			&i.ModelSlug,
			&i.Surface,
			&i.Status,
			&i.HttpStatus,
			&i.ErrorCode,
			&i.Stream,
			&i.TokensIn,
			&i.TokensOut,
			&i.BilledUnits,
			&i.BilledUnit,
			&i.ChargedNano,
			&i.DurationMs,
			&i.ApiKeyID,
			&i.EndUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
