// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gwdb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                 pgtype.UUID
	OrgID              pgtype.UUID
	Name               string
	Prefix             string
	KeyHash            string
	Scopes             []string
	AllowAllModels     bool
	AllowedModels      []string
	SpendLimitNano     pgtype.Int8
	SpendLimitInterval pgtype.Text
	RateLimitRpm       pgtype.Int4
	RateLimitTpm       pgtype.Int4
	Tags               []byte
	TotalSpentNano     int64
	Status             string
	LastUsedAt         pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ApiKeyDailySpend struct {
	ApiKeyID  pgtype.UUID
	Day       pgtype.Date
	SpentNano int64
}

type AuditLog struct {
	ID         pgtype.UUID
	ActorType  string
	ActorID    pgtype.UUID
	OrgID      pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Meta       []byte
	Ip         *netip.Addr
	RequestID  string
	CreatedAt  pgtype.Timestamptz
}

type AuditLogsDefault struct {
	ID         pgtype.UUID
	ActorType  string
	ActorID    pgtype.UUID
	OrgID      pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Meta       []byte
	Ip         *netip.Addr
	RequestID  string
	CreatedAt  pgtype.Timestamptz
}

type Cooldown struct {
	Scope     string
	RefID     pgtype.UUID
	Until     pgtype.Timestamptz
	Reason    string
	UpdatedAt pgtype.Timestamptz
}

// Requests held back because a price was missing. reserved_nano is what was set aside up front, not a final charge, so the generic retry worker must never settle these rows automatically
type GatewayPricingUnsettled struct {
	RequestID     string
	OrgID         pgtype.UUID
	ReservedNano  int64
	Currency      string
	Reason        string
	Attempts      int32
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	AbandonedAt   pgtype.Timestamptz
}

// Requests whose settlement failed to reach the database. A worker replays them; past the retry limit a row is abandoned and alerted for a human
type GatewayUnsettled struct {
	RequestID     string
	OrgID         pgtype.UUID
	ChargedNano   int64
	Currency      string
	Reason        string
	Attempts      int32
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	AbandonedAt   pgtype.Timestamptz
}

type GatewayUsageRollup struct {
	OrgID               pgtype.UUID
	BucketStart         pgtype.Timestamptz
	Granularity         string
	ApiKeyID            pgtype.UUID
	ModelSlug           string
	Requests            int64
	TokensIn            int64
	TokensOut           int64
	TokensCachedRead    int64
	TokensCacheWrite    int64
	TokensReasoning     int64
	TokensAudioIn       int64
	TokensAudioOut      int64
	TokensCacheWrite5m  int64
	TokensCacheWrite1h  int64
	ChargedNano         int64
	UpstreamCostUsdNano int64
	Errors              int64
	// Cumulative count of requests with duration_ms <= 100. All buckets zero while requests > 0 means the row carries no latency samples at all
	LatLe100      int64
	LatLe250      int64
	LatLe500      int64
	LatLe1000     int64
	LatLe2500     int64
	LatLe5000     int64
	LatLe10000    int64
	DurationMsSum int64
	// Total samples in the latency histogram (the +Inf bucket). Deliberately decoupled from requests: a row can have requests and no latency samples
	LatCount    int64
	ProviderID  pgtype.UUID
	LatLe30000  int64
	LatLe60000  int64
	LatLe120000 int64
}

type GatewayUsageRollupsDefault struct {
	OrgID               pgtype.UUID
	BucketStart         pgtype.Timestamptz
	Granularity         string
	ApiKeyID            pgtype.UUID
	ModelSlug           string
	Requests            int64
	TokensIn            int64
	TokensOut           int64
	TokensCachedRead    int64
	TokensCacheWrite    int64
	TokensReasoning     int64
	TokensAudioIn       int64
	TokensAudioOut      int64
	TokensCacheWrite5m  int64
	TokensCacheWrite1h  int64
	ChargedNano         int64
	UpstreamCostUsdNano int64
	Errors              int64
	// Cumulative count of requests with duration_ms <= 100. All buckets zero while requests > 0 means the row carries no latency samples at all
	LatLe100      int64
	LatLe250      int64
	LatLe500      int64
	LatLe1000     int64
	LatLe2500     int64
	LatLe5000     int64
	LatLe10000    int64
	DurationMsSum int64
	// Total samples in the latency histogram (the +Inf bucket). Deliberately decoupled from requests: a row can have requests and no latency samples
	LatCount    int64
	ProviderID  pgtype.UUID
	LatLe30000  int64
	LatLe60000  int64
	LatLe120000 int64
}

type IdempotencyKey struct {
	ID              pgtype.UUID
	Scope           string
	IdempotencyKey  string
	RequestHash     string
	Status          string
	ResponseStatus  pgtype.Int4
	ResponseHeaders []byte
	ResponseBody    []byte
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Model struct {
	ID              pgtype.UUID
	Slug            string
	DisplayName     string
	ContextWindow   int32
	MaxOutputTokens int32
	Capabilities    []byte
	Visibility      string
	Enabled         bool
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ModelPriceDimensionRate struct {
	ModelID        pgtype.UUID
	Bucket         string
	ServiceTier    string
	Variant        string
	MinInputTokens int32
	NanoPerMtok    int64
}

type ModelPriceToolRate struct {
	ModelID     pgtype.UUID
	Tool        string
	NanoPerCall int64
}

type ModelPricing struct {
	ModelID                       pgtype.UUID
	BillingMode                   string
	UpstreamInNanoPerMtok         pgtype.Int8
	UpstreamOutNanoPerMtok        pgtype.Int8
	UpstreamCacheReadNanoPerMtok  pgtype.Int8
	UpstreamCacheWriteNanoPerMtok pgtype.Int8
	Currency                      string
	MultiplierBps                 int32
	SourceName                    string
	SourceUrl                     string
	VerifiedAt                    pgtype.Timestamptz
	Provenance                    []byte
	Reason                        string
	UpdatedBy                     pgtype.UUID
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
}

type ModelPublishedEndpoint struct {
	ModelID  pgtype.UUID
	Endpoint string
	Protocol string
}

type ModelRoute struct {
	ID              pgtype.UUID
	ModelID         pgtype.UUID
	ProviderID      pgtype.UUID
	ProviderModelID string
	Priority        int32
	Weight          int32
	Enabled         bool
	Headers         []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ContextWindow   pgtype.Int4
	MaxOutputTokens pgtype.Int4
	Quirks          []byte
}

type ModelRouteProbe struct {
	RouteID    pgtype.UUID
	Endpoint   string
	Protocol   string
	ProbeMode  string
	Status     string
	Source     string
	CheckedAt  pgtype.Timestamptz
	LatencyMs  pgtype.Int4
	StatusCode pgtype.Int4
	Error      string
	UpdatedAt  pgtype.Timestamptz
}

type ModelTier struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	Description    string
	AllowAllModels bool
	IsDefault      bool
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ModelTierModel struct {
	TierID  pgtype.UUID
	ModelID pgtype.UUID
}

type Org struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	Kind      string
	Status    string
	Currency  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrgGatewaySetting struct {
	OrgID        pgtype.UUID
	TierID       pgtype.UUID
	RateLimitRpm pgtype.Int4
	RateLimitTpm pgtype.Int4
	UpdatedAt    pgtype.Timestamptz
}

type OrgPricingPlanAssignment struct {
	OrgID          pgtype.UUID
	PricingPlanID  pgtype.UUID
	InheritDefault bool
	Reason         string
	UpdatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

type OrgProviderKey struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	Vendor         string
	Name           string
	BaseUrl        pgtype.Text
	SecretEnc      []byte
	Status         string
	LastVerifiedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	SecretHint     string
	AllowFallback  bool
}

type PostingWatermark struct {
	Key       string
	Watermark pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PricingPlan struct {
	ID                   pgtype.UUID
	Slug                 string
	Name                 string
	Description          string
	Etag                 pgtype.UUID
	IsDefault            bool
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DefaultMultiplierBps int32
	Reason               string
	UpdatedBy            pgtype.UUID
}

type PricingPlanModelOverride struct {
	PricingPlanID pgtype.UUID
	ModelID       pgtype.UUID
	MultiplierBps int32
}

type Provider struct {
	ID                pgtype.UUID
	Slug              string
	Vendor            string
	Name              string
	BaseUrl           string
	Enabled           bool
	Headers           []byte
	Transport         []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AutoDisabled      bool
	CostMultiplierBps int32
	Protocols         []string
	RateLimitRpm      pgtype.Int4
	RateLimitTpm      pgtype.Int4
	MaxConcurrency    int32
}

type ProviderKey struct {
	ID             pgtype.UUID
	ProviderID     pgtype.UUID
	Name           string
	SecretEnc      []byte
	Status         string
	LastError      string
	CreatedAt      pgtype.Timestamptz
	SecretHint     string
	LastVerifiedAt pgtype.Timestamptz
}

type ResourceAffinity struct {
	OrgID            pgtype.UUID
	Protocol         string
	ResourceType     string
	UpstreamID       string
	ModelID          pgtype.UUID
	RouteID          pgtype.UUID
	ProviderID       pgtype.UUID
	ProviderKeyID    pgtype.UUID
	OrgProviderKeyID pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Setting struct {
	Key        string
	Value      []byte
	SecretEnc  []byte
	SecretHint pgtype.Text
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  string
}

type StaffSession struct {
	ID          pgtype.UUID
	StaffUserID pgtype.UUID
	TokenHash   string
	Ip          *netip.Addr
	UserAgent   string
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type StaffUser struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UsageLog struct {
	ID                  pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	OrgID               pgtype.UUID
	ApiKeyID            pgtype.UUID
	RequestID           string
	Surface             string
	ModelSlug           string
	ProviderID          pgtype.UUID
	ProviderKeyID       pgtype.UUID
	OrgProviderKeyID    pgtype.UUID
	RouteID             pgtype.UUID
	Byok                bool
	RouteAttempts       int32
	Attempts            []byte
	Stream              bool
	Status              string
	ErrorCode           string
	HttpStatus          int32
	TokensIn            int32
	TokensOut           int32
	TokensCachedRead    int32
	TokensReasoning     int32
	UsageEstimated      bool
	UpstreamCostUsdNano int64
	ChargedNano         int64
	ChargedCurrency     string
	FxRate              pgtype.Numeric
	HoldID              pgtype.UUID
	EndUserID           string
	TtftMs              int32
	DurationMs          int32
	TokensCacheWrite    int32
	ToolCalls           []byte
	ServiceTier         string
	TokensAudioIn       pgtype.Int4
	TokensAudioOut      pgtype.Int4
	TokensCacheWrite5m  pgtype.Int4
	TokensCacheWrite1h  pgtype.Int4
	PricingSnapshot     []byte
}

type UsageLogsDefault struct {
	ID                  pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	OrgID               pgtype.UUID
	ApiKeyID            pgtype.UUID
	RequestID           string
	Surface             string
	ModelSlug           string
	ProviderID          pgtype.UUID
	ProviderKeyID       pgtype.UUID
	OrgProviderKeyID    pgtype.UUID
	RouteID             pgtype.UUID
	Byok                bool
	RouteAttempts       int32
	Attempts            []byte
	Stream              bool
	Status              string
	ErrorCode           string
	HttpStatus          int32
	TokensIn            int32
	TokensOut           int32
	TokensCachedRead    int32
	TokensReasoning     int32
	UsageEstimated      bool
	UpstreamCostUsdNano int64
	ChargedNano         int64
	ChargedCurrency     string
	FxRate              pgtype.Numeric
	HoldID              pgtype.UUID
	EndUserID           string
	TtftMs              int32
	DurationMs          int32
	TokensCacheWrite    int32
	ToolCalls           []byte
	ServiceTier         string
	TokensAudioIn       pgtype.Int4
	TokensAudioOut      pgtype.Int4
	TokensCacheWrite5m  pgtype.Int4
	TokensCacheWrite1h  pgtype.Int4
	PricingSnapshot     []byte
}
