// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPricingPlanModelOverrides = `-- name: ClearPricingPlanModelOverrides :execrows
DELETE FROM pricing_plan_model_overrides WHERE pricing_plan_id = $1
`

// Used for whole-set replacement: the overrides are a set, so per-field dirty
// checking does not apply to them.
func (q *Queries) ClearPricingPlanModelOverrides(ctx context.Context, pricingPlanID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearPricingPlanModelOverrides, pricingPlanID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPricingPlan = `-- name: CreatePricingPlan :one
INSERT INTO pricing_plans (slug, name, description, default_multiplier_bps)
VALUES ($1, $2, $3, $4) RETURNING id, slug, name, description, etag, is_default, status, created_at, updated_at, default_multiplier_bps, reason, updated_by
`

type CreatePricingPlanParams struct {
	Slug                 string
	Name                 string
	Description          string
	DefaultMultiplierBps int32
}

func (q *Queries) CreatePricingPlan(ctx context.Context, arg CreatePricingPlanParams) (PricingPlan, error) {
	row := q.db.QueryRow(ctx, createPricingPlan,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DefaultMultiplierBps,
	)
	var i PricingPlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Etag,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultMultiplierBps,
		&i.Reason,
		&i.UpdatedBy,
	)
	return i, err
}

const deletePricingPlan = `-- name: DeletePricingPlan :execrows
DELETE FROM pricing_plans p
WHERE p.id = $1 AND p.etag = $2 AND NOT p.is_default
  AND NOT EXISTS (SELECT 1 FROM org_pricing_plan_assignments a
                  WHERE a.pricing_plan_id = p.id AND NOT a.inherit_default)
`

type DeletePricingPlanParams struct {
	ID   pgtype.UUID
	Etag pgtype.UUID
}

func (q *Queries) DeletePricingPlan(ctx context.Context, arg DeletePricingPlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePricingPlan, arg.ID, arg.Etag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEffectivePricingPlanForOrg = `-- name: GetEffectivePricingPlanForOrg :one

WITH selected AS (
    SELECT p.id, p.slug, p.name, p.description, p.etag, p.is_default, p.status, p.created_at, p.updated_at, p.default_multiplier_bps, p.reason, p.updated_by
    FROM org_pricing_plan_assignments a
    JOIN pricing_plans p ON p.id = a.pricing_plan_id AND p.status = 'active'
    WHERE a.org_id = $1 AND NOT a.inherit_default
    UNION ALL
    SELECT p.id, p.slug, p.name, p.description, p.etag, p.is_default, p.status, p.created_at, p.updated_at, p.default_multiplier_bps, p.reason, p.updated_by FROM pricing_plans p
    WHERE p.is_default AND p.status = 'active'
      AND NOT EXISTS (SELECT 1 FROM org_pricing_plan_assignments a
                      WHERE a.org_id = $1 AND NOT a.inherit_default)
    LIMIT 1
)
SELECT s.id AS pricing_plan_id, s.slug, s.name, s.is_default, s.default_multiplier_bps
FROM selected s
`

type GetEffectivePricingPlanForOrgRow struct {
	PricingPlanID        pgtype.UUID
	Slug                 string
	Name                 string
	IsDefault            bool
	DefaultMultiplierBps int32
}

// ===== Organization assignment (one row per org) =====
func (q *Queries) GetEffectivePricingPlanForOrg(ctx context.Context, orgID pgtype.UUID) (GetEffectivePricingPlanForOrgRow, error) {
	row := q.db.QueryRow(ctx, getEffectivePricingPlanForOrg, orgID)
	var i GetEffectivePricingPlanForOrgRow
	err := row.Scan(
		&i.PricingPlanID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.DefaultMultiplierBps,
	)
	return i, err
}

const getModelPricing = `-- name: GetModelPricing :one

SELECT model_id, billing_mode, pricing_family, upstream_in_nano_per_mtok, upstream_out_nano_per_mtok, upstream_cache_read_nano_per_mtok, upstream_cache_write_nano_per_mtok, currency, multiplier_bps, source_name, source_url, verified_at, provenance, reason, updated_by, created_at, updated_at FROM model_pricing WHERE model_id = $1
`

// ===== Model price (one row per model) =====
func (q *Queries) GetModelPricing(ctx context.Context, modelID pgtype.UUID) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, getModelPricing, modelID)
	var i ModelPricing
	err := row.Scan(
		&i.ModelID,
		&i.BillingMode,
		&i.PricingFamily,
		&i.UpstreamInNanoPerMtok,
		&i.UpstreamOutNanoPerMtok,
		&i.UpstreamCacheReadNanoPerMtok,
		&i.UpstreamCacheWriteNanoPerMtok,
		&i.Currency,
		&i.MultiplierBps,
		&i.SourceName,
		&i.SourceUrl,
		&i.VerifiedAt,
		&i.Provenance,
		&i.Reason,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPricingPlan = `-- name: GetPricingPlan :one
SELECT id, slug, name, description, etag, is_default, status, created_at, updated_at, default_multiplier_bps, reason, updated_by FROM pricing_plans WHERE id = $1
`

func (q *Queries) GetPricingPlan(ctx context.Context, id pgtype.UUID) (PricingPlan, error) {
	row := q.db.QueryRow(ctx, getPricingPlan, id)
	var i PricingPlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Etag,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultMultiplierBps,
		&i.Reason,
		&i.UpdatedBy,
	)
	return i, err
}

const getRouteCostMultiplier = `-- name: GetRouteCostMultiplier :one
SELECT p.cost_multiplier_bps
FROM model_routes r
JOIN providers p ON p.id = r.provider_id
WHERE r.id = $1
`

// Cost is a single scalar: cost = list price x provider.cost_multiplier_bps.
// Usage snapshots the scalar per request, so changing it later does not distort
// historical margin.
func (q *Queries) GetRouteCostMultiplier(ctx context.Context, routeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getRouteCostMultiplier, routeID)
	var cost_multiplier_bps int32
	err := row.Scan(&cost_multiplier_bps)
	return cost_multiplier_bps, err
}

const listModelPriceDimensionRates = `-- name: ListModelPriceDimensionRates :many

SELECT model_id, bucket, service_tier, variant, min_input_tokens, nano_per_mtok FROM model_price_dimension_rates
WHERE model_id = $1 ORDER BY bucket, service_tier, variant, min_input_tokens
`

// ===== Advanced pricing dimensions =====
// Ordering carries min_input_tokens so that the bands of one bucket arrive in a
// fixed order rather than whatever the heap returns.
func (q *Queries) ListModelPriceDimensionRates(ctx context.Context, modelID pgtype.UUID) ([]ModelPriceDimensionRate, error) {
	rows, err := q.db.Query(ctx, listModelPriceDimensionRates, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPriceDimensionRate
	for rows.Next() {
		var i ModelPriceDimensionRate
		if err := rows.Scan(
			&i.ModelID,
			&i.Bucket,
			&i.ServiceTier,
			&i.Variant,
			&i.MinInputTokens,
			&i.NanoPerMtok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPriceToolRates = `-- name: ListModelPriceToolRates :many
SELECT model_id, tool, nano_per_call FROM model_price_tool_rates WHERE model_id = $1 ORDER BY tool
`

func (q *Queries) ListModelPriceToolRates(ctx context.Context, modelID pgtype.UUID) ([]ModelPriceToolRate, error) {
	rows, err := q.db.Query(ctx, listModelPriceToolRates, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPriceToolRate
	for rows.Next() {
		var i ModelPriceToolRate
		if err := rows.Scan(&i.ModelID, &i.Tool, &i.NanoPerCall); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPriceUnitRates = `-- name: ListModelPriceUnitRates :many
SELECT model_id, unit, resolution, audio, variant, service_tier, nano_per_unit FROM model_price_unit_rates
WHERE model_id = $1 ORDER BY unit, resolution, audio, service_tier, variant
`

// The per-unit family (ADR-0220). Ordered so a rate card arrives the same way
// every time, which is what makes a stored price snapshot comparable.
func (q *Queries) ListModelPriceUnitRates(ctx context.Context, modelID pgtype.UUID) ([]ModelPriceUnitRate, error) {
	rows, err := q.db.Query(ctx, listModelPriceUnitRates, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPriceUnitRate
	for rows.Next() {
		var i ModelPriceUnitRate
		if err := rows.Scan(
			&i.ModelID,
			&i.Unit,
			&i.Resolution,
			&i.Audio,
			&i.Variant,
			&i.ServiceTier,
			&i.NanoPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsForPriceImport = `-- name: ListModelsForPriceImport :many

SELECT m.id AS model_id, m.slug AS model_slug,
       (mp.model_id IS NOT NULL)::boolean AS priced,
       mp.verified_at,
       coalesce(mp.billing_mode, '')::text        AS billing_mode,
       coalesce(mp.multiplier_bps, 10000)::integer AS multiplier_bps,
       mp.upstream_in_nano_per_mtok, mp.upstream_out_nano_per_mtok,
       mp.upstream_cache_read_nano_per_mtok, mp.upstream_cache_write_nano_per_mtok,
       -- The image-input dimension rate, when one is configured. It is read
       -- for the same reason as the four base rates: "the reference already
       -- says what is stored" is what makes the import idempotent, and a
       -- comparison that ignores this rate would call a model unchanged while
       -- the dataset has an image price the model does not carry -- so a
       -- re-run would never put it there.
       --
       -- Joined rather than read as a scalar subquery so that its nullability
       -- is visible: a model with no image rate has no row here, and generating
       -- these columns as NOT NULL would panic on scan for every model that has
       -- none -- which is nearly all of them. Both sides are read, because the
       -- dataset states both and a model whose output rate is already stored
       -- must not be reported as unchanged forever.
       --
       -- The join is pinned to the plain rate. The band, tier and variant axes
       -- belong to the operator, and the import neither writes nor compares
       -- them; the primary key makes that at most one row.
       dr.nano_per_mtok AS upstream_image_in_nano_per_mtok,
       dro.nano_per_mtok AS upstream_image_out_nano_per_mtok
FROM models m
LEFT JOIN model_pricing mp ON mp.model_id = m.id
LEFT JOIN model_price_dimension_rates dr
       ON dr.model_id = mp.model_id
      AND dr.bucket = 'image_in'
      AND dr.service_tier = 'standard'
      AND dr.variant = ''
      AND dr.min_input_tokens = 0
LEFT JOIN model_price_dimension_rates dro
       ON dro.model_id = mp.model_id
      AND dro.bucket = 'image_out'
      AND dro.service_tier = 'standard'
      AND dro.variant = ''
      AND dro.min_input_tokens = 0
ORDER BY m.slug
`

type ListModelsForPriceImportRow struct {
	ModelID                       pgtype.UUID
	ModelSlug                     string
	Priced                        bool
	VerifiedAt                    pgtype.Timestamptz
	BillingMode                   string
	MultiplierBps                 int32
	UpstreamInNanoPerMtok         pgtype.Int8
	UpstreamOutNanoPerMtok        pgtype.Int8
	UpstreamCacheReadNanoPerMtok  pgtype.Int8
	UpstreamCacheWriteNanoPerMtok pgtype.Int8
	UpstreamImageInNanoPerMtok    pgtype.Int8
	UpstreamImageOutNanoPerMtok   pgtype.Int8
}

// ===== Reference-price import =====
//
// The two reads below serve the operator-triggered import that fills empty
// price rows in from a bundled reference dataset. They are reads only: the
// write goes through the same path as the admin editor, so the completeness
// rule, the risk assessment and the cache invalidation cannot be bypassed by
// coming in through a different door.
// Every model, with the state of its price row.
//
// The import decides three things per model -- is there a price at all, has a
// human checked it, and does the reference rate differ from what is stored --
// and all three are answered here, so the decision is taken against one
// consistent view of the catalogue rather than a read per model.
//
// The explicit casts are not decoration: through a LEFT JOIN these columns can
// all be null, and generating the NOT NULL ones as non-nullable would panic on
// scan for every model that has no price yet, which is precisely the set this
// import exists for.
func (q *Queries) ListModelsForPriceImport(ctx context.Context) ([]ListModelsForPriceImportRow, error) {
	rows, err := q.db.Query(ctx, listModelsForPriceImport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsForPriceImportRow
	for rows.Next() {
		var i ListModelsForPriceImportRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ModelSlug,
			&i.Priced,
			&i.VerifiedAt,
			&i.BillingMode,
			&i.MultiplierBps,
			&i.UpstreamInNanoPerMtok,
			&i.UpstreamOutNanoPerMtok,
			&i.UpstreamCacheReadNanoPerMtok,
			&i.UpstreamCacheWriteNanoPerMtok,
			&i.UpstreamImageInNanoPerMtok,
			&i.UpstreamImageOutNanoPerMtok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingPlanModelOverrides = `-- name: ListPricingPlanModelOverrides :many
SELECT o.pricing_plan_id, o.model_id, o.multiplier_bps, m.slug AS model_slug
FROM pricing_plan_model_overrides o
JOIN models m ON m.id = o.model_id
WHERE o.pricing_plan_id = $1
ORDER BY m.slug
LIMIT 500
`

type ListPricingPlanModelOverridesRow struct {
	PricingPlanID pgtype.UUID
	ModelID       pgtype.UUID
	MultiplierBps int32
	ModelSlug     string
}

// 有界而不是分页，且这是**整集编辑面的前提**（ADR-0189）：编辑面把这份清单当作
// 完整的「已配置集」，缺一行，那一行在界面上就不存在——读者看到的不是「没勾」，
// 是「没有这一项」，而保存时它会被算作未勾选。上界跟着目录走（同为 500）：
// 一个方案覆盖价的条数不可能超过目录本身。
func (q *Queries) ListPricingPlanModelOverrides(ctx context.Context, pricingPlanID pgtype.UUID) ([]ListPricingPlanModelOverridesRow, error) {
	rows, err := q.db.Query(ctx, listPricingPlanModelOverrides, pricingPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingPlanModelOverridesRow
	for rows.Next() {
		var i ListPricingPlanModelOverridesRow
		if err := rows.Scan(
			&i.PricingPlanID,
			&i.ModelID,
			&i.MultiplierBps,
			&i.ModelSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingPlans = `-- name: ListPricingPlans :many
SELECT p.id, p.slug, p.name, p.description, p.etag, p.is_default, p.status, p.created_at, p.updated_at, p.default_multiplier_bps, p.reason, p.updated_by,
       CASE WHEN p.is_default THEN
           (SELECT count(*) FROM orgs o
             WHERE o.status <> 'deleted'
               AND NOT EXISTS (
                   SELECT 1 FROM org_pricing_plan_assignments a
                    WHERE a.org_id = o.id AND NOT a.inherit_default
                      AND a.pricing_plan_id <> p.id
               ))
       ELSE
           (SELECT count(*) FROM org_pricing_plan_assignments a
              JOIN orgs o ON o.id = a.org_id AND o.status <> 'deleted'
             WHERE a.pricing_plan_id = p.id AND NOT a.inherit_default)
       END::bigint AS org_count
FROM pricing_plans p
WHERE (NOT $1::boolean OR p.id = $2)
  AND (NOT $3::boolean
       OR p.is_default < $4::boolean
       OR (p.is_default = $4::boolean AND p.slug > $5::text))
  AND ($6::text = '' OR p.slug ILIKE '%' || $6::text || '%'
       OR p.name ILIKE '%' || $6::text || '%')
ORDER BY p.is_default DESC, p.slug
LIMIT $7
`

type ListPricingPlansParams struct {
	HasID           bool
	OnlyID          pgtype.UUID
	HasCursor       bool
	CursorIsDefault bool
	CursorSlug      string
	Search          string
	Lim             int32
}

type ListPricingPlansRow struct {
	ID                   pgtype.UUID
	Slug                 string
	Name                 string
	Description          string
	Etag                 pgtype.UUID
	IsDefault            bool
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DefaultMultiplierBps int32
	Reason               string
	UpdatedBy            pgtype.UUID
	OrgCount             int64
}

// The two branches of org_count count different things on purpose: the default
// plan must also include orgs with no explicit assignment, because those orgs
// really are on it.
// 键是 (is_default, slug)：默认档／默认方案永远排在最前，其余按 slug。
// 混合方向的元组比较不能直接写 `>`——is_default 降序意味着「之后」是它更小，
// 或相等而 slug 更大。slug 唯一，所以两分量已是全序，不需要 id 兜底。
// @only_id lets the single-plan read reuse this query instead of a second one:
// org_count is an aggregate only computed here, and two queries that disagree
// about what a plan is would be two answers to the same question.
func (q *Queries) ListPricingPlans(ctx context.Context, arg ListPricingPlansParams) ([]ListPricingPlansRow, error) {
	rows, err := q.db.Query(ctx, listPricingPlans,
		arg.HasID,
		arg.OnlyID,
		arg.HasCursor,
		arg.CursorIsDefault,
		arg.CursorSlug,
		arg.Search,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingPlansRow
	for rows.Next() {
		var i ListPricingPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Etag,
			&i.IsDefault,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultMultiplierBps,
			&i.Reason,
			&i.UpdatedBy,
			&i.OrgCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsableRoutesForPriceImport = `-- name: ListUsableRoutesForPriceImport :many
SELECT r.model_id, r.provider_model_id, p.slug AS provider_slug, p.vendor AS provider_vendor, p.base_url
FROM model_routes r
JOIN providers p ON p.id = r.provider_id
WHERE r.enabled AND p.enabled
ORDER BY r.model_id, r.priority, p.slug
`

type ListUsableRoutesForPriceImportRow struct {
	ModelID         pgtype.UUID
	ProviderModelID string
	ProviderSlug    string
	ProviderVendor  string
	BaseUrl         string
}

// Where the import reads an upstream model id from: enabled routes on enabled
// providers, the same set the catalogue calls usable.
//
// Restricted to that set on purpose. A model nothing can serve stays out of the
// catalogue whatever its price says, so pricing it would produce a row that
// changes nothing an operator can see; and a disabled route pointing at a
// different upstream name is a reading that would only manufacture
// disagreements between routes.
func (q *Queries) ListUsableRoutesForPriceImport(ctx context.Context) ([]ListUsableRoutesForPriceImportRow, error) {
	rows, err := q.db.Query(ctx, listUsableRoutesForPriceImport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsableRoutesForPriceImportRow
	for rows.Next() {
		var i ListUsableRoutesForPriceImportRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ProviderModelID,
			&i.ProviderSlug,
			&i.ProviderVendor,
			&i.BaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUsagePricing = `-- name: ResolveUsagePricing :one


WITH selected_plan AS (
    SELECT p.id AS pricing_plan_id
    FROM org_pricing_plan_assignments a
    JOIN pricing_plans p ON p.id = a.pricing_plan_id AND p.status = 'active'
    WHERE a.org_id = $2 AND NOT a.inherit_default
    UNION ALL
    -- With no explicit assignment (or one that explicitly says "follow the
    -- default"), inherit the deployment's default plan.
    SELECT p.id
    FROM pricing_plans p
    WHERE p.is_default AND p.status = 'active'
      AND NOT EXISTS (
          SELECT 1 FROM org_pricing_plan_assignments a
          WHERE a.org_id = $2 AND NOT a.inherit_default
      )
    LIMIT 1
)
SELECT m.id AS model_id, m.slug AS model_slug,
       mp.billing_mode,
       mp.upstream_in_nano_per_mtok, mp.upstream_out_nano_per_mtok,
       mp.upstream_cache_read_nano_per_mtok, mp.upstream_cache_write_nano_per_mtok,
       mp.multiplier_bps AS model_multiplier_bps,
       sp.pricing_plan_id,
       COALESCE(po.multiplier_bps, pl.default_multiplier_bps)::integer AS plan_multiplier_bps,
       (po.multiplier_bps IS NOT NULL)::boolean AS plan_model_override
FROM models m
JOIN model_pricing mp ON mp.model_id = m.id
JOIN selected_plan sp ON true
JOIN pricing_plans pl ON pl.id = sp.pricing_plan_id
LEFT JOIN pricing_plan_model_overrides po
    ON po.pricing_plan_id = sp.pricing_plan_id AND po.model_id = m.id
WHERE m.slug = $1 AND m.enabled
`

type ResolveUsagePricingParams struct {
	ModelSlug string
	OrgID     pgtype.UUID
}

type ResolveUsagePricingRow struct {
	ModelID                       pgtype.UUID
	ModelSlug                     string
	BillingMode                   string
	UpstreamInNanoPerMtok         pgtype.Int8
	UpstreamOutNanoPerMtok        pgtype.Int8
	UpstreamCacheReadNanoPerMtok  pgtype.Int8
	UpstreamCacheWriteNanoPerMtok pgtype.Int8
	ModelMultiplierBps            int32
	PricingPlanID                 pgtype.UUID
	PlanMultiplierBps             int32
	PlanModelOverride             bool
}

// Reads and writes for usage-based pricing. The truth about a price is its
// current value: one row per model, one row per plan. There is no version
// state machine and no publish workflow.
//
// Two properties hold instead:
//  1. a price is pinned when the request starts -- by the pricing snapshot
//     transaction in the request pipeline, not by a version id;
//  2. recomputing history reads only the pricing snapshot stored on the usage
//     log row, never a join against current configuration.
//
// ===== Resolution at request start =====
// One read for everything: the model's current price, the plan in effect for
// this org, and any per-model override that plan carries.
// Runs inside the pipeline's snapshot transaction -- reading once inside the
// transaction *is* the pin.
func (q *Queries) ResolveUsagePricing(ctx context.Context, arg ResolveUsagePricingParams) (ResolveUsagePricingRow, error) {
	row := q.db.QueryRow(ctx, resolveUsagePricing, arg.ModelSlug, arg.OrgID)
	var i ResolveUsagePricingRow
	err := row.Scan(
		&i.ModelID,
		&i.ModelSlug,
		&i.BillingMode,
		&i.UpstreamInNanoPerMtok,
		&i.UpstreamOutNanoPerMtok,
		&i.UpstreamCacheReadNanoPerMtok,
		&i.UpstreamCacheWriteNanoPerMtok,
		&i.ModelMultiplierBps,
		&i.PricingPlanID,
		&i.PlanMultiplierBps,
		&i.PlanModelOverride,
	)
	return i, err
}

const updatePricingPlan = `-- name: UpdatePricingPlan :one
UPDATE pricing_plans SET name = $1, description = $2,
       status = $3,
       default_multiplier_bps = $4,
       reason = $5, updated_by = $6,
       etag = uuidv7()
WHERE id = $7 AND etag = $8 RETURNING id, slug, name, description, etag, is_default, status, created_at, updated_at, default_multiplier_bps, reason, updated_by
`

type UpdatePricingPlanParams struct {
	Name                 string
	Description          string
	Status               string
	DefaultMultiplierBps int32
	Reason               string
	UpdatedBy            pgtype.UUID
	ID                   pgtype.UUID
	Etag                 pgtype.UUID
}

// Saving takes effect immediately. The ETag is still here: it guards against
// concurrent overwrite, which has nothing to do with versioning.
func (q *Queries) UpdatePricingPlan(ctx context.Context, arg UpdatePricingPlanParams) (PricingPlan, error) {
	row := q.db.QueryRow(ctx, updatePricingPlan,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DefaultMultiplierBps,
		arg.Reason,
		arg.UpdatedBy,
		arg.ID,
		arg.Etag,
	)
	var i PricingPlan
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Etag,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultMultiplierBps,
		&i.Reason,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertModelPriceDimensionRate = `-- name: UpsertModelPriceDimensionRate :one
INSERT INTO model_price_dimension_rates (
    model_id, bucket, service_tier, variant, min_input_tokens, nano_per_mtok
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (model_id, bucket, service_tier, variant, min_input_tokens)
DO UPDATE SET nano_per_mtok = EXCLUDED.nano_per_mtok
RETURNING model_id, bucket, service_tier, variant, min_input_tokens, nano_per_mtok
`

type UpsertModelPriceDimensionRateParams struct {
	ModelID        pgtype.UUID
	Bucket         string
	ServiceTier    string
	Variant        string
	MinInputTokens int32
	NanoPerMtok    int64
}

// The conflict target has to carry min_input_tokens too: it is part of the
// primary key, and leaving it out would collapse two context bands of the same
// bucket onto one row.
func (q *Queries) UpsertModelPriceDimensionRate(ctx context.Context, arg UpsertModelPriceDimensionRateParams) (ModelPriceDimensionRate, error) {
	row := q.db.QueryRow(ctx, upsertModelPriceDimensionRate,
		arg.ModelID,
		arg.Bucket,
		arg.ServiceTier,
		arg.Variant,
		arg.MinInputTokens,
		arg.NanoPerMtok,
	)
	var i ModelPriceDimensionRate
	err := row.Scan(
		&i.ModelID,
		&i.Bucket,
		&i.ServiceTier,
		&i.Variant,
		&i.MinInputTokens,
		&i.NanoPerMtok,
	)
	return i, err
}

const upsertModelPriceToolRate = `-- name: UpsertModelPriceToolRate :one
INSERT INTO model_price_tool_rates (model_id, tool, nano_per_call)
VALUES ($1, $2, $3)
ON CONFLICT (model_id, tool) DO UPDATE SET nano_per_call = EXCLUDED.nano_per_call
RETURNING model_id, tool, nano_per_call
`

type UpsertModelPriceToolRateParams struct {
	ModelID     pgtype.UUID
	Tool        string
	NanoPerCall int64
}

func (q *Queries) UpsertModelPriceToolRate(ctx context.Context, arg UpsertModelPriceToolRateParams) (ModelPriceToolRate, error) {
	row := q.db.QueryRow(ctx, upsertModelPriceToolRate, arg.ModelID, arg.Tool, arg.NanoPerCall)
	var i ModelPriceToolRate
	err := row.Scan(&i.ModelID, &i.Tool, &i.NanoPerCall)
	return i, err
}

const upsertModelPriceUnitRate = `-- name: UpsertModelPriceUnitRate :one
INSERT INTO model_price_unit_rates (
    model_id, unit, resolution, audio, variant, service_tier, nano_per_unit
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (model_id, unit, resolution, audio, variant, service_tier)
DO UPDATE SET nano_per_unit = EXCLUDED.nano_per_unit
RETURNING model_id, unit, resolution, audio, variant, service_tier, nano_per_unit
`

type UpsertModelPriceUnitRateParams struct {
	ModelID     pgtype.UUID
	Unit        string
	Resolution  string
	Audio       string
	Variant     string
	ServiceTier string
	NanoPerUnit int64
}

// The conflict target is the whole key: leaving an axis out would collapse two
// distinct rates onto one row.
func (q *Queries) UpsertModelPriceUnitRate(ctx context.Context, arg UpsertModelPriceUnitRateParams) (ModelPriceUnitRate, error) {
	row := q.db.QueryRow(ctx, upsertModelPriceUnitRate,
		arg.ModelID,
		arg.Unit,
		arg.Resolution,
		arg.Audio,
		arg.Variant,
		arg.ServiceTier,
		arg.NanoPerUnit,
	)
	var i ModelPriceUnitRate
	err := row.Scan(
		&i.ModelID,
		&i.Unit,
		&i.Resolution,
		&i.Audio,
		&i.Variant,
		&i.ServiceTier,
		&i.NanoPerUnit,
	)
	return i, err
}

const upsertModelPricing = `-- name: UpsertModelPricing :one
INSERT INTO model_pricing (
    model_id, billing_mode, pricing_family,
    upstream_in_nano_per_mtok, upstream_out_nano_per_mtok,
    upstream_cache_read_nano_per_mtok, upstream_cache_write_nano_per_mtok,
    multiplier_bps, source_name, source_url, verified_at, provenance, reason, updated_by
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14
)
ON CONFLICT (model_id) DO UPDATE SET
    billing_mode = EXCLUDED.billing_mode,
    pricing_family = EXCLUDED.pricing_family,
    upstream_in_nano_per_mtok = EXCLUDED.upstream_in_nano_per_mtok,
    upstream_out_nano_per_mtok = EXCLUDED.upstream_out_nano_per_mtok,
    upstream_cache_read_nano_per_mtok = EXCLUDED.upstream_cache_read_nano_per_mtok,
    upstream_cache_write_nano_per_mtok = EXCLUDED.upstream_cache_write_nano_per_mtok,
    multiplier_bps = EXCLUDED.multiplier_bps,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    verified_at = EXCLUDED.verified_at,
    provenance = EXCLUDED.provenance,
    reason = EXCLUDED.reason,
    updated_by = EXCLUDED.updated_by
RETURNING model_id, billing_mode, pricing_family, upstream_in_nano_per_mtok, upstream_out_nano_per_mtok, upstream_cache_read_nano_per_mtok, upstream_cache_write_nano_per_mtok, currency, multiplier_bps, source_name, source_url, verified_at, provenance, reason, updated_by, created_at, updated_at
`

type UpsertModelPricingParams struct {
	ModelID            pgtype.UUID
	BillingMode        string
	PricingFamily      string
	UpstreamIn         pgtype.Int8
	UpstreamOut        pgtype.Int8
	UpstreamCacheRead  pgtype.Int8
	UpstreamCacheWrite pgtype.Int8
	MultiplierBps      int32
	SourceName         string
	SourceUrl          string
	VerifiedAt         pgtype.Timestamptz
	Provenance         []byte
	Reason             string
	UpdatedBy          pgtype.UUID
}

// Saving takes effect immediately. `reason` is required, enforced by the write
// endpoint, and written to the audit log: "who changed this, when, and why" is
// the audit log's job, not a publish workflow's.
func (q *Queries) UpsertModelPricing(ctx context.Context, arg UpsertModelPricingParams) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, upsertModelPricing,
		arg.ModelID,
		arg.BillingMode,
		arg.PricingFamily,
		arg.UpstreamIn,
		arg.UpstreamOut,
		arg.UpstreamCacheRead,
		arg.UpstreamCacheWrite,
		arg.MultiplierBps,
		arg.SourceName,
		arg.SourceUrl,
		arg.VerifiedAt,
		arg.Provenance,
		arg.Reason,
		arg.UpdatedBy,
	)
	var i ModelPricing
	err := row.Scan(
		&i.ModelID,
		&i.BillingMode,
		&i.PricingFamily,
		&i.UpstreamInNanoPerMtok,
		&i.UpstreamOutNanoPerMtok,
		&i.UpstreamCacheReadNanoPerMtok,
		&i.UpstreamCacheWriteNanoPerMtok,
		&i.Currency,
		&i.MultiplierBps,
		&i.SourceName,
		&i.SourceUrl,
		&i.VerifiedAt,
		&i.Provenance,
		&i.Reason,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgPricingPlanAssignment = `-- name: UpsertOrgPricingPlanAssignment :one
INSERT INTO org_pricing_plan_assignments (
    org_id, pricing_plan_id, inherit_default, reason, updated_by
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id) DO UPDATE SET
    pricing_plan_id = EXCLUDED.pricing_plan_id,
    inherit_default = EXCLUDED.inherit_default,
    reason = EXCLUDED.reason,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING org_id, pricing_plan_id, inherit_default, reason, updated_by, updated_at
`

type UpsertOrgPricingPlanAssignmentParams struct {
	OrgID          pgtype.UUID
	PricingPlanID  pgtype.UUID
	InheritDefault bool
	Reason         string
	UpdatedBy      pgtype.UUID
}

// One row per org. `inherit_default = true` explicitly declares "follow the
// default plan": semantically the same as having no row, but it keeps a reason
// and an audit subject.
func (q *Queries) UpsertOrgPricingPlanAssignment(ctx context.Context, arg UpsertOrgPricingPlanAssignmentParams) (OrgPricingPlanAssignment, error) {
	row := q.db.QueryRow(ctx, upsertOrgPricingPlanAssignment,
		arg.OrgID,
		arg.PricingPlanID,
		arg.InheritDefault,
		arg.Reason,
		arg.UpdatedBy,
	)
	var i OrgPricingPlanAssignment
	err := row.Scan(
		&i.OrgID,
		&i.PricingPlanID,
		&i.InheritDefault,
		&i.Reason,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPricingPlanModelOverride = `-- name: UpsertPricingPlanModelOverride :one
INSERT INTO pricing_plan_model_overrides (pricing_plan_id, model_id, multiplier_bps)
VALUES ($1, $2, $3)
ON CONFLICT (pricing_plan_id, model_id) DO UPDATE SET multiplier_bps = EXCLUDED.multiplier_bps
RETURNING pricing_plan_id, model_id, multiplier_bps
`

type UpsertPricingPlanModelOverrideParams struct {
	PricingPlanID pgtype.UUID
	ModelID       pgtype.UUID
	MultiplierBps int32
}

func (q *Queries) UpsertPricingPlanModelOverride(ctx context.Context, arg UpsertPricingPlanModelOverrideParams) (PricingPlanModelOverride, error) {
	row := q.db.QueryRow(ctx, upsertPricingPlanModelOverride, arg.PricingPlanID, arg.ModelID, arg.MultiplierBps)
	var i PricingPlanModelOverride
	err := row.Scan(&i.PricingPlanID, &i.ModelID, &i.MultiplierBps)
	return i, err
}
