// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tiers.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTierModels = `-- name: AddTierModels :exec
INSERT INTO model_tier_models (tier_id, model_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddTierModelsParams struct {
	TierID   pgtype.UUID
	ModelIds []pgtype.UUID
}

// Bulk insert via unnest: one round trip instead of one per model.
// ON CONFLICT DO NOTHING makes duplicate selections and concurrent replays
// idempotent.
func (q *Queries) AddTierModels(ctx context.Context, arg AddTierModelsParams) error {
	_, err := q.db.Exec(ctx, addTierModels, arg.TierID, arg.ModelIds)
	return err
}

const clearDefaultTier = `-- name: ClearDefaultTier :exec
UPDATE model_tiers SET is_default = false, updated_at = now() WHERE is_default
`

// The two steps of moving the default. They are separate because a single
// UPDATE cannot satisfy model_tiers_single_default_uk in its intermediate state
// (a unique index takes effect within the statement).
// Callers must run both in one transaction, otherwise there is a window with no
// default tier at all.
func (q *Queries) ClearDefaultTier(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultTier)
	return err
}

const clearTierModels = `-- name: ClearTierModels :exec
DELETE FROM model_tier_models WHERE tier_id = $1
`

// Whole-set replacement: clear, then insert. Simpler than diffing out an
// add-set and a remove-set, and what the admin page submits is already the full
// set after checking boxes -- a diff-based implementation needs extra state and
// drifts from the UI easily.
func (q *Queries) ClearTierModels(ctx context.Context, tierID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTierModels, tierID)
	return err
}

const countOrgsOnTier = `-- name: CountOrgsOnTier :one
SELECT count(*)::bigint FROM org_gateway_settings WHERE tier_id = $1
`

// Reference check before deleting a tier: report the member count so the
// operator knows how many orgs have to be migrated, instead of just "cannot
// delete" -- the ON DELETE RESTRICT error does not carry that number.
func (q *Queries) CountOrgsOnTier(ctx context.Context, tierID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgsOnTier, tierID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO model_tiers (slug, name, description, allow_all_models)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, description, allow_all_models, is_default, status, created_at, updated_at
`

type CreateTierParams struct {
	Slug           string
	Name           string
	Description    string
	AllowAllModels bool
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (ModelTier, error) {
	row := q.db.QueryRow(ctx, createTier,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.AllowAllModels,
	)
	var i ModelTier
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AllowAllModels,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTier = `-- name: DeleteTier :execrows
DELETE FROM model_tiers WHERE id = $1 AND NOT is_default
`

// The default tier cannot be deleted (the application checks again; a DELETE
// guard cannot be expressed as a CHECK). Tiers with members are caught by
// ON DELETE RESTRICT on org_gateway_settings.tier_id.
func (q *Queries) DeleteTier(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTier, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgGatewaySettings = `-- name: GetOrgGatewaySettings :one

SELECT (s.tier_id IS NOT NULL)::boolean          AS tier_explicit,
       (s.org_id IS NOT NULL)::boolean           AS row_exists,
       COALESCE(t.id, dt.id)                     AS tier_id,
       COALESCE(t.slug, dt.slug)::text           AS tier_slug,
       COALESCE(t.name, dt.name)::text           AS tier_name,
       COALESCE(t.status, dt.status)::text       AS tier_status,
       COALESCE(t.allow_all_models, dt.allow_all_models)::boolean AS tier_allow_all_models,
       s.rate_limit_rpm,
       s.rate_limit_tpm
FROM (SELECT 1) AS anchor
LEFT JOIN org_gateway_settings s ON s.org_id = $1::uuid
LEFT JOIN model_tiers t          ON t.id = s.tier_id
LEFT JOIN model_tiers dt         ON dt.is_default
`

type GetOrgGatewaySettingsRow struct {
	TierExplicit       bool
	RowExists          bool
	TierID             pgtype.UUID
	TierSlug           string
	TierName           string
	TierStatus         string
	TierAllowAllModels bool
	RateLimitRpm       pgtype.Int4
	RateLimitTpm       pgtype.Int4
}

// ===== Binding on the org side =====
// What this org has been granted: its *effective* tier plus its own rate
// ceilings.
//
// Both a missing row and a NULL tier_id fall back to the default tier, so this
// is not a plain SELECT: `FROM (SELECT 1)` guarantees exactly one row, the two
// LEFT JOINs pick up "the explicitly assigned tier" and "the default tier", and
// COALESCE decides which one wins. Doing the fallback in SQL rather than in Go
// keeps the read path to a single round trip and keeps "effective tier" defined
// in exactly one place.
//
// The rate ceilings have no such fallback: a missing row simply means no
// ceiling, and NULL says the same thing, so they are read straight off the row.
//
// The two explicit-flag columns let the caller distinguish "configured on
// purpose" from "following the default" -- that difference is what the admin
// page needs to show, rather than a value with no visible provenance.
// No join condition = a cross product against the single default row
// (model_tiers_single_default_uk guarantees there is only one).
func (q *Queries) GetOrgGatewaySettings(ctx context.Context, orgID pgtype.UUID) (GetOrgGatewaySettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrgGatewaySettings, orgID)
	var i GetOrgGatewaySettingsRow
	err := row.Scan(
		&i.TierExplicit,
		&i.RowExists,
		&i.TierID,
		&i.TierSlug,
		&i.TierName,
		&i.TierStatus,
		&i.TierAllowAllModels,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
	)
	return i, err
}

const getOrgSettingsForDataplane = `-- name: GetOrgSettingsForDataplane :one

SELECT COALESCE(t.id, dt.id)               AS tier_id,
       COALESCE(t.status, dt.status)::text AS tier_status,
       s.rate_limit_rpm,
       s.rate_limit_tpm
FROM (SELECT 1) AS anchor
LEFT JOIN org_gateway_settings s ON s.org_id = $1::uuid
LEFT JOIN model_tiers t          ON t.id = s.tier_id
LEFT JOIN model_tiers dt         ON dt.is_default
`

type GetOrgSettingsForDataplaneRow struct {
	TierID       pgtype.UUID
	TierStatus   string
	RateLimitRpm pgtype.Int4
	RateLimitTpm pgtype.Int4
}

// ===== Dataplane =====
// The org's gateway settings, read while loading a request identity: the
// effective tier and the two rate ceilings.
//
// Same shape as GetOrgGatewaySettings but only the columns the hot path needs.
// Deliberately not merged into the core org lookup: that query lives in the
// shared query set and is compiled into builds that do not carry the gateway
// schema, so joining a gateway table into it would make those builds hit a
// table that does not exist at runtime. The extra round trip is amortised by
// the identity cache -- it happens only on load.
func (q *Queries) GetOrgSettingsForDataplane(ctx context.Context, orgID pgtype.UUID) (GetOrgSettingsForDataplaneRow, error) {
	row := q.db.QueryRow(ctx, getOrgSettingsForDataplane, orgID)
	var i GetOrgSettingsForDataplaneRow
	err := row.Scan(
		&i.TierID,
		&i.TierStatus,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
	)
	return i, err
}

const getTier = `-- name: GetTier :one
SELECT id, slug, name, description, allow_all_models, is_default, status, created_at, updated_at
FROM model_tiers WHERE id = $1
`

func (q *Queries) GetTier(ctx context.Context, id pgtype.UUID) (ModelTier, error) {
	row := q.db.QueryRow(ctx, getTier, id)
	var i ModelTier
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AllowAllModels,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveKeyHashesForOrg = `-- name: ListActiveKeyHashesForOrg :many
SELECT key_hash FROM api_keys WHERE org_id = $1 AND status = 'active'
`

// Changing an org's tier must invalidate the dataplane key cache immediately,
// because the cached identity carries the tier with it.
// Cache keys are built from the key hash, so invalidating by org means first
// looking up that org's hashes.
// Only active keys: a revoked key has its own invalidation path and should not
// be re-entering the cache anyway.
func (q *Queries) ListActiveKeyHashesForOrg(ctx context.Context, orgID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveKeyHashesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key_hash string
		if err := rows.Scan(&key_hash); err != nil {
			return nil, err
		}
		items = append(items, key_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTierModels = `-- name: ListTierModels :many

SELECT m.id, m.slug, m.display_name, m.enabled, m.visibility
FROM model_tier_models tm
JOIN models m ON m.id = tm.model_id
WHERE tm.tier_id = $1
ORDER BY m.slug
LIMIT 500
`

type ListTierModelsRow struct {
	ID          pgtype.UUID
	Slug        string
	DisplayName string
	Enabled     bool
	Visibility  string
}

// ===== Models inside a tier =====
// 有界而不是分页，且这是**整集编辑面的前提**（ADR-0189）：编辑面把这份清单当作
// 完整的「已配置集」，缺一行，那一行在界面上就不存在——读者看到的不是「没勾」，
// 是「没有这一项」，而保存时它会被算作未勾选。上界跟着目录走（同为 500）：
// 一个档位允许的模型数、一个方案覆盖价的条数，都不可能超过目录本身。
func (q *Queries) ListTierModels(ctx context.Context, tierID pgtype.UUID) ([]ListTierModelsRow, error) {
	rows, err := q.db.Query(ctx, listTierModels, tierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTierModelsRow
	for rows.Next() {
		var i ListTierModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Enabled,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiers = `-- name: ListTiers :many

SELECT t.id, t.slug, t.name, t.description, t.allow_all_models, t.is_default, t.status,
       t.created_at, t.updated_at,
       (SELECT count(*) FROM model_tier_models m WHERE m.tier_id = t.id)::bigint AS model_count,
       (SELECT count(*) FROM org_gateway_settings s WHERE s.tier_id = t.id)::bigint AS org_count
FROM model_tiers t
WHERE (NOT $1::boolean
       OR t.is_default < $2::boolean
       OR (t.is_default = $2::boolean AND t.slug > $3::text))
  AND ($4::text = '' OR t.slug ILIKE '%' || $4::text || '%'
       OR t.name ILIKE '%' || $4::text || '%')
ORDER BY t.is_default DESC, t.slug
LIMIT $5
`

type ListTiersParams struct {
	HasCursor       bool
	CursorIsDefault bool
	CursorSlug      string
	Search          string
	Lim             int32
}

type ListTiersRow struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	Description    string
	AllowAllModels bool
	IsDefault      bool
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ModelCount     int64
	OrgCount       int64
}

// Model tiers: the admission axis. A tier names a set of models an org is
// allowed to reach; it is orthogonal to pricing, which is decided per model.
// The list carries two counts: models in the tier and orgs assigned to it.
// The counts are computed in SQL rather than fetched N+1, because the admin
// page wants "how many models does this tier admit, how many organizations sit on it"
// in one screen, and with tiers numbering in the tens a subquery is cheaper
// than a round trip.
// model_count is read together with allow_all_models, never on its own: with
// allow_all_models true the count is zero by construction and says nothing, and
// with it false a zero count means the tier admits nothing at all.
// 键是 (is_default, slug)：默认档／默认方案永远排在最前，其余按 slug。
// 混合方向的元组比较不能直接写 `>`——is_default 降序意味着「之后」是它更小，
// 或相等而 slug 更大。slug 唯一，所以两分量已是全序，不需要 id 兜底。
func (q *Queries) ListTiers(ctx context.Context, arg ListTiersParams) ([]ListTiersRow, error) {
	rows, err := q.db.Query(ctx, listTiers,
		arg.HasCursor,
		arg.CursorIsDefault,
		arg.CursorSlug,
		arg.Search,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTiersRow
	for rows.Next() {
		var i ListTiersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AllowAllModels,
			&i.IsDefault,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelCount,
			&i.OrgCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDefaultTier = `-- name: MarkDefaultTier :execrows
UPDATE model_tiers SET is_default = true, updated_at = now()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) MarkDefaultTier(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDefaultTier, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const modelsNotAdmittedForOrg = `-- name: ModelsNotAdmittedForOrg :many
WITH tier AS (
    SELECT COALESCE(t.id, dt.id)                   AS id,
           COALESCE(t.allow_all_models, dt.allow_all_models) AS allow_all_models
    FROM (SELECT 1) AS anchor
    LEFT JOIN org_gateway_settings s ON s.org_id = $2::uuid
    LEFT JOIN model_tiers t          ON t.id = s.tier_id
    LEFT JOIN model_tiers dt         ON dt.is_default
)
SELECT candidate.slug::text AS slug
FROM unnest($1::text[]) AS candidate(slug)
WHERE NOT EXISTS (
    SELECT 1
    FROM models m, tier
    WHERE m.slug = candidate.slug
      AND m.enabled
      AND m.visibility = 'public'
      AND (
          tier.allow_all_models
          OR EXISTS (
              SELECT 1 FROM model_tier_models mt
              WHERE mt.tier_id = tier.id AND mt.model_id = m.id
          )
      )
)
`

type ModelsNotAdmittedForOrgParams struct {
	Slugs []string
	OrgID pgtype.UUID
}

// Which of these model slugs is this org *not* allowed to reach?
//
// It answers with the offending slugs rather than a verdict, because whoever
// asked has to be told which ones: "one of these is not available" leaves a
// person comparing two lists by hand.
//
// The criterion is deliberately the same three-part one the dataplane applies
// -- enabled, public, admitted by the tier -- so a key allowlist can never be
// saved promising a model that would answer 404 when called. It is not the
// same *statement*, though, and cannot be: this one runs over a set of slugs
// and the dataplane resolves exactly one.
//
// With no tier resolvable at all (no default row) every slug comes back
// rejected: the comparison against a NULL tier is not true, and refusing to
// save is the right direction when the deployment cannot say what is allowed.
func (q *Queries) ModelsNotAdmittedForOrg(ctx context.Context, arg ModelsNotAdmittedForOrgParams) ([]string, error) {
	rows, err := q.db.Query(ctx, modelsNotAdmittedForOrg, arg.Slugs, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putOrgGatewaySettings = `-- name: PutOrgGatewaySettings :one
INSERT INTO org_gateway_settings (org_id, tier_id, rate_limit_rpm, rate_limit_tpm)
VALUES ($1, $2,
        $3, $4)
ON CONFLICT (org_id) DO UPDATE SET
    tier_id        = excluded.tier_id,
    rate_limit_rpm = excluded.rate_limit_rpm,
    rate_limit_tpm = excluded.rate_limit_tpm,
    updated_at     = now()
RETURNING org_id, tier_id, rate_limit_rpm, rate_limit_tpm, updated_at
`

type PutOrgGatewaySettingsParams struct {
	OrgID        pgtype.UUID
	TierID       pgtype.UUID
	RateLimitRpm pgtype.Int4
	RateLimitTpm pgtype.Int4
}

// Whole-row replacement (PUT semantics). Deliberately not a partial update: a
// partial update needs a sentinel parameter to express "clear tier_id" (a
// nullable field cannot be expressed with coalesce), and that sentinel pattern
// is where the existing complexity around per-model markup overrides comes
// from. Whole-row replacement leaves nothing in the SQL but excluded.*.
func (q *Queries) PutOrgGatewaySettings(ctx context.Context, arg PutOrgGatewaySettingsParams) (OrgGatewaySetting, error) {
	row := q.db.QueryRow(ctx, putOrgGatewaySettings,
		arg.OrgID,
		arg.TierID,
		arg.RateLimitRpm,
		arg.RateLimitTpm,
	)
	var i OrgGatewaySetting
	err := row.Scan(
		&i.OrgID,
		&i.TierID,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.UpdatedAt,
	)
	return i, err
}

const tierAllowsModel = `-- name: TierAllowsModel :one
SELECT (
    t.allow_all_models
    OR EXISTS (
        SELECT 1 FROM model_tier_models m
        WHERE m.tier_id = t.id AND m.model_id = $1
    )
)::boolean AS allowed
FROM model_tiers t
WHERE t.id = $2
`

type TierAllowsModelParams struct {
	ModelID pgtype.UUID
	TierID  pgtype.UUID
}

// Does this tier admit this model? Either it admits everything, or it admits
// exactly what it lists -- and a tier that lists nothing admits nothing. The
// answer therefore has to read the tier row itself, not just count membership:
// inferring "unrestricted" from an empty membership is what made a cleared
// list silently grant the whole catalogue.
//
// Selecting FROM model_tiers means a tier that no longer exists returns no row
// rather than a permissive default. The caller treats that as "not admitted"
// (see catalog.Resolve).
// Every column is table-qualified: without the alias sqlc's analyser reads
// `tier_id = sqlc.arg('tier_id')` as an ambiguous column reference. PostgreSQL
// itself resolves it fine, but code generation fails.
func (q *Queries) TierAllowsModel(ctx context.Context, arg TierAllowsModelParams) (bool, error) {
	row := q.db.QueryRow(ctx, tierAllowsModel, arg.ModelID, arg.TierID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const updateTier = `-- name: UpdateTier :one
UPDATE model_tiers SET
    name             = coalesce($1, name),
    description      = coalesce($2, description),
    status           = coalesce($3, status),
    allow_all_models = coalesce($4, allow_all_models),
    updated_at       = now()
WHERE id = $5
RETURNING id, slug, name, description, allow_all_models, is_default, status, created_at, updated_at
`

type UpdateTierParams struct {
	Name           pgtype.Text
	Description    pgtype.Text
	Status         pgtype.Text
	AllowAllModels pgtype.Bool
	ID             pgtype.UUID
}

// Partial update: NULL means "leave this field alone". is_default is
// deliberately absent -- moving the default is a two-row transaction
// (ClearDefaultTier + MarkDefaultTier), and folding it into a partial update
// would let a casual rename move the default as a side effect.
func (q *Queries) UpdateTier(ctx context.Context, arg UpdateTierParams) (ModelTier, error) {
	row := q.db.QueryRow(ctx, updateTier,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.AllowAllModels,
		arg.ID,
	)
	var i ModelTier
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AllowAllModels,
		&i.IsDefault,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
