// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videojobs.sql

package gwdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueVideoJobs = `-- name: ClaimDueVideoJobs :many
UPDATE gateway_async_jobs
   SET next_poll_at = now() + $1::interval, last_polled_at = now(),
       poll_attempts = poll_attempts + 1
 WHERE id IN (
     SELECT id FROM gateway_async_jobs
      WHERE kind = 'video' AND status IN ('queued', 'in_progress')
        AND next_poll_at <= now()
      ORDER BY next_poll_at
      LIMIT $2
      FOR UPDATE SKIP LOCKED
 )
RETURNING id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at
`

type ClaimDueVideoJobsParams struct {
	Lease pgtype.Interval
	Lim   int32
}

// One statement is the lease: the rows selected are the rows whose next poll is
// pushed out, so a second replica running concurrently takes a different batch.
func (q *Queries) ClaimDueVideoJobs(ctx context.Context, arg ClaimDueVideoJobsParams) ([]GatewayAsyncJob, error) {
	rows, err := q.db.Query(ctx, claimDueVideoJobs, arg.Lease, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAsyncJob
	for rows.Next() {
		var i GatewayAsyncJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApiKeyID,
			&i.Kind,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.ModelID,
			&i.ModelSlug,
			&i.RouteID,
			&i.ProviderID,
			&i.ProviderKeyID,
			&i.OrgProviderKeyID,
			&i.Byok,
			&i.UpstreamID,
			&i.Status,
			&i.SettlementState,
			&i.UpstreamStatus,
			&i.Progress,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Params,
			&i.BillingUnits,
			&i.HoldID,
			&i.HoldNano,
			&i.HoldExpiresAt,
			&i.ChargedNano,
			&i.ChargedCurrency,
			&i.PricingSnapshot,
			&i.MaxJobSeconds,
			&i.PollAttempts,
			&i.NotFoundCount,
			&i.NextPollAt,
			&i.LastPolledAt,
			&i.ArtifactKey,
			&i.ArtifactBytes,
			&i.ArtifactContentType,
			&i.ArtifactFetchedAt,
			&i.UpstreamArtifactRef,
			&i.UpstreamArtifactExpiresAt,
			&i.NativeAlias,
			&i.EndUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearVideoJobArtifact = `-- name: ClearVideoJobArtifact :exec
UPDATE gateway_async_jobs
   SET artifact_key = '', artifact_bytes = 0, artifact_content_type = '', artifact_fetched_at = NULL
 WHERE id = $1
`

// Forget the stored object without forgetting the job.
//
// Retention is about the media, and a row whose money has not moved may not be
// deleted (see videoDeleteRefusal): it is the only thing pointing at an
// outstanding reservation, and it is what the operator's repair queue reads. So
// the sweep drops the artifact and keeps the row.
//
// The key is cleared rather than merely deleted upstream, because the sweep
// selects on `expires_at` and would otherwise pick the same row up every pass
// and re-issue a delete for an object that is already gone.
func (q *Queries) ClearVideoJobArtifact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearVideoJobArtifact, id)
	return err
}

const countStuckMoneyJobs = `-- name: CountStuckMoneyJobs :one
SELECT count(*)::bigint              AS jobs,
       min(terminal_at)::timestamptz AS oldest_terminal_at
FROM gateway_async_jobs
WHERE settlement_state IN ('held', 'protected')
  AND status IN ('completed', 'failed', 'canceled', 'expired')
`

type CountStuckMoneyJobsRow struct {
	Jobs             int64
	OldestTerminalAt pgtype.Timestamptz
}

// Terminal jobs whose money never moved: the operator's repair queue.
//
// The predicate is `gateway_async_jobs_stuck_money_idx`'s, verbatim. That index
// was created with a comment calling this "the operator's repair queue" and then
// had no reader at all -- the state was absent from the API, the console and the
// alerts at once, which is the one shape in which a money bug keeps its own
// secret. A row here is a customer either overcharged or not charged.
//
// It does not filter on `kind`, and neither does the index. A second kind of
// asynchronous job would reach terminal with an unmoved reservation the same
// way, and a queue that silently covered only one of them would be worse than
// no queue: it would read as "nothing stuck".
//
// Two numbers rather than one, because a count alone cannot be triaged:
// `oldest_terminal_at` separates a live incident from a single row stranded a
// month ago.
//
// It deliberately does **not** sum `hold_nano`. A hold is denominated in its
// organisation's wallet currency, `wallets.currency` is per-organisation, and
// that table is Cloud's -- this query ships in Community too, where there are
// no wallets at all. So the sum would be either a cross-currency addition or a
// join this module is not allowed to write. A total that is wrong is worse here
// than no total: this readout exists to be believed.
func (q *Queries) CountStuckMoneyJobs(ctx context.Context) (CountStuckMoneyJobsRow, error) {
	row := q.db.QueryRow(ctx, countStuckMoneyJobs)
	var i CountStuckMoneyJobsRow
	err := row.Scan(&i.Jobs, &i.OldestTerminalAt)
	return i, err
}

const createVideoJob = `-- name: CreateVideoJob :one

INSERT INTO gateway_async_jobs (
    org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint,
    model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id,
    byok, status, params, billing_units, hold_id, hold_nano, hold_expires_at,
    charged_currency, pricing_snapshot, end_user_id, max_job_seconds, next_poll_at, expires_at
) VALUES (
    $1, $2, 'video', $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, 'queued', $13, $14, $15, $16, $17,
    $18, $19, $20, $21, now(), $22
)
RETURNING id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at
`

type CreateVideoJobParams struct {
	OrgID              pgtype.UUID
	ApiKeyID           pgtype.UUID
	RequestID          string
	IdempotencyKey     string
	RequestFingerprint string
	ModelID            pgtype.UUID
	ModelSlug          string
	RouteID            pgtype.UUID
	ProviderID         pgtype.UUID
	ProviderKeyID      pgtype.UUID
	OrgProviderKeyID   pgtype.UUID
	Byok               bool
	Params             []byte
	BillingUnits       []byte
	HoldID             pgtype.UUID
	HoldNano           int64
	HoldExpiresAt      pgtype.Timestamptz
	ChargedCurrency    string
	PricingSnapshot    []byte
	EndUserID          string
	MaxJobSeconds      int32
	ExpiresAt          pgtype.Timestamptz
}

// Asynchronous job rows: work that outlives the request that started it.
//
// Every statement here is written so that a crash between any two of them
// leaves a state the reconciler can finish. The money-bearing ones guard on
// settlement_state rather than reading it first, because two concurrent pollers
// would both pass a check-then-act.
func (q *Queries) CreateVideoJob(ctx context.Context, arg CreateVideoJobParams) (GatewayAsyncJob, error) {
	row := q.db.QueryRow(ctx, createVideoJob,
		arg.OrgID,
		arg.ApiKeyID,
		arg.RequestID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ModelID,
		arg.ModelSlug,
		arg.RouteID,
		arg.ProviderID,
		arg.ProviderKeyID,
		arg.OrgProviderKeyID,
		arg.Byok,
		arg.Params,
		arg.BillingUnits,
		arg.HoldID,
		arg.HoldNano,
		arg.HoldExpiresAt,
		arg.ChargedCurrency,
		arg.PricingSnapshot,
		arg.EndUserID,
		arg.MaxJobSeconds,
		arg.ExpiresAt,
	)
	var i GatewayAsyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApiKeyID,
		&i.Kind,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
		&i.ModelSlug,
		&i.RouteID,
		&i.ProviderID,
		&i.ProviderKeyID,
		&i.OrgProviderKeyID,
		&i.Byok,
		&i.UpstreamID,
		&i.Status,
		&i.SettlementState,
		&i.UpstreamStatus,
		&i.Progress,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Params,
		&i.BillingUnits,
		&i.HoldID,
		&i.HoldNano,
		&i.HoldExpiresAt,
		&i.ChargedNano,
		&i.ChargedCurrency,
		&i.PricingSnapshot,
		&i.MaxJobSeconds,
		&i.PollAttempts,
		&i.NotFoundCount,
		&i.NextPollAt,
		&i.LastPolledAt,
		&i.ArtifactKey,
		&i.ArtifactBytes,
		&i.ArtifactContentType,
		&i.ArtifactFetchedAt,
		&i.UpstreamArtifactRef,
		&i.UpstreamArtifactExpiresAt,
		&i.NativeAlias,
		&i.EndUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.TerminalAt,
	)
	return i, err
}

const deleteVideoJob = `-- name: DeleteVideoJob :exec
DELETE FROM gateway_async_jobs WHERE id = $1
`

func (q *Queries) DeleteVideoJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideoJob, id)
	return err
}

const getVideoJob = `-- name: GetVideoJob :one
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE id = $1 AND org_id = $2 AND kind = 'video'
`

type GetVideoJobParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

// Org-scoped by the predicate, not only by RLS: a job id belonging to another
// organization must be indistinguishable from one that does not exist.
func (q *Queries) GetVideoJob(ctx context.Context, arg GetVideoJobParams) (GatewayAsyncJob, error) {
	row := q.db.QueryRow(ctx, getVideoJob, arg.ID, arg.OrgID)
	var i GatewayAsyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApiKeyID,
		&i.Kind,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
		&i.ModelSlug,
		&i.RouteID,
		&i.ProviderID,
		&i.ProviderKeyID,
		&i.OrgProviderKeyID,
		&i.Byok,
		&i.UpstreamID,
		&i.Status,
		&i.SettlementState,
		&i.UpstreamStatus,
		&i.Progress,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Params,
		&i.BillingUnits,
		&i.HoldID,
		&i.HoldNano,
		&i.HoldExpiresAt,
		&i.ChargedNano,
		&i.ChargedCurrency,
		&i.PricingSnapshot,
		&i.MaxJobSeconds,
		&i.PollAttempts,
		&i.NotFoundCount,
		&i.NextPollAt,
		&i.LastPolledAt,
		&i.ArtifactKey,
		&i.ArtifactBytes,
		&i.ArtifactContentType,
		&i.ArtifactFetchedAt,
		&i.UpstreamArtifactRef,
		&i.UpstreamArtifactExpiresAt,
		&i.NativeAlias,
		&i.EndUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.TerminalAt,
	)
	return i, err
}

const getVideoJobByAlias = `-- name: GetVideoJobByAlias :one
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE native_alias = $1 AND org_id = $2 AND kind = 'video'
`

type GetVideoJobByAliasParams struct {
	NativeAlias int64
	OrgID       pgtype.UUID
}

// The same job reached by its integer alias, which is what one vendor's
// compatibility surface must hand out because that vendor's own schema types
// the identifier as int64.
//
// Scoped the same way and for the same reason: an alias from another
// organization has to be indistinguishable from one that never existed.
// Guessing one is easier than guessing a UUID, which is exactly why the
// predicate carries the organization rather than trusting the identifier to be
// unguessable.
func (q *Queries) GetVideoJobByAlias(ctx context.Context, arg GetVideoJobByAliasParams) (GatewayAsyncJob, error) {
	row := q.db.QueryRow(ctx, getVideoJobByAlias, arg.NativeAlias, arg.OrgID)
	var i GatewayAsyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApiKeyID,
		&i.Kind,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
		&i.ModelSlug,
		&i.RouteID,
		&i.ProviderID,
		&i.ProviderKeyID,
		&i.OrgProviderKeyID,
		&i.Byok,
		&i.UpstreamID,
		&i.Status,
		&i.SettlementState,
		&i.UpstreamStatus,
		&i.Progress,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Params,
		&i.BillingUnits,
		&i.HoldID,
		&i.HoldNano,
		&i.HoldExpiresAt,
		&i.ChargedNano,
		&i.ChargedCurrency,
		&i.PricingSnapshot,
		&i.MaxJobSeconds,
		&i.PollAttempts,
		&i.NotFoundCount,
		&i.NextPollAt,
		&i.LastPolledAt,
		&i.ArtifactKey,
		&i.ArtifactBytes,
		&i.ArtifactContentType,
		&i.ArtifactFetchedAt,
		&i.UpstreamArtifactRef,
		&i.UpstreamArtifactExpiresAt,
		&i.NativeAlias,
		&i.EndUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.TerminalAt,
	)
	return i, err
}

const getVideoJobByIdempotencyKey = `-- name: GetVideoJobByIdempotencyKey :one
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE org_id = $1 AND kind = 'video' AND idempotency_key = $2
`

type GetVideoJobByIdempotencyKeyParams struct {
	OrgID          pgtype.UUID
	IdempotencyKey string
}

// The replay path: a repeat of a key returns the job it already created.
func (q *Queries) GetVideoJobByIdempotencyKey(ctx context.Context, arg GetVideoJobByIdempotencyKeyParams) (GatewayAsyncJob, error) {
	row := q.db.QueryRow(ctx, getVideoJobByIdempotencyKey, arg.OrgID, arg.IdempotencyKey)
	var i GatewayAsyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApiKeyID,
		&i.Kind,
		&i.RequestID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
		&i.ModelSlug,
		&i.RouteID,
		&i.ProviderID,
		&i.ProviderKeyID,
		&i.OrgProviderKeyID,
		&i.Byok,
		&i.UpstreamID,
		&i.Status,
		&i.SettlementState,
		&i.UpstreamStatus,
		&i.Progress,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Params,
		&i.BillingUnits,
		&i.HoldID,
		&i.HoldNano,
		&i.HoldExpiresAt,
		&i.ChargedNano,
		&i.ChargedCurrency,
		&i.PricingSnapshot,
		&i.MaxJobSeconds,
		&i.PollAttempts,
		&i.NotFoundCount,
		&i.NextPollAt,
		&i.LastPolledAt,
		&i.ArtifactKey,
		&i.ArtifactBytes,
		&i.ArtifactContentType,
		&i.ArtifactFetchedAt,
		&i.UpstreamArtifactRef,
		&i.UpstreamArtifactExpiresAt,
		&i.NativeAlias,
		&i.EndUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.TerminalAt,
	)
	return i, err
}

const getVideoJobProviderKey = `-- name: GetVideoJobProviderKey :one
SELECT id, secret_enc FROM provider_keys WHERE id = $1
`

type GetVideoJobProviderKeyRow struct {
	ID        pgtype.UUID
	SecretEnc []byte
}

// The exact shared credential a job was created with.
func (q *Queries) GetVideoJobProviderKey(ctx context.Context, id pgtype.UUID) (GetVideoJobProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, getVideoJobProviderKey, id)
	var i GetVideoJobProviderKeyRow
	err := row.Scan(&i.ID, &i.SecretEnc)
	return i, err
}

const getVideoJobRoute = `-- name: GetVideoJobRoute :one
SELECT r.id, r.provider_model_id, r.headers AS route_headers, r.video_envelope,
       p.id AS provider_id, p.slug AS provider_slug, p.vendor, p.base_url,
       p.headers AS provider_headers, p.transport AS provider_transport
FROM model_routes r JOIN providers p ON p.id = r.provider_id
WHERE r.id = $1
`

type GetVideoJobRouteRow struct {
	ID                pgtype.UUID
	ProviderModelID   string
	RouteHeaders      []byte
	VideoEnvelope     []byte
	ProviderID        pgtype.UUID
	ProviderSlug      string
	Vendor            string
	BaseUrl           string
	ProviderHeaders   []byte
	ProviderTransport []byte
}

// The route a job was pinned to, loaded by id and without any admission check.
//
// Polling needs two things: where to send the request and which credential
// created the upstream job. It does not need to re-decide whether the model is
// still admissible -- doing that made an ordinary catalog edit (hiding a model,
// renaming an upstream model, which resets probe verdicts) turn every in-flight
// job into a failed one while the upstream kept generating.
//
// It carries `video_envelope` because how far a job can be stopped is declared
// there, and the catalogue publishes it from there: reading it from anywhere
// else makes the two disagree (ADR-0221).
func (q *Queries) GetVideoJobRoute(ctx context.Context, id pgtype.UUID) (GetVideoJobRouteRow, error) {
	row := q.db.QueryRow(ctx, getVideoJobRoute, id)
	var i GetVideoJobRouteRow
	err := row.Scan(
		&i.ID,
		&i.ProviderModelID,
		&i.RouteHeaders,
		&i.VideoEnvelope,
		&i.ProviderID,
		&i.ProviderSlug,
		&i.Vendor,
		&i.BaseUrl,
		&i.ProviderHeaders,
		&i.ProviderTransport,
	)
	return i, err
}

const listExpiredVideoJobs = `-- name: ListExpiredVideoJobs :many
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE kind = 'video' AND expires_at <= now()
LIMIT $1
`

func (q *Queries) ListExpiredVideoJobs(ctx context.Context, lim int32) ([]GatewayAsyncJob, error) {
	rows, err := q.db.Query(ctx, listExpiredVideoJobs, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAsyncJob
	for rows.Next() {
		var i GatewayAsyncJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApiKeyID,
			&i.Kind,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.ModelID,
			&i.ModelSlug,
			&i.RouteID,
			&i.ProviderID,
			&i.ProviderKeyID,
			&i.OrgProviderKeyID,
			&i.Byok,
			&i.UpstreamID,
			&i.Status,
			&i.SettlementState,
			&i.UpstreamStatus,
			&i.Progress,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Params,
			&i.BillingUnits,
			&i.HoldID,
			&i.HoldNano,
			&i.HoldExpiresAt,
			&i.ChargedNano,
			&i.ChargedCurrency,
			&i.PricingSnapshot,
			&i.MaxJobSeconds,
			&i.PollAttempts,
			&i.NotFoundCount,
			&i.NextPollAt,
			&i.LastPolledAt,
			&i.ArtifactKey,
			&i.ArtifactBytes,
			&i.ArtifactContentType,
			&i.ArtifactFetchedAt,
			&i.UpstreamArtifactRef,
			&i.UpstreamArtifactExpiresAt,
			&i.NativeAlias,
			&i.EndUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleVideoJobs = `-- name: ListStaleVideoJobs :many
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE kind = 'video' AND status IN ('queued', 'in_progress')
  AND created_at < now() - make_interval(secs => max_job_seconds * 2)
LIMIT $1
`

// Never reached a terminal state within twice its model's own ceiling.
//
// Per job rather than one interval for all of them: the ceiling is a property
// of the model, and a single global bound either expires a long render that was
// about to succeed or leaves a dead short job holding a reservation for hours.
func (q *Queries) ListStaleVideoJobs(ctx context.Context, lim int32) ([]GatewayAsyncJob, error) {
	rows, err := q.db.Query(ctx, listStaleVideoJobs, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAsyncJob
	for rows.Next() {
		var i GatewayAsyncJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApiKeyID,
			&i.Kind,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.ModelID,
			&i.ModelSlug,
			&i.RouteID,
			&i.ProviderID,
			&i.ProviderKeyID,
			&i.OrgProviderKeyID,
			&i.Byok,
			&i.UpstreamID,
			&i.Status,
			&i.SettlementState,
			&i.UpstreamStatus,
			&i.Progress,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Params,
			&i.BillingUnits,
			&i.HoldID,
			&i.HoldNano,
			&i.HoldExpiresAt,
			&i.ChargedNano,
			&i.ChargedCurrency,
			&i.PricingSnapshot,
			&i.MaxJobSeconds,
			&i.PollAttempts,
			&i.NotFoundCount,
			&i.NextPollAt,
			&i.LastPolledAt,
			&i.ArtifactKey,
			&i.ArtifactBytes,
			&i.ArtifactContentType,
			&i.ArtifactFetchedAt,
			&i.UpstreamArtifactRef,
			&i.UpstreamArtifactExpiresAt,
			&i.NativeAlias,
			&i.EndUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsubmittedVideoJobs = `-- name: ListUnsubmittedVideoJobs :many
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE kind = 'video' AND status = 'queued' AND upstream_id = '' AND submitted_at IS NULL
  AND created_at < now() - $1::interval
LIMIT $2
`

type ListUnsubmittedVideoJobsParams struct {
	OlderThan pgtype.Interval
	Lim       int32
}

// A hold was taken and nothing was ever submitted: the process died between the
// two. Bounded by age so a job still inside its submit call is not swept.
func (q *Queries) ListUnsubmittedVideoJobs(ctx context.Context, arg ListUnsubmittedVideoJobsParams) ([]GatewayAsyncJob, error) {
	rows, err := q.db.Query(ctx, listUnsubmittedVideoJobs, arg.OlderThan, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAsyncJob
	for rows.Next() {
		var i GatewayAsyncJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApiKeyID,
			&i.Kind,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.ModelID,
			&i.ModelSlug,
			&i.RouteID,
			&i.ProviderID,
			&i.ProviderKeyID,
			&i.OrgProviderKeyID,
			&i.Byok,
			&i.UpstreamID,
			&i.Status,
			&i.SettlementState,
			&i.UpstreamStatus,
			&i.Progress,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Params,
			&i.BillingUnits,
			&i.HoldID,
			&i.HoldNano,
			&i.HoldExpiresAt,
			&i.ChargedNano,
			&i.ChargedCurrency,
			&i.PricingSnapshot,
			&i.MaxJobSeconds,
			&i.PollAttempts,
			&i.NotFoundCount,
			&i.NextPollAt,
			&i.LastPolledAt,
			&i.ArtifactKey,
			&i.ArtifactBytes,
			&i.ArtifactContentType,
			&i.ArtifactFetchedAt,
			&i.UpstreamArtifactRef,
			&i.UpstreamArtifactExpiresAt,
			&i.NativeAlias,
			&i.EndUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoJobsForOrgFiltered = `-- name: ListVideoJobsForOrgFiltered :many
SELECT id, org_id, api_key_id, kind, request_id, idempotency_key, request_fingerprint, model_id, model_slug, route_id, provider_id, provider_key_id, org_provider_key_id, byok, upstream_id, status, settlement_state, upstream_status, progress, error_code, error_message, params, billing_units, hold_id, hold_nano, hold_expires_at, charged_nano, charged_currency, pricing_snapshot, max_job_seconds, poll_attempts, not_found_count, next_poll_at, last_polled_at, artifact_key, artifact_bytes, artifact_content_type, artifact_fetched_at, upstream_artifact_ref, upstream_artifact_expires_at, native_alias, end_user_id, expires_at, created_at, updated_at, submitted_at, terminal_at FROM gateway_async_jobs
WHERE org_id = $1 AND kind = 'video'
  AND ($2::text = '' OR status = $2::text)
  AND ($3::text = '' OR model_slug = $3::text)
  AND (NOT $4::boolean OR created_at >= $5::timestamptz)
  AND (NOT $6::boolean OR created_at < $7::timestamptz)
  AND (NOT $8::boolean
       OR created_at < $9::timestamptz
       OR (created_at = $9::timestamptz AND id < $10))
ORDER BY created_at DESC, id DESC
LIMIT $11
`

type ListVideoJobsForOrgFilteredParams struct {
	OrgID           pgtype.UUID
	Status          string
	ModelSlug       string
	HasFrom         bool
	FromTs          pgtype.Timestamptz
	HasTo           bool
	ToTs            pgtype.Timestamptz
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	Lim             int32
}

// One organization's jobs, newest first, for both surfaces.
//
// Keyset-ordered on gateway_async_jobs_org_idx (ADR-0185/0195). The data plane
// names none of the filters and gets the same statement with them all empty --
// one statement rather than two, because two would be one tested list endpoint
// and one that quietly drifted.
func (q *Queries) ListVideoJobsForOrgFiltered(ctx context.Context, arg ListVideoJobsForOrgFilteredParams) ([]GatewayAsyncJob, error) {
	rows, err := q.db.Query(ctx, listVideoJobsForOrgFiltered,
		arg.OrgID,
		arg.Status,
		arg.ModelSlug,
		arg.HasFrom,
		arg.FromTs,
		arg.HasTo,
		arg.ToTs,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayAsyncJob
	for rows.Next() {
		var i GatewayAsyncJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApiKeyID,
			&i.Kind,
			&i.RequestID,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
			&i.ModelID,
			&i.ModelSlug,
			&i.RouteID,
			&i.ProviderID,
			&i.ProviderKeyID,
			&i.OrgProviderKeyID,
			&i.Byok,
			&i.UpstreamID,
			&i.Status,
			&i.SettlementState,
			&i.UpstreamStatus,
			&i.Progress,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Params,
			&i.BillingUnits,
			&i.HoldID,
			&i.HoldNano,
			&i.HoldExpiresAt,
			&i.ChargedNano,
			&i.ChargedCurrency,
			&i.PricingSnapshot,
			&i.MaxJobSeconds,
			&i.PollAttempts,
			&i.NotFoundCount,
			&i.NextPollAt,
			&i.LastPolledAt,
			&i.ArtifactKey,
			&i.ArtifactBytes,
			&i.ArtifactContentType,
			&i.ArtifactFetchedAt,
			&i.UpstreamArtifactRef,
			&i.UpstreamArtifactExpiresAt,
			&i.NativeAlias,
			&i.EndUserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoRouteEnvelopes = `-- name: ListVideoRouteEnvelopes :many
SELECT id, video_envelope FROM model_routes WHERE id = ANY($1::uuid[])
`

type ListVideoRouteEnvelopesRow struct {
	ID            pgtype.UUID
	VideoEnvelope []byte
}

// The declared envelope of several routes at once.
//
// The console's job list needs one field off each row's route -- how far that
// job can still be stopped -- and asking per row turned a page of a hundred
// jobs into a hundred and one queries for a field most of those rows never
// render.
func (q *Queries) ListVideoRouteEnvelopes(ctx context.Context, ids []pgtype.UUID) ([]ListVideoRouteEnvelopesRow, error) {
	rows, err := q.db.Query(ctx, listVideoRouteEnvelopes, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideoRouteEnvelopesRow
	for rows.Next() {
		var i ListVideoRouteEnvelopesRow
		if err := rows.Scan(&i.ID, &i.VideoEnvelope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoJobNotFound = `-- name: MarkVideoJobNotFound :one
UPDATE gateway_async_jobs
   SET not_found_count = not_found_count + 1, next_poll_at = now() + $1::interval
 WHERE id = $2
RETURNING not_found_count
`

type MarkVideoJobNotFoundParams struct {
	PollAfter pgtype.Interval
	ID        pgtype.UUID
}

func (q *Queries) MarkVideoJobNotFound(ctx context.Context, arg MarkVideoJobNotFoundParams) (int16, error) {
	row := q.db.QueryRow(ctx, markVideoJobNotFound, arg.PollAfter, arg.ID)
	var not_found_count int16
	err := row.Scan(&not_found_count)
	return not_found_count, err
}

const markVideoJobProgress = `-- name: MarkVideoJobProgress :exec
UPDATE gateway_async_jobs
   SET status = $1, upstream_status = $2, progress = $3,
       next_poll_at = now() + $4::interval
 WHERE id = $5 AND status IN ('queued', 'in_progress')
`

type MarkVideoJobProgressParams struct {
	Status         string
	UpstreamStatus string
	Progress       int16
	PollAfter      pgtype.Interval
	ID             pgtype.UUID
}

func (q *Queries) MarkVideoJobProgress(ctx context.Context, arg MarkVideoJobProgressParams) error {
	_, err := q.db.Exec(ctx, markVideoJobProgress,
		arg.Status,
		arg.UpstreamStatus,
		arg.Progress,
		arg.PollAfter,
		arg.ID,
	)
	return err
}

const markVideoJobSubmitted = `-- name: MarkVideoJobSubmitted :exec
UPDATE gateway_async_jobs
   SET upstream_id = $1, upstream_status = $2,
       status = $3, submitted_at = now(), next_poll_at = now() + $4::interval
 WHERE id = $5
`

type MarkVideoJobSubmittedParams struct {
	UpstreamID     string
	UpstreamStatus string
	Status         string
	PollAfter      pgtype.Interval
	ID             pgtype.UUID
}

func (q *Queries) MarkVideoJobSubmitted(ctx context.Context, arg MarkVideoJobSubmittedParams) error {
	_, err := q.db.Exec(ctx, markVideoJobSubmitted,
		arg.UpstreamID,
		arg.UpstreamStatus,
		arg.Status,
		arg.PollAfter,
		arg.ID,
	)
	return err
}

const markVideoJobTerminal = `-- name: MarkVideoJobTerminal :execrows
UPDATE gateway_async_jobs
   SET status = $1, upstream_status = $2, terminal_at = now(),
       error_code = $3, error_message = $4,
       upstream_artifact_ref = $5,
       upstream_artifact_expires_at = $6,
       progress = CASE WHEN $1::text = 'completed' THEN 100 ELSE progress END,
       next_poll_at = NULL
 WHERE id = $7 AND status IN ('queued', 'in_progress')
`

type MarkVideoJobTerminalParams struct {
	Status                    string
	UpstreamStatus            string
	ErrorCode                 string
	ErrorMessage              string
	UpstreamArtifactRef       string
	UpstreamArtifactExpiresAt pgtype.Timestamptz
	ID                        pgtype.UUID
}

// The terminal transition and nothing else. Settlement is a separate statement
// in the same transaction, guarded on settlement_state, so that a crash between
// the two leaves a row the sweeper can still finish.
func (q *Queries) MarkVideoJobTerminal(ctx context.Context, arg MarkVideoJobTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markVideoJobTerminal,
		arg.Status,
		arg.UpstreamStatus,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.UpstreamArtifactRef,
		arg.UpstreamArtifactExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orphanVideoJobHold = `-- name: OrphanVideoJobHold :exec
UPDATE gateway_async_jobs SET settlement_state = 'orphaned'
 WHERE id = $1 AND settlement_state IN ('held', 'protected')
`

func (q *Queries) OrphanVideoJobHold(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, orphanVideoJobHold, id)
	return err
}

const protectVideoJobHold = `-- name: ProtectVideoJobHold :exec
UPDATE gateway_async_jobs
   SET settlement_state = 'protected', hold_expires_at = NULL
 WHERE id = $1 AND settlement_state = 'held'
`

func (q *Queries) ProtectVideoJobHold(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, protectVideoJobHold, id)
	return err
}

const recordVideoJobArtifact = `-- name: RecordVideoJobArtifact :exec
UPDATE gateway_async_jobs
   SET artifact_key = $1, artifact_bytes = $2,
       artifact_content_type = $3, artifact_fetched_at = now()
 WHERE id = $4
`

type RecordVideoJobArtifactParams struct {
	ArtifactKey         string
	ArtifactBytes       int64
	ArtifactContentType string
	ID                  pgtype.UUID
}

func (q *Queries) RecordVideoJobArtifact(ctx context.Context, arg RecordVideoJobArtifactParams) error {
	_, err := q.db.Exec(ctx, recordVideoJobArtifact,
		arg.ArtifactKey,
		arg.ArtifactBytes,
		arg.ArtifactContentType,
		arg.ID,
	)
	return err
}

const settleVideoJob = `-- name: SettleVideoJob :execrows
UPDATE gateway_async_jobs
   SET settlement_state = 'settled', charged_nano = $1
 WHERE id = $2 AND settlement_state IN ('held', 'protected', 'orphaned')
`

type SettleVideoJobParams struct {
	ChargedNano int64
	ID          pgtype.UUID
}

// The idempotency guard for money. A duplicate poll, a racing replica and a
// job retry all converge here, and only one of them updates a row.
//
// `orphaned` is in the list because that job still owes a charge -- its
// reservation was reclaimed while it was running, and it settles late through
// the replay queue. Leaving it out made that whole branch unreachable: the
// guard matched nothing, the transaction rolled back, and the charge was lost
// silently.
func (q *Queries) SettleVideoJob(ctx context.Context, arg SettleVideoJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleVideoJob, arg.ChargedNano, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const voidVideoJob = `-- name: VoidVideoJob :execrows
UPDATE gateway_async_jobs
   SET settlement_state = 'voided', charged_nano = 0
 WHERE id = $1 AND settlement_state IN ('held', 'protected')
`

func (q *Queries) VoidVideoJob(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, voidVideoJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
