// Code generated by tools/errgen from api/errors-core.yaml. DO NOT EDIT.

export const ErrorCodes = {
  CommonConflict: "common.conflict",
  CommonForbidden: "common.forbidden",
  CommonIdempotencyInFlight: "common.idempotency_in_flight",
  CommonIdempotencyMismatch: "common.idempotency_mismatch",
  CommonInsufficientCredits: "common.insufficient_credits",
  CommonInternal: "common.internal",
  CommonMethodNotAllowed: "common.method_not_allowed",
  CommonNotFound: "common.not_found",
  CommonOrgSuspended: "common.org_suspended",
  CommonPayloadTooLarge: "common.payload_too_large",
  CommonPreconditionFailed: "common.precondition_failed",
  CommonRateLimited: "common.rate_limited",
  CommonSettingsReasonRequired: "common.settings_reason_required",
  CommonSettingsSectionInvalid: "common.settings_section_invalid",
  CommonUnauthenticated: "common.unauthenticated",
  CommonUnavailable: "common.unavailable",
  CommonUnprocessable: "common.unprocessable",
  CommonValidation: "common.validation",
  GatewayAllProvidersFailed: "gateway.all_providers_failed",
  GatewayInsufficientCredits: "gateway.insufficient_credits",
  GatewayInsufficientScope: "gateway.insufficient_scope",
  GatewayInternal: "gateway.internal",
  GatewayInvalidApiKey: "gateway.invalid_api_key",
  GatewayInvalidRequest: "gateway.invalid_request",
  GatewayKeyBudgetExceeded: "gateway.key_budget_exceeded",
  GatewayKeyExpired: "gateway.key_expired",
  GatewayKeyRevoked: "gateway.key_revoked",
  GatewayModelDisabled: "gateway.model_disabled",
  GatewayModelNotFound: "gateway.model_not_found",
  GatewayModelTierDisabled: "gateway.model_tier_disabled",
  GatewayModelUnpriced: "gateway.model_unpriced",
  GatewayOrgSuspended: "gateway.org_suspended",
  GatewayRateLimited: "gateway.rate_limited",
  GatewayRequestTooLarge: "gateway.request_too_large",
  GatewayResourceNotFound: "gateway.resource_not_found",
  GatewaySaturated: "gateway.saturated",
  GatewayStateRouteUnavailable: "gateway.state_route_unavailable",
  GatewayUpstreamTimeout: "gateway.upstream_timeout",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ErrorCodeDef {
  status: number;
  title: string;
  titleZh: string;
}

export const errorCodeDefs: Record<ErrorCode, ErrorCodeDef> = {
  "common.conflict": { status: 409, title: "Conflict", titleZh: "资源状态冲突，请稍后重试" },
  "common.forbidden": { status: 403, title: "Insufficient permissions", titleZh: "权限不足" },
  "common.idempotency_in_flight": {
    status: 409,
    title: "Original request still in flight",
    titleZh: "首次请求处理中",
  },
  "common.idempotency_mismatch": {
    status: 422,
    title: "Idempotency key reused with different request",
    titleZh: "幂等键与请求内容不匹配",
  },
  "common.insufficient_credits": {
    status: 402,
    title: "Insufficient credits",
    titleZh: "余额不足，请充值",
  },
  "common.internal": { status: 500, title: "Internal error", titleZh: "服务内部错误" },
  "common.method_not_allowed": { status: 405, title: "Method not allowed", titleZh: "方法不允许" },
  "common.not_found": { status: 404, title: "Resource not found", titleZh: "资源不存在" },
  "common.org_suspended": { status: 403, title: "Organization suspended", titleZh: "组织已被封禁" },
  "common.payload_too_large": { status: 413, title: "Payload too large", titleZh: "请求体过大" },
  "common.precondition_failed": {
    status: 412,
    title: "Precondition failed",
    titleZh: "资源已变更，请刷新后重试",
  },
  "common.rate_limited": { status: 429, title: "Too many requests", titleZh: "请求过于频繁" },
  "common.settings_reason_required": {
    status: 422,
    title: "A reason is required for this change",
    titleZh: "这项变更必须填写原因",
  },
  "common.settings_section_invalid": {
    status: 422,
    title: "Settings section is inconsistent",
    titleZh: "设置分组不一致",
  },
  "common.unauthenticated": { status: 401, title: "Authentication required", titleZh: "需要登录" },
  "common.unavailable": {
    status: 503,
    title: "Temporarily unavailable",
    titleZh: "暂时不可用，请稍后重试",
  },
  "common.unprocessable": {
    status: 422,
    title: "Request value is outside the accepted range",
    titleZh: "请求值超出允许范围",
  },
  "common.validation": {
    status: 400,
    title: "Request validation failed",
    titleZh: "请求参数校验失败",
  },
  "gateway.all_providers_failed": {
    status: 502,
    title: "All upstream providers failed",
    titleZh: "所有上游渠道均失败",
  },
  "gateway.insufficient_credits": {
    status: 402,
    title: "Insufficient credits",
    titleZh: "余额不足",
  },
  "gateway.insufficient_scope": {
    status: 403,
    title: "API key lacks required scope",
    titleZh: "API Key 缺少所需权限范围",
  },
  "gateway.internal": { status: 500, title: "Internal error", titleZh: "服务内部错误" },
  "gateway.invalid_api_key": { status: 401, title: "Invalid API key", titleZh: "API Key 无效" },
  "gateway.invalid_request": { status: 400, title: "Invalid request", titleZh: "请求无效" },
  "gateway.key_budget_exceeded": {
    status: 402,
    title: "API key budget exceeded",
    titleZh: "API Key 预算已用尽",
  },
  "gateway.key_expired": { status: 401, title: "API key expired", titleZh: "API Key 已过期" },
  "gateway.key_revoked": { status: 401, title: "API key revoked", titleZh: "API Key 已吊销" },
  "gateway.model_disabled": {
    status: 503,
    title: "Model temporarily disabled",
    titleZh: "模型已临时停用",
  },
  "gateway.model_not_found": {
    status: 404,
    title: "Model not found",
    titleZh: "模型不存在或不可用",
  },
  "gateway.model_tier_disabled": {
    status: 403,
    title: "Model access tier disabled",
    titleZh: "账号的模型准入档已停用，请联系客服",
  },
  "gateway.model_unpriced": {
    status: 503,
    title: "Model is not priced",
    titleZh: "模型未配置定价，暂不可用",
  },
  "gateway.org_suspended": {
    status: 403,
    title: "Organization suspended",
    titleZh: "组织已被封禁",
  },
  "gateway.rate_limited": { status: 429, title: "Rate limit exceeded", titleZh: "请求频率超限" },
  "gateway.request_too_large": {
    status: 413,
    title: "Request too large",
    titleZh: "请求体超出限制",
  },
  "gateway.resource_not_found": {
    status: 404,
    title: "Resource not found",
    titleZh: "资源不存在或已过期",
  },
  "gateway.saturated": {
    status: 429,
    title: "Upstream capacity saturated",
    titleZh: "上游容量已饱和",
  },
  "gateway.state_route_unavailable": {
    status: 503,
    title: "Stateful resource route unavailable",
    titleZh: "有状态资源的原始渠道或凭证暂不可用",
  },
  "gateway.upstream_timeout": { status: 502, title: "Upstream timeout", titleZh: "上游超时" },
};
