// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package communitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO orgs (slug, name, kind)
VALUES ('team-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 12),
        $1, 'team')
RETURNING id, name, status, created_at
`

type CreateTeamRow struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

// A team is an org with a generated slug.
//
// The slug is generated here rather than derived from the name, and is never
// shown or edited. A hosted deployment addresses organizations by it; giving
// this deployment a second, human-edited identifier for the same row would
// invite the two to disagree. Deriving it from the name would also make two
// teams called the same thing collide on a value the operator never typed and
// cannot see, and that error has nowhere sensible to point.
//
// A collision here raises the unique violation rather than passing silently,
// which is the right direction: 48 bits makes it vanishingly unlikely, and if
// it ever happens the operator sees an error instead of a team quietly landing
// in another team's row.
func (q *Queries) CreateTeam(ctx context.Context, name string) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i CreateTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getKeyTeam = `-- name: GetKeyTeam :one
SELECT org_id FROM api_keys WHERE id = $1
`

// Which team a key belongs to.
//
// Key operations here address a key by id with no team in the path, while the
// shared key service scopes every write by organisation. This is the lookup
// that joins the two: without it, editing a key in any team but the first would
// answer "not found", which reads as "no such key".
func (q *Queries) GetKeyTeam(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getKeyTeam, id)
	var org_id pgtype.UUID
	err := row.Scan(&org_id)
	return org_id, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, status, created_at FROM orgs WHERE id = $1
`

type GetTeamRow struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (GetTeamRow, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i GetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveKeyHashesForTeam = `-- name: ListActiveKeyHashesForTeam :many
SELECT key_hash FROM api_keys WHERE org_id = $1 AND status = 'active'
`

// Suspending a team must reach the data plane now, not when the identity cache
// expires. Cache keys are built from the key hash, so invalidating by team
// means looking that team's hashes up first.
//
// Only active keys: a revoked one has its own invalidation path and should not
// be re-entering the cache anyway.
func (q *Queries) ListActiveKeyHashesForTeam(ctx context.Context, orgID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveKeyHashesForTeam, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key_hash string
		if err := rows.Scan(&key_hash); err != nil {
			return nil, err
		}
		items = append(items, key_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many

SELECT o.id, o.name, o.status, o.created_at,
       (SELECT count(*) FROM api_keys k
        WHERE k.org_id = o.id AND k.status = 'active')::bigint AS key_count
FROM orgs o
ORDER BY o.created_at, o.id
LIMIT 200
`

type ListTeamsRow struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	KeyCount  int64
}

// Teams: the organizations of a self-hosted deployment.
//
// These live in their own query set rather than in the shared one, and the
// reason is what the shared set would then contain. A hosted deployment owns
// an organization's whole lifecycle -- a profile row, a deletion window, the
// membership that authorizes writing it -- and a plain "insert an org" next to
// those is an insert that skips all of them. Shared code is code both
// deployments should call, and this is code only one of them should.
// The teams this instance serves, with how many keys each has.
//
// Oldest first: the team created at first start is always the first row, so
// the list does not reorder underneath somebody as teams are added.
//
// The key count is only the active ones. A revoked key is history, and
// counting it would make a team that has issued and revoked one key look the
// same as a team that has one working key.
func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.KeyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE orgs SET
    name       = coalesce($1, name),
    status     = coalesce($2, status),
    updated_at = now()
WHERE id = $3
RETURNING id, name, status, created_at
`

type UpdateTeamParams struct {
	Name   pgtype.Text
	Status pgtype.Text
	ID     pgtype.UUID
}

type UpdateTeamRow struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

// Partial update: NULL leaves the field alone.
//
// `status` is limited to active and suspended by the application. The column
// also accepts pending_delete, which belongs to a deletion flow this
// deployment does not have -- writing it here would leave a team in a state
// nothing ever advances out of.
func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (UpdateTeamRow, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.Name, arg.Status, arg.ID)
	var i UpdateTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
