package config_test

import (
	"flag"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	foundation "github.com/fairlb/fairlb/foundation/config"
	communityconfig "github.com/fairlb/fairlb/internal/community/config"
)

var updateSurface = flag.Bool("update-env-surface", false, "rewrite the Community env-surface golden")

func TestEnvSurfaceMatchesMetadata(t *testing.T) {
	seen := map[string]bool{}
	src := foundation.MapSource{Seen: seen, Values: map[string]string{
		"DATABASE_URL": "postgres://x", "REDIS_URL": "redis://x", "SECRET_KEY": strings.Repeat("ab", 32),
		"DRIVER_CACHE": "redis", "DRIVER_RATELIMIT": "redis", "DRIVER_BREAKER": "redis", "DRIVER_LOCK": "redis",
		"FAIRLB_ADMIN_EMAIL": "a@example.com", "FAIRLB_ADMIN_PASSWORD": "password",
		"FAIRLB_SETUP_TOKEN": strings.Repeat("t", 32), "PUBLIC_URL": "https://example.com",
	}}
	if _, err := communityconfig.LoadRuntime(src); err != nil {
		t.Fatalf("full Community fixture did not reach the end of LoadRuntime: %v", err)
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	slices.Sort(names)
	metadata, err := foundation.ExpandedDescriptors(foundation.SharedDescriptors, communityconfig.Descriptors)
	if err != nil {
		t.Fatal(err)
	}
	metadataNames := make([]string, len(metadata))
	for i, descriptor := range metadata {
		metadataNames[i] = descriptor.Name
	}
	if !slices.Equal(names, metadataNames) {
		t.Fatalf("actual reads and metadata differ\nreads: %s\nmetadata: %s", strings.Join(names, ", "), strings.Join(metadataNames, ", "))
	}

	golden := filepath.Join("testdata", "env-surface.txt")
	body := "# Generated by internal/community/config/surface_test.go. Do not edit.\n" + strings.Join(names, "\n") + "\n"
	if *updateSurface {
		if err := os.MkdirAll(filepath.Dir(golden), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden: %v; generate with -update-env-surface", err)
	}
	if string(want) != body {
		t.Fatal("Community environment surface differs; regenerate the golden and update delivery/docs")
	}
}
