// Code generated by tools/errgen from api/errors-core.yaml. DO NOT EDIT.

// Package errcode is the registry of stable error codes.
package errcode

// Def describes one error code: the problem+json code plus its default
// status and title.
type Def struct {
	Code    string
	Status  int
	Title   string
	TitleZH string
}

const (
	CommonConflict               = "common.conflict"
	CommonForbidden              = "common.forbidden"
	CommonIdempotencyInFlight    = "common.idempotency_in_flight"
	CommonIdempotencyMismatch    = "common.idempotency_mismatch"
	CommonInsufficientCredits    = "common.insufficient_credits"
	CommonInternal               = "common.internal"
	CommonMethodNotAllowed       = "common.method_not_allowed"
	CommonNotFound               = "common.not_found"
	CommonOrgSuspended           = "common.org_suspended"
	CommonPayloadTooLarge        = "common.payload_too_large"
	CommonPreconditionFailed     = "common.precondition_failed"
	CommonRateLimited            = "common.rate_limited"
	CommonSettingsReasonRequired = "common.settings_reason_required"
	CommonSettingsSectionInvalid = "common.settings_section_invalid"
	CommonUnauthenticated        = "common.unauthenticated"
	CommonUnavailable            = "common.unavailable"
	CommonUnprocessable          = "common.unprocessable"
	CommonValidation             = "common.validation"
	GatewayAllProvidersFailed    = "gateway.all_providers_failed"
	GatewayInsufficientCredits   = "gateway.insufficient_credits"
	GatewayInsufficientScope     = "gateway.insufficient_scope"
	GatewayInternal              = "gateway.internal"
	GatewayInvalidApiKey         = "gateway.invalid_api_key"
	GatewayInvalidRequest        = "gateway.invalid_request"
	GatewayKeyBudgetExceeded     = "gateway.key_budget_exceeded"
	GatewayKeyExpired            = "gateway.key_expired"
	GatewayKeyRevoked            = "gateway.key_revoked"
	GatewayModelDisabled         = "gateway.model_disabled"
	GatewayModelNotFound         = "gateway.model_not_found"
	GatewayModelTierDisabled     = "gateway.model_tier_disabled"
	GatewayModelUnpriced         = "gateway.model_unpriced"
	GatewayOrgSuspended          = "gateway.org_suspended"
	GatewayRateLimited           = "gateway.rate_limited"
	GatewayRequestTooLarge       = "gateway.request_too_large"
	GatewayResourceNotFound      = "gateway.resource_not_found"
	GatewaySaturated             = "gateway.saturated"
	GatewayStateRouteUnavailable = "gateway.state_route_unavailable"
	GatewayUpstreamTimeout       = "gateway.upstream_timeout"
)

// registry indexes every definition by code. Unexported on purpose: an error
// code is part of the public contract, and a package-level map anyone can
// assign into makes "only the generator writes this" unenforceable. Read it
// through Lookup/All (ADR-0161).
var registry = map[string]Def{
	CommonConflict:               {Code: CommonConflict, Status: 409, Title: "Conflict", TitleZH: "资源状态冲突，请稍后重试"},
	CommonForbidden:              {Code: CommonForbidden, Status: 403, Title: "Insufficient permissions", TitleZH: "权限不足"},
	CommonIdempotencyInFlight:    {Code: CommonIdempotencyInFlight, Status: 409, Title: "Original request still in flight", TitleZH: "首次请求处理中"},
	CommonIdempotencyMismatch:    {Code: CommonIdempotencyMismatch, Status: 422, Title: "Idempotency key reused with different request", TitleZH: "幂等键与请求内容不匹配"},
	CommonInsufficientCredits:    {Code: CommonInsufficientCredits, Status: 402, Title: "Insufficient credits", TitleZH: "余额不足，请充值"},
	CommonInternal:               {Code: CommonInternal, Status: 500, Title: "Internal error", TitleZH: "服务内部错误"},
	CommonMethodNotAllowed:       {Code: CommonMethodNotAllowed, Status: 405, Title: "Method not allowed", TitleZH: "方法不允许"},
	CommonNotFound:               {Code: CommonNotFound, Status: 404, Title: "Resource not found", TitleZH: "资源不存在"},
	CommonOrgSuspended:           {Code: CommonOrgSuspended, Status: 403, Title: "Organization suspended", TitleZH: "组织已被封禁"},
	CommonPayloadTooLarge:        {Code: CommonPayloadTooLarge, Status: 413, Title: "Payload too large", TitleZH: "请求体过大"},
	CommonPreconditionFailed:     {Code: CommonPreconditionFailed, Status: 412, Title: "Precondition failed", TitleZH: "资源已变更，请刷新后重试"},
	CommonRateLimited:            {Code: CommonRateLimited, Status: 429, Title: "Too many requests", TitleZH: "请求过于频繁"},
	CommonSettingsReasonRequired: {Code: CommonSettingsReasonRequired, Status: 422, Title: "A reason is required for this change", TitleZH: "这项变更必须填写原因"},
	CommonSettingsSectionInvalid: {Code: CommonSettingsSectionInvalid, Status: 422, Title: "Settings section is inconsistent", TitleZH: "设置分组不一致"},
	CommonUnauthenticated:        {Code: CommonUnauthenticated, Status: 401, Title: "Authentication required", TitleZH: "需要登录"},
	CommonUnavailable:            {Code: CommonUnavailable, Status: 503, Title: "Temporarily unavailable", TitleZH: "暂时不可用，请稍后重试"},
	CommonUnprocessable:          {Code: CommonUnprocessable, Status: 422, Title: "Request value is outside the accepted range", TitleZH: "请求值超出允许范围"},
	CommonValidation:             {Code: CommonValidation, Status: 400, Title: "Request validation failed", TitleZH: "请求参数校验失败"},
	GatewayAllProvidersFailed:    {Code: GatewayAllProvidersFailed, Status: 502, Title: "All upstream providers failed", TitleZH: "所有上游渠道均失败"},
	GatewayInsufficientCredits:   {Code: GatewayInsufficientCredits, Status: 402, Title: "Insufficient credits", TitleZH: "余额不足"},
	GatewayInsufficientScope:     {Code: GatewayInsufficientScope, Status: 403, Title: "API key lacks required scope", TitleZH: "API Key 缺少所需权限范围"},
	GatewayInternal:              {Code: GatewayInternal, Status: 500, Title: "Internal error", TitleZH: "服务内部错误"},
	GatewayInvalidApiKey:         {Code: GatewayInvalidApiKey, Status: 401, Title: "Invalid API key", TitleZH: "API Key 无效"},
	GatewayInvalidRequest:        {Code: GatewayInvalidRequest, Status: 400, Title: "Invalid request", TitleZH: "请求无效"},
	GatewayKeyBudgetExceeded:     {Code: GatewayKeyBudgetExceeded, Status: 402, Title: "API key budget exceeded", TitleZH: "API Key 预算已用尽"},
	GatewayKeyExpired:            {Code: GatewayKeyExpired, Status: 401, Title: "API key expired", TitleZH: "API Key 已过期"},
	GatewayKeyRevoked:            {Code: GatewayKeyRevoked, Status: 401, Title: "API key revoked", TitleZH: "API Key 已吊销"},
	GatewayModelDisabled:         {Code: GatewayModelDisabled, Status: 503, Title: "Model temporarily disabled", TitleZH: "模型已临时停用"},
	GatewayModelNotFound:         {Code: GatewayModelNotFound, Status: 404, Title: "Model not found", TitleZH: "模型不存在或不可用"},
	GatewayModelTierDisabled:     {Code: GatewayModelTierDisabled, Status: 403, Title: "Model access tier disabled", TitleZH: "账号的模型准入档已停用，请联系客服"},
	GatewayModelUnpriced:         {Code: GatewayModelUnpriced, Status: 503, Title: "Model is not priced", TitleZH: "模型未配置定价，暂不可用"},
	GatewayOrgSuspended:          {Code: GatewayOrgSuspended, Status: 403, Title: "Organization suspended", TitleZH: "组织已被封禁"},
	GatewayRateLimited:           {Code: GatewayRateLimited, Status: 429, Title: "Rate limit exceeded", TitleZH: "请求频率超限"},
	GatewayRequestTooLarge:       {Code: GatewayRequestTooLarge, Status: 413, Title: "Request too large", TitleZH: "请求体超出限制"},
	GatewayResourceNotFound:      {Code: GatewayResourceNotFound, Status: 404, Title: "Resource not found", TitleZH: "资源不存在或已过期"},
	GatewaySaturated:             {Code: GatewaySaturated, Status: 429, Title: "Upstream capacity saturated", TitleZH: "上游容量已饱和"},
	GatewayStateRouteUnavailable: {Code: GatewayStateRouteUnavailable, Status: 503, Title: "Stateful resource route unavailable", TitleZH: "有状态资源的原始渠道或凭证暂不可用"},
	GatewayUpstreamTimeout:       {Code: GatewayUpstreamTimeout, Status: 502, Title: "Upstream timeout", TitleZH: "上游超时"},
}

// All returns a copy of this segment's definitions. A copy, so that walking
// the contract cannot become writing to it.
func All() map[string]Def {
	out := make(map[string]Def, len(registry))
	for code, d := range registry {
		out[code] = d
	}
	return out
}
