// Package staffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package staffapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiKeySpendLimitInterval.
const (
	ApiKeySpendLimitIntervalDaily   ApiKeySpendLimitInterval = "daily"
	ApiKeySpendLimitIntervalMonthly ApiKeySpendLimitInterval = "monthly"
	ApiKeySpendLimitIntervalTotal   ApiKeySpendLimitInterval = "total"
)

// Valid indicates whether the value is a known member of the ApiKeySpendLimitInterval enum.
func (e ApiKeySpendLimitInterval) Valid() bool {
	switch e {
	case ApiKeySpendLimitIntervalDaily:
		return true
	case ApiKeySpendLimitIntervalMonthly:
		return true
	case ApiKeySpendLimitIntervalTotal:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyStatus.
const (
	ApiKeyStatusActive  ApiKeyStatus = "active"
	ApiKeyStatusRevoked ApiKeyStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ApiKeyStatus enum.
func (e ApiKeyStatus) Valid() bool {
	switch e {
	case ApiKeyStatusActive:
		return true
	case ApiKeyStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for CommunityIdentityRole.
const (
	Superadmin CommunityIdentityRole = "superadmin"
)

// Valid indicates whether the value is a known member of the CommunityIdentityRole enum.
func (e CommunityIdentityRole) Valid() bool {
	switch e {
	case Superadmin:
		return true
	default:
		return false
	}
}

// Defines values for CommunityMetaSetupState.
const (
	Available CommunityMetaSetupState = "available"
	Complete  CommunityMetaSetupState = "complete"
)

// Valid indicates whether the value is a known member of the CommunityMetaSetupState enum.
func (e CommunityMetaSetupState) Valid() bool {
	switch e {
	case Available:
		return true
	case Complete:
		return true
	default:
		return false
	}
}

// Defines values for CreateKeyRequestSpendLimitInterval.
const (
	CreateKeyRequestSpendLimitIntervalDaily   CreateKeyRequestSpendLimitInterval = "daily"
	CreateKeyRequestSpendLimitIntervalMonthly CreateKeyRequestSpendLimitInterval = "monthly"
	CreateKeyRequestSpendLimitIntervalTotal   CreateKeyRequestSpendLimitInterval = "total"
)

// Valid indicates whether the value is a known member of the CreateKeyRequestSpendLimitInterval enum.
func (e CreateKeyRequestSpendLimitInterval) Valid() bool {
	switch e {
	case CreateKeyRequestSpendLimitIntervalDaily:
		return true
	case CreateKeyRequestSpendLimitIntervalMonthly:
		return true
	case CreateKeyRequestSpendLimitIntervalTotal:
		return true
	default:
		return false
	}
}

// Defines values for SettingEntryGroup.
const (
	Access     SettingEntryGroup = "access"
	Billing    SettingEntryGroup = "billing"
	Operations SettingEntryGroup = "operations"
	Retention  SettingEntryGroup = "retention"
)

// Valid indicates whether the value is a known member of the SettingEntryGroup enum.
func (e SettingEntryGroup) Valid() bool {
	switch e {
	case Access:
		return true
	case Billing:
		return true
	case Operations:
		return true
	case Retention:
		return true
	default:
		return false
	}
}

// Defines values for SettingEntryImpact.
const (
	High   SettingEntryImpact = "high"
	Normal SettingEntryImpact = "normal"
)

// Valid indicates whether the value is a known member of the SettingEntryImpact enum.
func (e SettingEntryImpact) Valid() bool {
	switch e {
	case High:
		return true
	case Normal:
		return true
	default:
		return false
	}
}

// Defines values for SettingEntryKind.
const (
	Bool          SettingEntryKind = "bool"
	DecimalString SettingEntryKind = "decimal_string"
	Email         SettingEntryKind = "email"
	Enum          SettingEntryKind = "enum"
	Int           SettingEntryKind = "int"
	MapStringInt  SettingEntryKind = "map_string_int"
	Money         SettingEntryKind = "money"
	Secret        SettingEntryKind = "secret"
	String        SettingEntryKind = "string"
	StringList    SettingEntryKind = "string_list"
)

// Valid indicates whether the value is a known member of the SettingEntryKind enum.
func (e SettingEntryKind) Valid() bool {
	switch e {
	case Bool:
		return true
	case DecimalString:
		return true
	case Email:
		return true
	case Enum:
		return true
	case Int:
		return true
	case MapStringInt:
		return true
	case Money:
		return true
	case Secret:
		return true
	case String:
		return true
	case StringList:
		return true
	default:
		return false
	}
}

// Defines values for TeamStatus.
const (
	TeamStatusActive    TeamStatus = "active"
	TeamStatusSuspended TeamStatus = "suspended"
)

// Valid indicates whether the value is a known member of the TeamStatus enum.
func (e TeamStatus) Valid() bool {
	switch e {
	case TeamStatusActive:
		return true
	case TeamStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for UpdateKeyRequestClear.
const (
	ExpiresAt    UpdateKeyRequestClear = "expires_at"
	RateLimitRpm UpdateKeyRequestClear = "rate_limit_rpm"
	RateLimitTpm UpdateKeyRequestClear = "rate_limit_tpm"
	SpendLimit   UpdateKeyRequestClear = "spend_limit"
)

// Valid indicates whether the value is a known member of the UpdateKeyRequestClear enum.
func (e UpdateKeyRequestClear) Valid() bool {
	switch e {
	case ExpiresAt:
		return true
	case RateLimitRpm:
		return true
	case RateLimitTpm:
		return true
	case SpendLimit:
		return true
	default:
		return false
	}
}

// Defines values for UpdateKeyRequestSpendLimitInterval.
const (
	UpdateKeyRequestSpendLimitIntervalDaily   UpdateKeyRequestSpendLimitInterval = "daily"
	UpdateKeyRequestSpendLimitIntervalMonthly UpdateKeyRequestSpendLimitInterval = "monthly"
	UpdateKeyRequestSpendLimitIntervalTotal   UpdateKeyRequestSpendLimitInterval = "total"
)

// Valid indicates whether the value is a known member of the UpdateKeyRequestSpendLimitInterval enum.
func (e UpdateKeyRequestSpendLimitInterval) Valid() bool {
	switch e {
	case UpdateKeyRequestSpendLimitIntervalDaily:
		return true
	case UpdateKeyRequestSpendLimitIntervalMonthly:
		return true
	case UpdateKeyRequestSpendLimitIntervalTotal:
		return true
	default:
		return false
	}
}

// Defines values for CommunityUpdateTeamJSONBodyStatus.
const (
	CommunityUpdateTeamJSONBodyStatusActive    CommunityUpdateTeamJSONBodyStatus = "active"
	CommunityUpdateTeamJSONBodyStatusSuspended CommunityUpdateTeamJSONBodyStatus = "suspended"
)

// Valid indicates whether the value is a known member of the CommunityUpdateTeamJSONBodyStatus enum.
func (e CommunityUpdateTeamJSONBodyStatus) Valid() bool {
	switch e {
	case CommunityUpdateTeamJSONBodyStatusActive:
		return true
	case CommunityUpdateTeamJSONBodyStatusSuspended:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Id Public id, prefixed `key_`
	Id         string     `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// ModelAccess Which models a key may call.
	//
	// Two fields rather than one list, because "every model" and "no model at
	// all" both have to be sayable and a single list can only say one of them.
	// With `allow_all` the key adds no restriction of its own and reaches
	// whatever the organization's admission tier allows; otherwise `models` is
	// the exact set, and an empty set refuses every model.
	//
	// A model listed here that the organization's tier does not admit is
	// rejected when it is saved, so this list can never promise more than the
	// tier behind it.
	ModelAccess *ModelAccess `json:"model_access,omitempty"`
	Name        string       `json:"name"`

	// Prefix Display prefix: the fixed key prefix plus the first 8 random characters
	Prefix string `json:"prefix"`

	// RateLimitRpm Requests per minute; absent means no limit
	RateLimitRpm *int `json:"rate_limit_rpm,omitempty"`

	// RateLimitTpm Tokens per minute; absent means no limit
	RateLimitTpm       *int                      `json:"rate_limit_tpm,omitempty"`
	Scopes             []string                  `json:"scopes"`
	SpendLimitInterval *ApiKeySpendLimitInterval `json:"spend_limit_interval,omitempty"`
	SpendLimitNano     *int64                    `json:"spend_limit_nano,omitempty"`
	Status             ApiKeyStatus              `json:"status"`

	// Tags Free-form labels, for grouping keys by project or environment
	Tags *[]string `json:"tags,omitempty"`

	// TeamId Public id of the team this key belongs to, prefixed `org_`
	TeamId         string `json:"team_id"`
	TotalSpentNano int64  `json:"total_spent_nano"`
}

// ApiKeySpendLimitInterval defines model for ApiKey.SpendLimitInterval.
type ApiKeySpendLimitInterval string

// ApiKeyStatus defines model for ApiKey.Status.
type ApiKeyStatus string

// ApiKeyCreated The create response; the key itself appears only here
type ApiKeyCreated struct {
	ApiKey ApiKey `json:"api_key"`

	// Key The full key, returned only at creation and never retrievable again
	Key string `json:"key"`
}

// CommunityIdentity defines model for CommunityIdentity.
type CommunityIdentity struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`

	// OrgId Public id (prefixed `org_`) of the single organization this instance
	// serves.
	//
	// The organization-facing endpoints take `{org_id}` in their path, and
	// this value is fixed at first start and never shown in the UI. It is
	// reported here rather than guessed or hard-coded by a client: a
	// hard-coded id would point at an organization that does not exist
	// after the database is replaced, and the symptom would be every page
	// rendering empty without an error.
	OrgId string `json:"org_id"`

	// Role Always `superadmin` here; this deployment has no role grades
	Role CommunityIdentityRole `json:"role"`
}

// CommunityIdentityRole Always `superadmin` here; this deployment has no role grades
type CommunityIdentityRole string

// CommunityLoginRequest defines model for CommunityLoginRequest.
type CommunityLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// CommunityMeta defines model for CommunityMeta.
type CommunityMeta struct {
	// SetupRequiresToken Whether POST /setup will ask for a token. Only meaningful while
	// `setup_state` is `available`. Saying so is what lets the form render
	// the field; it does not disclose the token.
	SetupRequiresToken bool `json:"setup_requires_token"`

	// SetupState `complete` — an administrator exists; show the sign-in form.
	// `available` — none exists yet; show the setup form.
	SetupState CommunityMetaSetupState `json:"setup_state"`

	// Version Build version.
	Version string `json:"version"`
}

// CommunityMetaSetupState `complete` — an administrator exists; show the sign-in form.
// `available` — none exists yet; show the setup form.
type CommunityMetaSetupState string

// CommunitySetupRequest defines model for CommunitySetupRequest.
type CommunitySetupRequest struct {
	Email openapi_types.Email `json:"email"`

	// Password At least 12 characters. This account has no second factor and is the
	// only way in, so the one length rule in this API is here.
	Password string `json:"password"`

	// Token Required when FAIRLB_SETUP_TOKEN is set.
	Token *string `json:"token,omitempty"`
}

// CreateKeyRequest defines model for CreateKeyRequest.
type CreateKeyRequest struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// ModelAccess Absent means unrestricted, the default for a new key
	ModelAccess        *ModelAccess                        `json:"model_access,omitempty"`
	Name               string                              `json:"name"`
	RateLimitRpm       *int                                `json:"rate_limit_rpm,omitempty"`
	RateLimitTpm       *int                                `json:"rate_limit_tpm,omitempty"`
	SpendLimitInterval *CreateKeyRequestSpendLimitInterval `json:"spend_limit_interval,omitempty"`
	SpendLimitNano     *int64                              `json:"spend_limit_nano,omitempty"`
	Tags               *[]string                           `json:"tags,omitempty"`

	// TeamId Which team this key belongs to; omit for the team created at first start
	TeamId *string `json:"team_id,omitempty"`
}

// CreateKeyRequestSpendLimitInterval defines model for CreateKeyRequest.SpendLimitInterval.
type CreateKeyRequestSpendLimitInterval string

// ModelAccess Which models a key may call.
//
// Two fields rather than one list, because "every model" and "no model at
// all" both have to be sayable and a single list can only say one of them.
// With `allow_all` the key adds no restriction of its own and reaches
// whatever the organization's admission tier allows; otherwise `models` is
// the exact set, and an empty set refuses every model.
//
// A model listed here that the organization's tier does not admit is
// rejected when it is saved, so this list can never promise more than the
// tier behind it.
type ModelAccess struct {
	// AllowAll True means every model the organization's tier allows; `models` must then be empty
	AllowAll bool `json:"allow_all"`

	// Models Exact model slugs, used only when `allow_all` is false
	Models []string `json:"models"`
}

// Problem RFC 9457 problem+json, the same shape every endpoint uses
type Problem struct {
	Code                 string                 `json:"code"`
	Detail               *string                `json:"detail,omitempty"`
	RequestId            *string                `json:"request_id,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SettingEntry defines model for SettingEntry.
type SettingEntry struct {
	// Default Registered default, as JSON
	Default interface{} `json:"default,omitempty"`

	// Description Fallback copy; the interface renders description_key instead
	Description *string `json:"description,omitempty"`

	// DescriptionKey Message key (`settingDesc*`) the interface translates
	DescriptionKey *string           `json:"description_key,omitempty"`
	Enum           *[]string         `json:"enum,omitempty"`
	Group          SettingEntryGroup `json:"group"`

	// Hint Display mask of a stored secret; the value itself never comes back
	Hint *string `json:"hint,omitempty"`

	// Impact high = reaches every request, every bill or data retention; needs confirmation and a reason
	Impact SettingEntryImpact `json:"impact"`
	Key    string             `json:"key"`
	Kind   SettingEntryKind   `json:"kind"`

	// Max Inclusive upper bound for int / map_string_int; in nano for money
	Max *int64 `json:"max,omitempty"`

	// Min Inclusive lower bound for int / map_string_int; in nano for money
	Min *int64 `json:"min,omitempty"`

	// Section The integration the key belongs to; one form, one transaction. Absent for a key on its own
	Section   *string    `json:"section,omitempty"`
	Set       bool       `json:"set"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UpdatedBy *string    `json:"updated_by,omitempty"`

	// Value Current value (the default when unset); absent for secrets
	Value interface{} `json:"value,omitempty"`
}

// SettingEntryGroup defines model for SettingEntry.Group.
type SettingEntryGroup string

// SettingEntryImpact high = reaches every request, every bill or data retention; needs confirmation and a reason
type SettingEntryImpact string

// SettingEntryKind defines model for SettingEntry.Kind.
type SettingEntryKind string

// SettingsBatch defines model for SettingsBatch.
type SettingsBatch struct {
	Changes []struct {
		Key string `json:"key"`

		// Value A JSON value of the registered kind; `""` clears a secret
		Value interface{} `json:"value"`
	} `json:"changes"`

	// Reason Goes into every key's audit row; required when any key is impact high
	Reason *string `json:"reason,omitempty"`
}

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time `json:"created_at"`

	// Id Public id, prefixed `org_`
	Id string `json:"id"`

	// IsDefault The team created at first start, where a key lands when none is
	// named. It cannot be suspended.
	IsDefault bool `json:"is_default"`

	// KeyCount How many active keys this team has
	KeyCount int    `json:"key_count"`
	Name     string `json:"name"`

	// Status A suspended team's keys are refused on every request
	Status TeamStatus `json:"status"`
}

// TeamStatus A suspended team's keys are refused on every request
type TeamStatus string

// UpdateKeyRequest `scopes` is not editable: these keys are for the data plane only. The
// admin API of a single-tenant deployment is served by the same process an
// administrator is already signed in to, so there is no case for calling
// it with an API key — and a credential that can grant itself more
// privilege is one more thing to attack.
type UpdateKeyRequest struct {
	// Clear Limits to clear, i.e. set back to "no limit"
	Clear     *[]UpdateKeyRequestClear `json:"clear,omitempty"`
	ExpiresAt *time.Time               `json:"expires_at,omitempty"`

	// ModelAccess Replaces the key's model gate whole. It is absent from `clear`
	// because it has no "no limit" state to return to: unrestricted is
	// said with `allow_all`.
	ModelAccess        *ModelAccess                        `json:"model_access,omitempty"`
	RateLimitRpm       *int                                `json:"rate_limit_rpm,omitempty"`
	RateLimitTpm       *int                                `json:"rate_limit_tpm,omitempty"`
	SpendLimitInterval *UpdateKeyRequestSpendLimitInterval `json:"spend_limit_interval,omitempty"`
	SpendLimitNano     *int64                              `json:"spend_limit_nano,omitempty"`
	Tags               *[]string                           `json:"tags,omitempty"`
}

// UpdateKeyRequestClear defines model for UpdateKeyRequest.Clear.
type UpdateKeyRequestClear string

// UpdateKeyRequestSpendLimitInterval defines model for UpdateKeyRequest.SpendLimitInterval.
type UpdateKeyRequestSpendLimitInterval string

// CommunityListKeysParams defines parameters for CommunityListKeys.
type CommunityListKeysParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// TeamId Whose keys to list; omit for the team created at first start.
	//
	// It lists one team rather than all of them because that is the
	// question the screen asks: keys are managed inside a team, and a
	// merged list would need a column saying which team each row is in
	// before it meant anything. The team list carries a key count, so no
	// key is hidden by this.
	TeamId *string `form:"team_id,omitempty" json:"team_id,omitempty"`
}

// CommunityCreateTeamJSONBody defines parameters for CommunityCreateTeam.
type CommunityCreateTeamJSONBody struct {
	Name string `json:"name"`
}

// CommunityUpdateTeamJSONBody defines parameters for CommunityUpdateTeam.
type CommunityUpdateTeamJSONBody struct {
	Name   *string                            `json:"name,omitempty"`
	Status *CommunityUpdateTeamJSONBodyStatus `json:"status,omitempty"`
}

// CommunityUpdateTeamJSONBodyStatus defines parameters for CommunityUpdateTeam.
type CommunityUpdateTeamJSONBodyStatus string

// CommunityLoginJSONRequestBody defines body for CommunityLogin for application/json ContentType.
type CommunityLoginJSONRequestBody = CommunityLoginRequest

// CommunityCreateKeyJSONRequestBody defines body for CommunityCreateKey for application/json ContentType.
type CommunityCreateKeyJSONRequestBody = CreateKeyRequest

// CommunityUpdateKeyJSONRequestBody defines body for CommunityUpdateKey for application/json ContentType.
type CommunityUpdateKeyJSONRequestBody = UpdateKeyRequest

// CommunityPutSettingsJSONRequestBody defines body for CommunityPutSettings for application/json ContentType.
type CommunityPutSettingsJSONRequestBody = SettingsBatch

// CommunitySetupJSONRequestBody defines body for CommunitySetup for application/json ContentType.
type CommunitySetupJSONRequestBody = CommunitySetupRequest

// CommunityCreateTeamJSONRequestBody defines body for CommunityCreateTeam for application/json ContentType.
type CommunityCreateTeamJSONRequestBody CommunityCreateTeamJSONBody

// CommunityUpdateTeamJSONRequestBody defines body for CommunityUpdateTeam for application/json ContentType.
type CommunityUpdateTeamJSONRequestBody CommunityUpdateTeamJSONBody

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.RequestId != nil {
		object["request_id"], err = json.Marshal(a.RequestId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CommunityLogin Sign in
	// (POST /auth/login)
	CommunityLogin(w http.ResponseWriter, r *http.Request)
	// CommunityLogout Sign out
	// (POST /auth/logout)
	CommunityLogout(w http.ResponseWriter, r *http.Request)
	// CommunityMe Current administrator identity
	// (GET /auth/me)
	CommunityMe(w http.ResponseWriter, r *http.Request)
	// CommunityListKeys List API keys
	// (GET /keys)
	CommunityListKeys(w http.ResponseWriter, r *http.Request, params CommunityListKeysParams)
	// CommunityCreateKey Create an API key (the key itself is returned only now)
	// (POST /keys)
	CommunityCreateKey(w http.ResponseWriter, r *http.Request)
	// CommunityRevokeKey Revoke a key
	// (DELETE /keys/{key_id})
	CommunityRevokeKey(w http.ResponseWriter, r *http.Request, keyId string)
	// CommunityUpdateKey Update a key's limits
	// (PATCH /keys/{key_id})
	CommunityUpdateKey(w http.ResponseWriter, r *http.Request, keyId string)
	// CommunityMeta Public instance metadata
	// (GET /meta)
	CommunityMeta(w http.ResponseWriter, r *http.Request)
	// CommunityListSettings Registered runtime settings with their current values
	// (GET /settings)
	CommunityListSettings(w http.ResponseWriter, r *http.Request)
	// CommunityPutSettings Write a batch of settings in one transaction
	// (PUT /settings)
	CommunityPutSettings(w http.ResponseWriter, r *http.Request)
	// CommunitySetup Create the first administrator
	// (POST /setup)
	CommunitySetup(w http.ResponseWriter, r *http.Request)
	// CommunityListTeams List teams
	// (GET /teams)
	CommunityListTeams(w http.ResponseWriter, r *http.Request)
	// CommunityCreateTeam Create a team
	// (POST /teams)
	CommunityCreateTeam(w http.ResponseWriter, r *http.Request)
	// CommunityUpdateTeam Rename or suspend a team
	// (PATCH /teams/{team_id})
	CommunityUpdateTeam(w http.ResponseWriter, r *http.Request, teamId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// CommunityLogin Sign in
// (POST /auth/login)
func (_ Unimplemented) CommunityLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityLogout Sign out
// (POST /auth/logout)
func (_ Unimplemented) CommunityLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityMe Current administrator identity
// (GET /auth/me)
func (_ Unimplemented) CommunityMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityListKeys List API keys
// (GET /keys)
func (_ Unimplemented) CommunityListKeys(w http.ResponseWriter, r *http.Request, params CommunityListKeysParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityCreateKey Create an API key (the key itself is returned only now)
// (POST /keys)
func (_ Unimplemented) CommunityCreateKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityRevokeKey Revoke a key
// (DELETE /keys/{key_id})
func (_ Unimplemented) CommunityRevokeKey(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityUpdateKey Update a key's limits
// (PATCH /keys/{key_id})
func (_ Unimplemented) CommunityUpdateKey(w http.ResponseWriter, r *http.Request, keyId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityMeta Public instance metadata
// (GET /meta)
func (_ Unimplemented) CommunityMeta(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityListSettings Registered runtime settings with their current values
// (GET /settings)
func (_ Unimplemented) CommunityListSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityPutSettings Write a batch of settings in one transaction
// (PUT /settings)
func (_ Unimplemented) CommunityPutSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunitySetup Create the first administrator
// (POST /setup)
func (_ Unimplemented) CommunitySetup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityListTeams List teams
// (GET /teams)
func (_ Unimplemented) CommunityListTeams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityCreateTeam Create a team
// (POST /teams)
func (_ Unimplemented) CommunityCreateTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CommunityUpdateTeam Rename or suspend a team
// (PATCH /teams/{team_id})
func (_ Unimplemented) CommunityUpdateTeam(w http.ResponseWriter, r *http.Request, teamId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CommunityLogin operation middleware
func (siw *ServerInterfaceWrapper) CommunityLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityLogout operation middleware
func (siw *ServerInterfaceWrapper) CommunityLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityMe operation middleware
func (siw *ServerInterfaceWrapper) CommunityMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityListKeys operation middleware
func (siw *ServerInterfaceWrapper) CommunityListKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CommunityListKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "team_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "team_id", r.URL.Query(), &params.TeamId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityListKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityCreateKey operation middleware
func (siw *ServerInterfaceWrapper) CommunityCreateKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityCreateKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityRevokeKey operation middleware
func (siw *ServerInterfaceWrapper) CommunityRevokeKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityRevokeKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityUpdateKey operation middleware
func (siw *ServerInterfaceWrapper) CommunityUpdateKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key_id" -------------
	var keyId string

	err = runtime.BindStyledParameterWithOptions("simple", "key_id", chi.URLParam(r, "key_id"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityUpdateKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityMeta operation middleware
func (siw *ServerInterfaceWrapper) CommunityMeta(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityListSettings operation middleware
func (siw *ServerInterfaceWrapper) CommunityListSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityListSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityPutSettings operation middleware
func (siw *ServerInterfaceWrapper) CommunityPutSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityPutSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunitySetup operation middleware
func (siw *ServerInterfaceWrapper) CommunitySetup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunitySetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityListTeams operation middleware
func (siw *ServerInterfaceWrapper) CommunityListTeams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityListTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityCreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CommunityCreateTeam(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityCreateTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CommunityUpdateTeam operation middleware
func (siw *ServerInterfaceWrapper) CommunityUpdateTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "team_id" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "team_id", chi.URLParam(r, "team_id"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CommunityUpdateTeam(w, r, teamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meta", wrapper.CommunityMeta)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/setup", wrapper.CommunitySetup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.CommunityLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.CommunityLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.CommunityMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/teams", wrapper.CommunityListTeams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams", wrapper.CommunityCreateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/teams/{team_id}", wrapper.CommunityUpdateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/settings", wrapper.CommunityListSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/settings", wrapper.CommunityPutSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/keys", wrapper.CommunityListKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/keys", wrapper.CommunityCreateKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/keys/{key_id}", wrapper.CommunityRevokeKey)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/keys/{key_id}", wrapper.CommunityUpdateKey)
	})

	return r
}

type ProblemApplicationProblemPlusJSONResponse Problem

type CommunityLoginRequestObject struct {
	Body *CommunityLoginJSONRequestBody
}

type CommunityLoginResponseObject interface {
	VisitCommunityLoginResponse(w http.ResponseWriter) error
}

type CommunityLogin204Response struct {
}

func (response CommunityLogin204Response) VisitCommunityLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CommunityLogin400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityLogin400ApplicationProblemPlusJSONResponse) VisitCommunityLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityLogin401ApplicationProblemPlusJSONResponse Problem

func (response CommunityLogin401ApplicationProblemPlusJSONResponse) VisitCommunityLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityLogin429ApplicationProblemPlusJSONResponse Problem

func (response CommunityLogin429ApplicationProblemPlusJSONResponse) VisitCommunityLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityLogoutRequestObject struct {
}

type CommunityLogoutResponseObject interface {
	VisitCommunityLogoutResponse(w http.ResponseWriter) error
}

type CommunityLogout204Response struct {
}

func (response CommunityLogout204Response) VisitCommunityLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CommunityLogout401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityLogout401ApplicationProblemPlusJSONResponse) VisitCommunityLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityMeRequestObject struct {
}

type CommunityMeResponseObject interface {
	VisitCommunityMeResponse(w http.ResponseWriter) error
}

type CommunityMe200JSONResponse CommunityIdentity

func (response CommunityMe200JSONResponse) VisitCommunityMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityMe401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityMe401ApplicationProblemPlusJSONResponse) VisitCommunityMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityListKeysRequestObject struct {
	Params CommunityListKeysParams
}

type CommunityListKeysResponseObject interface {
	VisitCommunityListKeysResponse(w http.ResponseWriter) error
}

type CommunityListKeys200JSONResponse struct {
	Items []ApiKey `json:"items"`
}

func (response CommunityListKeys200JSONResponse) VisitCommunityListKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityListKeys401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityListKeys401ApplicationProblemPlusJSONResponse) VisitCommunityListKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateKeyRequestObject struct {
	Body *CommunityCreateKeyJSONRequestBody
}

type CommunityCreateKeyResponseObject interface {
	VisitCommunityCreateKeyResponse(w http.ResponseWriter) error
}

type CommunityCreateKey201JSONResponse ApiKeyCreated

func (response CommunityCreateKey201JSONResponse) VisitCommunityCreateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateKey400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityCreateKey400ApplicationProblemPlusJSONResponse) VisitCommunityCreateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateKey401ApplicationProblemPlusJSONResponse Problem

func (response CommunityCreateKey401ApplicationProblemPlusJSONResponse) VisitCommunityCreateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityRevokeKeyRequestObject struct {
	KeyId string `json:"key_id"`
}

type CommunityRevokeKeyResponseObject interface {
	VisitCommunityRevokeKeyResponse(w http.ResponseWriter) error
}

type CommunityRevokeKey204Response struct {
}

func (response CommunityRevokeKey204Response) VisitCommunityRevokeKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CommunityRevokeKey401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityRevokeKey401ApplicationProblemPlusJSONResponse) VisitCommunityRevokeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityRevokeKey404ApplicationProblemPlusJSONResponse Problem

func (response CommunityRevokeKey404ApplicationProblemPlusJSONResponse) VisitCommunityRevokeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateKeyRequestObject struct {
	KeyId string `json:"key_id"`
	Body  *CommunityUpdateKeyJSONRequestBody
}

type CommunityUpdateKeyResponseObject interface {
	VisitCommunityUpdateKeyResponse(w http.ResponseWriter) error
}

type CommunityUpdateKey200JSONResponse ApiKey

func (response CommunityUpdateKey200JSONResponse) VisitCommunityUpdateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateKey400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityUpdateKey400ApplicationProblemPlusJSONResponse) VisitCommunityUpdateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateKey401ApplicationProblemPlusJSONResponse Problem

func (response CommunityUpdateKey401ApplicationProblemPlusJSONResponse) VisitCommunityUpdateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateKey404ApplicationProblemPlusJSONResponse Problem

func (response CommunityUpdateKey404ApplicationProblemPlusJSONResponse) VisitCommunityUpdateKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityMetaRequestObject struct {
}

type CommunityMetaResponseObject interface {
	VisitCommunityMetaResponse(w http.ResponseWriter) error
}

type CommunityMeta200JSONResponse CommunityMeta

func (response CommunityMeta200JSONResponse) VisitCommunityMetaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityListSettingsRequestObject struct {
}

type CommunityListSettingsResponseObject interface {
	VisitCommunityListSettingsResponse(w http.ResponseWriter) error
}

type CommunityListSettings200JSONResponse struct {
	Items []SettingEntry `json:"items"`
}

func (response CommunityListSettings200JSONResponse) VisitCommunityListSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityListSettingsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CommunityListSettingsdefaultApplicationProblemPlusJSONResponse) VisitCommunityListSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityPutSettingsRequestObject struct {
	Body *CommunityPutSettingsJSONRequestBody
}

type CommunityPutSettingsResponseObject interface {
	VisitCommunityPutSettingsResponse(w http.ResponseWriter) error
}

type CommunityPutSettings204Response struct {
}

func (response CommunityPutSettings204Response) VisitCommunityPutSettingsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CommunityPutSettingsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CommunityPutSettingsdefaultApplicationProblemPlusJSONResponse) VisitCommunityPutSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CommunitySetupRequestObject struct {
	Body *CommunitySetupJSONRequestBody
}

type CommunitySetupResponseObject interface {
	VisitCommunitySetupResponse(w http.ResponseWriter) error
}

type CommunitySetup204Response struct {
}

func (response CommunitySetup204Response) VisitCommunitySetupResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CommunitySetup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunitySetup400ApplicationProblemPlusJSONResponse) VisitCommunitySetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommunitySetup403ApplicationProblemPlusJSONResponse Problem

func (response CommunitySetup403ApplicationProblemPlusJSONResponse) VisitCommunitySetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CommunitySetup409ApplicationProblemPlusJSONResponse Problem

func (response CommunitySetup409ApplicationProblemPlusJSONResponse) VisitCommunitySetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CommunitySetup429ApplicationProblemPlusJSONResponse Problem

func (response CommunitySetup429ApplicationProblemPlusJSONResponse) VisitCommunitySetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityListTeamsRequestObject struct {
}

type CommunityListTeamsResponseObject interface {
	VisitCommunityListTeamsResponse(w http.ResponseWriter) error
}

type CommunityListTeams200JSONResponse struct {
	Items []Team `json:"items"`
}

func (response CommunityListTeams200JSONResponse) VisitCommunityListTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityListTeams401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityListTeams401ApplicationProblemPlusJSONResponse) VisitCommunityListTeamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateTeamRequestObject struct {
	Body *CommunityCreateTeamJSONRequestBody
}

type CommunityCreateTeamResponseObject interface {
	VisitCommunityCreateTeamResponse(w http.ResponseWriter) error
}

type CommunityCreateTeam201JSONResponse Team

func (response CommunityCreateTeam201JSONResponse) VisitCommunityCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateTeam400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityCreateTeam400ApplicationProblemPlusJSONResponse) VisitCommunityCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateTeam401ApplicationProblemPlusJSONResponse Problem

func (response CommunityCreateTeam401ApplicationProblemPlusJSONResponse) VisitCommunityCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityCreateTeam409ApplicationProblemPlusJSONResponse Problem

func (response CommunityCreateTeam409ApplicationProblemPlusJSONResponse) VisitCommunityCreateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateTeamRequestObject struct {
	TeamId string `json:"team_id"`
	Body   *CommunityUpdateTeamJSONRequestBody
}

type CommunityUpdateTeamResponseObject interface {
	VisitCommunityUpdateTeamResponse(w http.ResponseWriter) error
}

type CommunityUpdateTeam200JSONResponse Team

func (response CommunityUpdateTeam200JSONResponse) VisitCommunityUpdateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateTeam400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CommunityUpdateTeam400ApplicationProblemPlusJSONResponse) VisitCommunityUpdateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateTeam401ApplicationProblemPlusJSONResponse Problem

func (response CommunityUpdateTeam401ApplicationProblemPlusJSONResponse) VisitCommunityUpdateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateTeam404ApplicationProblemPlusJSONResponse Problem

func (response CommunityUpdateTeam404ApplicationProblemPlusJSONResponse) VisitCommunityUpdateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CommunityUpdateTeam409ApplicationProblemPlusJSONResponse Problem

func (response CommunityUpdateTeam409ApplicationProblemPlusJSONResponse) VisitCommunityUpdateTeamResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CommunityLogin Sign in
	// (POST /auth/login)
	CommunityLogin(ctx context.Context, request CommunityLoginRequestObject) (CommunityLoginResponseObject, error)
	// CommunityLogout Sign out
	// (POST /auth/logout)
	CommunityLogout(ctx context.Context, request CommunityLogoutRequestObject) (CommunityLogoutResponseObject, error)
	// CommunityMe Current administrator identity
	// (GET /auth/me)
	CommunityMe(ctx context.Context, request CommunityMeRequestObject) (CommunityMeResponseObject, error)
	// CommunityListKeys List API keys
	// (GET /keys)
	CommunityListKeys(ctx context.Context, request CommunityListKeysRequestObject) (CommunityListKeysResponseObject, error)
	// CommunityCreateKey Create an API key (the key itself is returned only now)
	// (POST /keys)
	CommunityCreateKey(ctx context.Context, request CommunityCreateKeyRequestObject) (CommunityCreateKeyResponseObject, error)
	// CommunityRevokeKey Revoke a key
	// (DELETE /keys/{key_id})
	CommunityRevokeKey(ctx context.Context, request CommunityRevokeKeyRequestObject) (CommunityRevokeKeyResponseObject, error)
	// CommunityUpdateKey Update a key's limits
	// (PATCH /keys/{key_id})
	CommunityUpdateKey(ctx context.Context, request CommunityUpdateKeyRequestObject) (CommunityUpdateKeyResponseObject, error)
	// CommunityMeta Public instance metadata
	// (GET /meta)
	CommunityMeta(ctx context.Context, request CommunityMetaRequestObject) (CommunityMetaResponseObject, error)
	// CommunityListSettings Registered runtime settings with their current values
	// (GET /settings)
	CommunityListSettings(ctx context.Context, request CommunityListSettingsRequestObject) (CommunityListSettingsResponseObject, error)
	// CommunityPutSettings Write a batch of settings in one transaction
	// (PUT /settings)
	CommunityPutSettings(ctx context.Context, request CommunityPutSettingsRequestObject) (CommunityPutSettingsResponseObject, error)
	// CommunitySetup Create the first administrator
	// (POST /setup)
	CommunitySetup(ctx context.Context, request CommunitySetupRequestObject) (CommunitySetupResponseObject, error)
	// CommunityListTeams List teams
	// (GET /teams)
	CommunityListTeams(ctx context.Context, request CommunityListTeamsRequestObject) (CommunityListTeamsResponseObject, error)
	// CommunityCreateTeam Create a team
	// (POST /teams)
	CommunityCreateTeam(ctx context.Context, request CommunityCreateTeamRequestObject) (CommunityCreateTeamResponseObject, error)
	// CommunityUpdateTeam Rename or suspend a team
	// (PATCH /teams/{team_id})
	CommunityUpdateTeam(ctx context.Context, request CommunityUpdateTeamRequestObject) (CommunityUpdateTeamResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CommunityLogin operation middleware
func (sh *strictHandler) CommunityLogin(w http.ResponseWriter, r *http.Request) {
	var request CommunityLoginRequestObject

	var body CommunityLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityLogin(ctx, request.(CommunityLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityLoginResponseObject); ok {
		if err := validResponse.VisitCommunityLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityLogout operation middleware
func (sh *strictHandler) CommunityLogout(w http.ResponseWriter, r *http.Request) {
	var request CommunityLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityLogout(ctx, request.(CommunityLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityLogoutResponseObject); ok {
		if err := validResponse.VisitCommunityLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityMe operation middleware
func (sh *strictHandler) CommunityMe(w http.ResponseWriter, r *http.Request) {
	var request CommunityMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityMe(ctx, request.(CommunityMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityMeResponseObject); ok {
		if err := validResponse.VisitCommunityMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityListKeys operation middleware
func (sh *strictHandler) CommunityListKeys(w http.ResponseWriter, r *http.Request, params CommunityListKeysParams) {
	var request CommunityListKeysRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityListKeys(ctx, request.(CommunityListKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityListKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityListKeysResponseObject); ok {
		if err := validResponse.VisitCommunityListKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityCreateKey operation middleware
func (sh *strictHandler) CommunityCreateKey(w http.ResponseWriter, r *http.Request) {
	var request CommunityCreateKeyRequestObject

	var body CommunityCreateKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityCreateKey(ctx, request.(CommunityCreateKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityCreateKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityCreateKeyResponseObject); ok {
		if err := validResponse.VisitCommunityCreateKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityRevokeKey operation middleware
func (sh *strictHandler) CommunityRevokeKey(w http.ResponseWriter, r *http.Request, keyId string) {
	var request CommunityRevokeKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityRevokeKey(ctx, request.(CommunityRevokeKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityRevokeKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityRevokeKeyResponseObject); ok {
		if err := validResponse.VisitCommunityRevokeKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityUpdateKey operation middleware
func (sh *strictHandler) CommunityUpdateKey(w http.ResponseWriter, r *http.Request, keyId string) {
	var request CommunityUpdateKeyRequestObject

	request.KeyId = keyId

	var body CommunityUpdateKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityUpdateKey(ctx, request.(CommunityUpdateKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityUpdateKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityUpdateKeyResponseObject); ok {
		if err := validResponse.VisitCommunityUpdateKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityMeta operation middleware
func (sh *strictHandler) CommunityMeta(w http.ResponseWriter, r *http.Request) {
	var request CommunityMetaRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityMeta(ctx, request.(CommunityMetaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityMeta")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityMetaResponseObject); ok {
		if err := validResponse.VisitCommunityMetaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityListSettings operation middleware
func (sh *strictHandler) CommunityListSettings(w http.ResponseWriter, r *http.Request) {
	var request CommunityListSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityListSettings(ctx, request.(CommunityListSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityListSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityListSettingsResponseObject); ok {
		if err := validResponse.VisitCommunityListSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityPutSettings operation middleware
func (sh *strictHandler) CommunityPutSettings(w http.ResponseWriter, r *http.Request) {
	var request CommunityPutSettingsRequestObject

	var body CommunityPutSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityPutSettings(ctx, request.(CommunityPutSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityPutSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityPutSettingsResponseObject); ok {
		if err := validResponse.VisitCommunityPutSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunitySetup operation middleware
func (sh *strictHandler) CommunitySetup(w http.ResponseWriter, r *http.Request) {
	var request CommunitySetupRequestObject

	var body CommunitySetupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunitySetup(ctx, request.(CommunitySetupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunitySetup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunitySetupResponseObject); ok {
		if err := validResponse.VisitCommunitySetupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityListTeams operation middleware
func (sh *strictHandler) CommunityListTeams(w http.ResponseWriter, r *http.Request) {
	var request CommunityListTeamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityListTeams(ctx, request.(CommunityListTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityListTeams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityListTeamsResponseObject); ok {
		if err := validResponse.VisitCommunityListTeamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityCreateTeam operation middleware
func (sh *strictHandler) CommunityCreateTeam(w http.ResponseWriter, r *http.Request) {
	var request CommunityCreateTeamRequestObject

	var body CommunityCreateTeamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityCreateTeam(ctx, request.(CommunityCreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityCreateTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityCreateTeamResponseObject); ok {
		if err := validResponse.VisitCommunityCreateTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommunityUpdateTeam operation middleware
func (sh *strictHandler) CommunityUpdateTeam(w http.ResponseWriter, r *http.Request, teamId string) {
	var request CommunityUpdateTeamRequestObject

	request.TeamId = teamId

	var body CommunityUpdateTeamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CommunityUpdateTeam(ctx, request.(CommunityUpdateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommunityUpdateTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CommunityUpdateTeamResponseObject); ok {
		if err := validResponse.VisitCommunityUpdateTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
