package staffapi

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"

	"github.com/fairlb/fairlb/foundation/db"
	"github.com/fairlb/fairlb/foundation/errcode"
	"github.com/fairlb/fairlb/foundation/httpx"
	"github.com/fairlb/fairlb/foundation/publicid"
	communitydb "github.com/fairlb/fairlb/internal/community/db"
)

// Teams: the groups a self-hosted deployment issues keys in.
//
// # Why this exists at all in a single-administrator deployment
//
// Because two of the things an administrator most often wants to say are
// statements about a group and not about a key: "these people may use only this
// model" and "this department may not exceed this many requests per minute".
// Both are configured per organization -- that is where the access tier and the
// rate ceilings live -- so without a way to have more than one organization,
// neither can be said at all here, however many keys are issued.
//
// The object already existed; every row in this deployment has always carried
// an org_id and one organization has always been created at first start. What
// was missing was any way to make a second one. So this is a surface over
// something the schema already had, not a new concept: the same rows, the same
// gateway endpoints for tier and rate configuration, and the same
// organization-scoped isolation, with the count no longer fixed at one.
//
// # Suspended, never deleted
//
// Deleting a team cascades its keys away, and leaves behind the usage rows that
// name it -- those carry org_id without a foreign key, on purpose, so that what
// was consumed survives the organization that consumed it. A delete would
// therefore turn history into rows pointing at nothing while the operator's
// intent ("stop this group") is fully served by suspension, which the data
// plane already refuses on and which is reversible.

// teamView renders a team row. The public id carries the org prefix because
// that is what it is: the same object the gateway's admin endpoints take as
// {org_id} when configuring this team's tier and rate ceilings.
func teamView(id pgtype.UUID, name, status string, createdAt pgtype.Timestamptz, keys int64, isDefault bool) Team {
	return Team{
		Id:        publicid.Format(publicid.Org, id),
		Name:      name,
		Status:    TeamStatus(status),
		IsDefault: isDefault,
		KeyCount:  int(keys),
		CreatedAt: createdAt.Time,
	}
}

func (s *Server) CommunityListTeams(ctx context.Context, _ CommunityListTeamsRequestObject) (CommunityListTeamsResponseObject, error) {
	rows, err := s.community.ListTeams(ctx)
	if err != nil {
		return nil, fmt.Errorf("staffapi: list teams: %w", err)
	}
	items := make([]Team, 0, len(rows))
	for _, r := range rows {
		items = append(items, teamView(r.ID, r.Name, r.Status, r.CreatedAt, r.KeyCount, r.ID == s.orgID))
	}
	return CommunityListTeams200JSONResponse{Items: items}, nil
}

func (s *Server) CommunityCreateTeam(ctx context.Context, req CommunityCreateTeamRequestObject) (CommunityCreateTeamResponseObject, error) {
	if req.Body == nil {
		return nil, httpx.ErrCode(errcode.CommonValidation)
	}
	name := strings.TrimSpace(req.Body.Name)
	if name == "" {
		return nil, httpx.ErrCodeDetail(errcode.CommonValidation, "A name is required")
	}
	// The slug is generated by the statement itself; see the query's comment.
	row, err := s.community.CreateTeam(ctx, name)
	if err != nil {
		return nil, fmt.Errorf("staffapi: create team: %w", err)
	}
	return CommunityCreateTeam201JSONResponse(
		teamView(row.ID, row.Name, row.Status, row.CreatedAt, 0, false)), nil
}

func (s *Server) CommunityUpdateTeam(ctx context.Context, req CommunityUpdateTeamRequestObject) (CommunityUpdateTeamResponseObject, error) {
	teamID, err := publicid.Parse(publicid.Org, req.TeamId)
	if err != nil {
		return nil, httpx.ErrCode(errcode.CommonNotFound)
	}
	if req.Body == nil {
		return nil, httpx.ErrCode(errcode.CommonValidation)
	}
	var name pgtype.Text
	if req.Body.Name != nil {
		trimmed := strings.TrimSpace(*req.Body.Name)
		if trimmed == "" {
			return nil, httpx.ErrCodeDetail(errcode.CommonValidation, "A name cannot be empty")
		}
		name = pgtype.Text{String: trimmed, Valid: true}
	}
	var status pgtype.Text
	if req.Body.Status != nil {
		// The first team is where a key lands when none is named. Suspending it
		// would refuse requests for a deployment that never opted into having
		// teams -- one team, one key, and suddenly nothing works.
		if *req.Body.Status == CommunityUpdateTeamJSONBodyStatusSuspended && teamID == s.orgID {
			return nil, httpx.ErrCodeDetail(errcode.CommonConflict,
				"The first team cannot be suspended: it is where keys are issued when no team is named")
		}
		status = pgtype.Text{String: string(*req.Body.Status), Valid: true}
	}
	row, err := s.community.UpdateTeam(ctx, communitydb.UpdateTeamParams{ID: teamID, Name: name, Status: status})
	if err != nil {
		if db.IsNoRows(err) {
			return nil, httpx.ErrCode(errcode.CommonNotFound)
		}
		return nil, fmt.Errorf("staffapi: update team: %w", err)
	}
	// Suspension has to reach the data plane now rather than when the identity
	// cache expires. The cache holds a snapshot per key, so the team's keys are
	// looked up and dropped one at a time -- the same thing the gateway's own
	// tier writes do, for the same reason.
	if status.Valid {
		s.invalidateTeamKeyCache(ctx, teamID)
	}
	return CommunityUpdateTeam200JSONResponse(
		teamView(row.ID, row.Name, row.Status, row.CreatedAt, 0, row.ID == s.orgID)), nil
}

// teamOf resolves the team a key operation names, defaulting to the first one.
//
// A team that does not exist is 404 and not "fall back to the default": writing
// a key into the wrong team because its id was mistyped is worse than being
// told the id is wrong.
func (s *Server) teamOf(ctx context.Context, id *string) (pgtype.UUID, error) {
	if id == nil || *id == "" {
		return s.orgID, nil
	}
	teamID, err := publicid.Parse(publicid.Org, *id)
	if err != nil {
		return pgtype.UUID{}, httpx.ErrCode(errcode.CommonNotFound)
	}
	if _, err := s.community.GetTeam(ctx, teamID); err != nil {
		return pgtype.UUID{}, httpx.ErrCode(errcode.CommonNotFound)
	}
	return teamID, nil
}
